package com.rilixtech.google_material_typeface;

import ohos.agp.text.Font;
import ohos.app.AbilityContext;
import com.rilixtech.materialfancybutton.typeface.IIcon;
import com.rilixtech.materialfancybutton.typeface.ITypeface;
import com.rilixtech.materialfancybutton.utils.FontUtil;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;

/**
 * ITypeface implementation using the GoogleMaterial font. It hosts a variety of icons that can be used by
 * the MaterialFancyButton Components.
 */
public class GoogleMaterial implements ITypeface {
    private static final String TTF_FILE = "googlematerial.ttf";
    private static final String GOOGLE_MATERIAL_PREFIX = "GMDI";
    public static final String GOOGLE_MATERIAL_NAME = "Google Material";
    public static final String GOOGLE_MATERIAL_VERSION = "3" + ".0.1.0.original";
    public static final String GOOGLE_MATERIAL_AUTHOR = "Google";
    public static final String GOOGLE_MATERIAL_URL = "https://github.com/google/material-design-icons";
    public static final String GOOGLE_MATERIAL_DESC = "Material design icons are the official icon set from Google that"
            + " are designed under the material design guidelines.";
    public static final String GOOGLE_MATERIAL_LICENSE = "CC-BY 4.0";
    public static final String GOOGLE_MATERIAL_LICENSE_URL = "http://creativecommons.org/licenses/by/4.0/";

    private static Font googleMaterialTypeface = null;
    private static HashMap<String, Character> googleMaterialCharMap;


    /**
     * GoogleMaterial IIcon object corresponding to this typeface for the given key.
     *
     * @param key Key for which GoogleMaterial IIcon is to be retrieved.
     */
    @Override public IIcon getIcon(String key) {
        return Icon.valueOf(key);
    }

    /**
     * Get all the GoogleMaterial icon characters in a HashMap.
     *
     * @return HashMap of all GoogleMaterial icon character names mapped to their character values.
     */
    @Override public HashMap<String, Character> getCharacters() {
        if (googleMaterialCharMap == null) {
            HashMap<String, Character> characterHashMap = new HashMap<>();
            for (Icon v : Icon.values()) {
                characterHashMap.put(v.name(), v.googleMaterialCharacter);
            }
            setChars(characterHashMap);
        }
        return googleMaterialCharMap;
    }

    /**
     * Set the GoogleMaterial Characters into a HashMap.
     */
    private static void setChars(HashMap<String, Character> characterHashMap) {
        googleMaterialCharMap = characterHashMap;
    }

    /**
     * Return the GoogleMaterial Mapping Prefix.
     *
     * @return GoogleMaterial Mapping Prefix, used by all GoogleMaterial icons.
     */
    @Override public String getMappingPrefix() {
        return GOOGLE_MATERIAL_PREFIX;
    }

    @Override public String getFontName() {
        return GOOGLE_MATERIAL_NAME;
    }

    @Override public String getVersion() {
        return GOOGLE_MATERIAL_VERSION;
    }

    @Override public int getIconCount() {
        return googleMaterialCharMap.size();
    }

    @Override public Collection<String> getIcons() {
        Collection<String> googleMaterialKeyList = new LinkedList<>();
        for (Icon value : Icon.values()) {
            googleMaterialKeyList.add(value.name());
        }
        return googleMaterialKeyList;
    }

    @Override public String getAuthor() {
        return GOOGLE_MATERIAL_AUTHOR;
    }

    @Override public String getUrl() {
        return GOOGLE_MATERIAL_URL;
    }

    @Override public String getDescription() {
        return GOOGLE_MATERIAL_DESC;
    }

    @Override public String getLicense() {
        return GOOGLE_MATERIAL_LICENSE;
    }

    @Override public String getLicenseUrl() {
        return GOOGLE_MATERIAL_LICENSE_URL;
    }

    @Override
    public Font getTypeface(AbilityContext context) {
        if (googleMaterialTypeface == null) {
            try {
                cacheTypeface(FontUtil.getFontFromRawFile(context, TTF_FILE));
            } catch (IllegalStateException e) {
                throw new IllegalStateException(e);
            }
        }
        return googleMaterialTypeface;
    }

    private static void cacheTypeface(Font font) {
        googleMaterialTypeface = font;
    }

    /**
     * Enumerates all the supported Custom Icon Unicode characters by GoogleMaterial ITypeface.
     */
    public enum Icon implements IIcon {
        GMDI_3D_ROTATION('\ue84d'),
        GMDI_AC_UNIT('\ueb3b'),
        GMDI_ACCESS_ALARM('\ue190'),
        GMDI_ACCESS_ALARMS('\ue191'),
        GMDI_ACCESS_TIME('\ue192'),
        GMDI_ACCESSIBILITY('\ue84e'),
        GMDI_ACCESSIBLE('\ue914'),
        GMDI_ACCOUNT_BALANCE('\ue84f'),
        GMDI_ACCOUNT_BALANCE_WALLET('\ue850'),
        GMDI_ACCOUNT_BOX('\ue851'),
        GMDI_ACCOUNT_CIRCLE('\ue853'),
        GMDI_ADB('\ue60e'),
        GMDI_ADD('\ue145'),
        GMDI_ADD_A_PHOTO('\ue439'),
        GMDI_ADD_ALARM('\ue193'),
        GMDI_ADD_ALERT('\ue003'),
        GMDI_ADD_BOX('\ue146'),
        GMDI_ADD_CIRCLE('\ue147'),
        GMDI_ADD_CIRCLE_OUTLINE('\ue148'),
        GMDI_ADD_LOCATION('\ue567'),
        GMDI_ADD_SHOPPING_CART('\ue854'),
        GMDI_ADD_TO_PHOTOS('\ue39d'),
        GMDI_ADD_TO_QUEUE('\ue05c'),
        GMDI_ADJUST('\ue39e'),
        GMDI_AIRLINE_SEAT_FLAT('\ue630'),
        GMDI_AIRLINE_SEAT_FLAT_ANGLED('\ue631'),
        GMDI_AIRLINE_SEAT_INDIVIDUAL_SUITE('\ue632'),
        GMDI_AIRLINE_SEAT_LEGROOM_EXTRA('\ue633'),
        GMDI_AIRLINE_SEAT_LEGROOM_NORMAL('\ue634'),
        GMDI_AIRLINE_SEAT_LEGROOM_REDUCED('\ue635'),
        GMDI_AIRLINE_SEAT_RECLINE_EXTRA('\ue636'),
        GMDI_AIRLINE_SEAT_RECLINE_NORMAL('\ue637'),
        GMDI_AIRPLANEMODE_ACTIVE('\ue195'),
        GMDI_AIRPLANEMODE_INACTIVE('\ue194'),
        GMDI_AIRPLAY('\ue055'),
        GMDI_AIRPORT_SHUTTLE('\ueb3c'),
        GMDI_ALARM('\ue855'),
        GMDI_ALARM_ADD('\ue856'),
        GMDI_ALARM_OFF('\ue857'),
        GMDI_ALARM_ON('\ue858'),
        GMDI_ALBUM('\ue019'),
        GMDI_ALL_INCLUSIVE('\ueb3d'),
        GMDI_ALL_OUT('\ue90b'),
        GMDI_ANNOUNCEMENT('\ue85a'),
        GMDI_APPS('\ue5c3'),
        GMDI_ARCHIVE('\ue149'),
        GMDI_ARROW_BACK('\ue5c4'),
        GMDI_ARROW_DOWNWARD('\ue5db'),
        GMDI_ARROW_DROP_DOWN('\ue5c5'),
        GMDI_ARROW_DROP_DOWN_CIRCLE('\ue5c6'),
        GMDI_ARROW_DROP_UP('\ue5c7'),
        GMDI_ARROW_FORWARD('\ue5c8'),
        GMDI_ARROW_UPWARD('\ue5d8'),
        GMDI_ART_TRACK('\ue060'),
        GMDI_ASPECT_RATIO('\ue85b'),
        GMDI_ASSESSMENT('\ue85c'),
        GMDI_ASSIGNMENT('\ue85d'),
        GMDI_ASSIGNMENTI_IND('\ue85e'),
        GMDI_ASSIGNMENTI_LATE('\ue85f'),
        GMDI_ASSIGNMENTI_RETURN('\ue860'),
        GMDI_ASSIGNMENTI_RETURNED('\ue861'),
        GMDI_ASSIGNMENTI_TURNED_IN('\ue862'),
        GMDI_ASSISTANT('\ue39f'),
        GMDI_ASSISTANT_PHOTO('\ue3a0'),
        GMDI_ATTACH_FILE('\ue226'),
        GMDI_ATTACH_MONEY('\ue227'),
        GMDI_ATTACHMENT('\ue2bc'),
        GMDI_AUDIOTRACK('\ue3a1'),
        GMDI_AUTORENEW('\ue863'),
        GMDI_AV_TIMER('\ue01b'),
        GMDI_BACKSPACE('\ue14a'),
        GMDI_BACKUP('\ue864'),
        GMDI_BATTERY_ALERT('\ue19c'),
        GMDI_BATTERY_CHARGING_FULL('\ue1a3'),
        GMDI_BATTERY_FULL('\ue1a4'),
        GMDI_BATTERY_STD('\ue1a5'),
        GMDI_BATTERY_UNKNOWN('\ue1a6'),
        GMDI_BEACH_ACCESS('\ueb3e'),
        GMDI_BEENHERE('\ue52d'),
        GMDI_BLOCK('\ue14b'),
        GMDI_BLUETOOTH('\ue1a7'),
        GMDI_BLUETOOTH_AUDIO('\ue60f'),
        GMDI_BLUETOOTH_CONNECTED('\ue1a8'),
        GMDI_BLUETOOTH_DISABLED('\ue1a9'),
        GMDI_BLUETOOTH_SEARCHING('\ue1aa'),
        GMDI_BLUR_CIRCULAR('\ue3a2'),
        GMDI_BLUR_LINEAR('\ue3a3'),
        GMDI_BLUR_OFF('\ue3a4'),
        GMDI_BLUR_ON('\ue3a5'),
        GMDI_BOOK('\ue865'),
        GMDI_BOOKMARK('\ue866'),
        GMDI_BOOKMARK_BORDER('\ue867'),
        GMDI_BORDER_ALL('\ue228'),
        GMDI_BORDER_BOTTOM('\ue229'),
        GMDI_BORDER_CLEAR('\ue22a'),
        GMDI_BORDER_COLOR('\ue22b'),
        GMDI_BORDER_HORIZONTAL('\ue22c'),
        GMDI_BORDER_INNER('\ue22d'),
        GMDI_BORDER_LEFT('\ue22e'),
        GMDI_BORDER_OUTER('\ue22f'),
        GMDI_BORDER_RIGHT('\ue230'),
        GMDI_BORDER_STYLE('\ue231'),
        GMDI_BORDER_TOP('\ue232'),
        GMDI_BORDER_VERTICAL('\ue233'),
        GMDI_BRANDING_WATERMARK('\ue06b'),
        GMDI_BRIGHTNESS_1('\ue3a6'),
        GMDI_BRIGHTNESS_2('\ue3a7'),
        GMDI_BRIGHTNESS_3('\ue3a8'),
        GMDI_BRIGHTNESS_4('\ue3a9'),
        GMDI_BRIGHTNESS_5('\ue3aa'),
        GMDI_BRIGHTNESS_6('\ue3ab'),
        GMDI_BRIGHTNESS_7('\ue3ac'),
        GMDI_BRIGHTNESS_AUTO('\ue1ab'),
        GMDI_BRIGHTNESS_HIGH('\ue1ac'),
        GMDI_BRIGHTNESS_LOW('\ue1ad'),
        GMDI_BRIGHTNESS_MEDIUM('\ue1ae'),
        GMDI_BROKEN_IMAGE('\ue3ad'),
        GMDI_BRUSH('\ue3ae'),
        GMDI_BUBBLE_CHART('\ue6dd'),
        GMDI_BUG_REPORT('\ue868'),
        GMDI_BUILD('\ue869'),
        GMDI_BURST_MODE('\ue43c'),
        GMDI_BUSINESS('\ue0af'),
        GMDI_BUSINESS_CENTER('\ueb3f'),
        GMDI_CACHED('\ue86a'),
        GMDI_CAKE('\ue7e9'),
        GMDI_CALL('\ue0b0'),
        GMDI_CALL_END('\ue0b1'),
        GMDI_CALL_MADE('\ue0b2'),
        GMDI_CALL_MERGE('\ue0b3'),
        GMDI_CALL_MISSED('\ue0b4'),
        GMDI_CALL_MISSED_OUTGOING('\ue0e4'),
        GMDI_CALL_RECEIVED('\ue0b5'),
        GMDI_CALL_SPLIT('\ue0b6'),
        GMDI_CALL_TO_ACTION('\ue06c'),
        GMDI_CAMERA('\ue3af'),
        GMDI_CAMERA_ALT('\ue3b0'),
        GMDI_CAMERA_ENHANCE('\ue8fc'),
        GMDI_CAMERA_FRONT('\ue3b1'),
        GMDI_CAMERA_REAR('\ue3b2'),
        GMDI_CAMERA_ROLL('\ue3b3'),
        GMDI_CANCEL('\ue5c9'),
        GMDI_CARD_GIFTCARD('\ue8f6'),
        GMDI_CARD_MEMBERSHIP('\ue8f7'),
        GMDI_CARD_TRAVEL('\ue8f8'),
        GMDI_CASINO('\ueb40'),
        GMDI_CAST('\ue307'),
        GMDI_CAST_CONNECTED('\ue308'),
        GMDI_CENTER_FOCUS_STRONG('\ue3b4'),
        GMDI_CENTER_FOCUS_WEAK('\ue3b5'),
        GMDI_CHANGE_HISTORY('\ue86b'),
        GMDI_CHAT('\ue0b7'),
        GMDI_CHAT_BUBBLE('\ue0ca'),
        GMDI_CHAT_BUBBLE_OUTLINE('\ue0cb'),
        GMDI_CHECK('\ue5ca'),
        GMDI_CHECK_BOX('\ue834'),
        GMDI_CHECK_BOX_OUTLINE_BLANK('\ue835'),
        GMDI_CHECK_CIRCLE('\ue86c'),
        GMDI_CHEVRON_LEFT('\ue5cb'),
        GMDI_CHEVRON_RIGHT('\ue5cc'),
        GMDI_CHILD_CARE('\ueb41'),
        GMDI_CHILD_FRIENDLY('\ueb42'),
        GMDI_CHROME_READER_MODE('\ue86d'),
        GMDI_CLASS('\ue86e'),
        GMDI_CLEAR('\ue14c'),
        GMDI_CLEAR_ALL('\ue0b8'),
        GMDI_CLOSE('\ue5cd'),
        GMDI_CLOSED_CAPTION('\ue01c'),
        GMDI_CLOUD('\ue2bd'),
        GMDI_CLOUD_CIRCLE('\ue2be'),
        GMDI_CLOUD_DONE('\ue2bf'),
        GMDI_CLOUD_DOWNLOAD('\ue2c0'),
        GMDI_CLOUD_OFF('\ue2c1'),
        GMDI_CLOUD_QUEUE('\ue2c2'),
        GMDI_CLOUD_UPLOAD('\ue2c3'),
        GMDI_CODE('\ue86f'),
        GMDI_COLLECTIONS('\ue3b6'),
        GMDI_COLLECTIONS_BOOKMARK('\ue431'),
        GMDI_COLOR_LENS('\ue3b7'),
        GMDI_COLORIZE('\ue3b8'),
        GMDI_COMMENT('\ue0b9'),
        GMDI_COMPARE('\ue3b9'),
        GMDI_COMPARE_ARROWS('\ue915'),
        GMDI_COMPUTER('\ue30a'),
        GMDI_CONFIRMATION_NUMBER('\ue638'),
        GMDI_CONTACT_MAIL('\ue0d0'),
        GMDI_CONTACT_PHONE('\ue0cf'),
        GMDI_CONTACTS('\ue0ba'),
        GMDI_CONTENTI_COPY('\ue14d'),
        GMDI_CONTENTI_CUT('\ue14e'),
        GMDI_CONTENTI_PASTE('\ue14f'),
        GMDI_CONTROL_POINT('\ue3ba'),
        GMDI_CONTROL_POINT_DUPLICATE('\ue3bb'),
        GMDI_COPYRIGHT('\ue90c'),
        GMDI_CREATE('\ue150'),
        GMDI_CREATE_NEW_FOLDER('\ue2cc'),
        GMDI_CREDIT_CARD('\ue870'),
        GMDI_CROP('\ue3be'),
        GMDI_CROP_16_9('\ue3bc'),
        GMDI_CROP_3_2('\ue3bd'),
        GMDI_CROP_5_4('\ue3bf'),
        GMDI_CROP_7_5('\ue3c0'),
        GMDI_CROP_DIN('\ue3c1'),
        GMDI_CROP_FREE('\ue3c2'),
        GMDI_CROP_LANDSCAPE('\ue3c3'),
        GMDI_CROP_ORIGINAL('\ue3c4'),
        GMDI_CROP_PORTRAIT('\ue3c5'),
        GMDI_CROP_ROTATE('\ue437'),
        GMDI_CROP_SQUARE('\ue3c6'),
        GMDI_DASHBOARD('\ue871'),
        GMDI_DATA_USAGE('\ue1af'),
        GMDI_DATE_RANGE('\ue916'),
        GMDI_DEHAZE('\ue3c7'),
        GMDI_DELETE('\ue872'),
        GMDI_DELETE_FOREVER('\ue92b'),
        GMDI_DELETE_SWEEP('\ue16c'),
        GMDI_DESCRIPTION('\ue873'),
        GMDI_DESKTOP_MAC('\ue30b'),
        GMDI_DESKTOP_WINDOWS('\ue30c'),
        GMDI_DETAILS('\ue3c8'),
        GMDI_DEVELOPER_BOARD('\ue30d'),
        GMDI_DEVELOPER_MODE('\ue1b0'),
        GMDI_DEVICE_HUB('\ue335'),
        GMDI_DEVICES('\ue1b1'),
        GMDI_DEVICES_OTHER('\ue337'),
        GMDI_DIALER_SIP('\ue0bb'),
        GMDI_DIALPAD('\ue0bc'),
        GMDI_DIRECTIONS('\ue52e'),
        GMDI_DIRECTIONS_BIKE('\ue52f'),
        GMDI_DIRECTIONS_BOAT('\ue532'),
        GMDI_DIRECTIONS_BUS('\ue530'),
        GMDI_DIRECTIONS_CAR('\ue531'),
        GMDI_DIRECTIONS_RAILWAY('\ue534'),
        GMDI_DIRECTIONS_RUN('\ue566'),
        GMDI_DIRECTIONS_SUBWAY('\ue533'),
        GMDI_DIRECTIONS_TRANSIT('\ue535'),
        GMDI_DIRECTIONS_WALK('\ue536'),
        GMDI_DISC_FULL('\ue610'),
        GMDI_DNS('\ue875'),
        GMDI_DO_NOT_DISTURB('\ue612'),
        GMDI_DO_NOT_DISTURB_ALT('\ue611'),
        GMDI_DO_NOT_DISTURB_OFF('\ue643'),
        GMDI_DO_NOT_DISTURB_ON('\ue644'),
        GMDI_DOCK('\ue30e'),
        GMDI_DOMAIN('\ue7ee'),
        GMDI_DONE('\ue876'),
        GMDI_DONE_ALL('\ue877'),
        GMDI_DONUT_LARGE('\ue917'),
        GMDI_DONUT_SMALL('\ue918'),
        GMDI_DRAFTS('\ue151'),
        GMDI_DRAG_HANDLE('\ue25d'),
        GMDI_DRIVE_ETA('\ue613'),
        GMDI_DVR('\ue1b2'),
        GMDI_EDIT('\ue3c9'),
        GMDI_EDIT_LOCATION('\ue568'),
        GMDI_EJECT('\ue8fb'),
        GMDI_EMAIL('\ue0be'),
        GMDI_ENHANCED_ENCRYPTION('\ue63f'),
        GMDI_EQUALIZER('\ue01d'),
        GMDI_ERROR('\ue000'),
        GMDI_ERROR_OUTLINE('\ue001'),
        GMDI_EURO_SYMBOL('\ue926'),
        GMDI_EV_STATION('\ue56d'),
        GMDI_EVENT('\ue878'),
        GMDI_EVENTI_AVAILABLE('\ue614'),
        GMDI_EVENTI_BUSY('\ue615'),
        GMDI_EVENTI_NOTE('\ue616'),
        GMDI_EVENTI_SEAT('\ue903'),
        GMDI_EXIT_TO_APP('\ue879'),
        GMDI_EXPAND_LESS('\ue5ce'),
        GMDI_EXPAND_MORE('\ue5cf'),
        GMDI_EXPLICIT('\ue01e'),
        GMDI_EXPLORE('\ue87a'),
        GMDI_EXPOSURE('\ue3ca'),
        GMDI_EXPOSURE_NEG_1('\ue3cb'),
        GMDI_EXPOSURE_NEG_2('\ue3cc'),
        GMDI_EXPOSURE_PLUS_1('\ue3cd'),
        GMDI_EXPOSURE_PLUS_2('\ue3ce'),
        GMDI_EXPOSURE_ZERO('\ue3cf'),
        GMDI_EXTENSION('\ue87b'),
        GMDI_FACE('\ue87c'),
        GMDI_FAST_FORWARD('\ue01f'),
        GMDI_FAST_REWIND('\ue020'),
        GMDI_FAVORITE('\ue87d'),
        GMDI_FAVORITE_BORDER('\ue87e'),
        GMDI_FEATURED_PLAY_LIST('\ue06d'),
        GMDI_FEATURED_VIDEO('\ue06e'),
        GMDI_FEEDBACK('\ue87f'),
        GMDI_FIBER_DVR('\ue05d'),
        GMDI_FIBER_MANUAL_RECORD('\ue061'),
        GMDI_FIBER_NEW('\ue05e'),
        GMDI_FIBER_PIN('\ue06a'),
        GMDI_FIBER_SMART_RECORD('\ue062'),
        GMDI_FILE_DOWNLOAD('\ue2c4'),
        GMDI_FILE_UPLOAD('\ue2c6'),
        GMDI_FILTER('\ue3d3'),
        GMDI_FILTER_1('\ue3d0'),
        GMDI_FILTER_2('\ue3d1'),
        GMDI_FILTER_3('\ue3d2'),
        GMDI_FILTER_4('\ue3d4'),
        GMDI_FILTER_5('\ue3d5'),
        GMDI_FILTER_6('\ue3d6'),
        GMDI_FILTER_7('\ue3d7'),
        GMDI_FILTER_8('\ue3d8'),
        GMDI_FILTER_9('\ue3d9'),
        GMDI_FILTER_9_PLUS('\ue3da'),
        GMDI_FILTER_B_AND_W('\ue3db'),
        GMDI_FILTER_CENTER_FOCUS('\ue3dc'),
        GMDI_FILTER_DRAMA('\ue3dd'),
        GMDI_FILTER_FRAMES('\ue3de'),
        GMDI_FILTER_HDR('\ue3df'),
        GMDI_FILTER_LIST('\ue152'),
        GMDI_FILTER_NONE('\ue3e0'),
        GMDI_FILTER_TILT_SHIFT('\ue3e2'),
        GMDI_FILTER_VINTAGE('\ue3e3'),
        GMDI_FIND_IN_PAGE('\ue880'),
        GMDI_FIND_REPLACE('\ue881'),
        GMDI_FINGERPRINT('\ue90d'),
        GMDI_FIRST_PAGE('\ue5dc'),
        GMDI_FITNESS_CENTER('\ueb43'),
        GMDI_FLAG('\ue153'),
        GMDI_FLARE('\ue3e4'),
        GMDI_FLASH_AUTO('\ue3e5'),
        GMDI_FLASH_OFF('\ue3e6'),
        GMDI_FLASH_ON('\ue3e7'),
        GMDI_FLIGHT('\ue539'),
        GMDI_FLIGHT_LAND('\ue904'),
        GMDI_FLIGHT_TAKEOFF('\ue905'),
        GMDI_FLIP('\ue3e8'),
        GMDI_FLIP_TO_BACK('\ue882'),
        GMDI_FLIP_TO_FRONT('\ue883'),
        GMDI_FOLDER('\ue2c7'),
        GMDI_FOLDER_OPEN('\ue2c8'),
        GMDI_FOLDER_SHARED('\ue2c9'),
        GMDI_FOLDER_SPECIAL('\ue617'),
        GMDI_FONT_DOWNLOAD('\ue167'),
        GMDI_FORMAT_ALIGN_CENTER('\ue234'),
        GMDI_FORMAT_ALIGN_JUSTIFY('\ue235'),
        GMDI_FORMAT_ALIGN_LEFT('\ue236'),
        GMDI_FORMAT_ALIGN_RIGHT('\ue237'),
        GMDI_FORMAT_BOLD('\ue238'),
        GMDI_FORMAT_CLEAR('\ue239'),
        GMDI_FORMAT_COLOR_FILL('\ue23a'),
        GMDI_FORMAT_COLOR_RESET('\ue23b'),
        GMDI_FORMAT_COLOR_TEXT('\ue23c'),
        GMDI_FORMAT_INDENTI_DECREASE('\ue23d'),
        GMDI_FORMAT_INDENTI_INCREASE('\ue23e'),
        GMDI_FORMAT_ITALIC('\ue23f'),
        GMDI_FORMAT_LINE_SPACING('\ue240'),
        GMDI_FORMAT_LIST_BULLETED('\ue241'),
        GMDI_FORMAT_LIST_NUMBERED('\ue242'),
        GMDI_FORMAT_PAINT('\ue243'),
        GMDI_FORMAT_QUOTE('\ue244'),
        GMDI_FORMAT_SHAPES('\ue25e'),
        GMDI_FORMAT_SIZE('\ue245'),
        GMDI_FORMAT_STRIKETHROUGH('\ue246'),
        GMDI_FORMAT_TEXTDIRECTION_L_TO_R('\ue247'),
        GMDI_FORMAT_TEXTDIRECTION_R_TO_L('\ue248'),
        GMDI_FORMAT_UNDERLINED('\ue249'),
        GMDI_FORUM('\ue0bf'),
        GMDI_FORWARD('\ue154'),
        GMDI_FORWARD_10('\ue056'),
        GMDI_FORWARD_30('\ue057'),
        GMDI_FORWARD_5('\ue058'),
        GMDI_FREE_BREAKFAST('\ueb44'),
        GMDI_FULLSCREEN('\ue5d0'),
        GMDI_FULLSCREEN_EXIT('\ue5d1'),
        GMDI_FUNCTIONS('\ue24a'),
        GMDI_G_TRANSLATE('\ue927'),
        GMDI_GAMEPAD('\ue30f'),
        GMDI_GAMES('\ue021'),
        GMDI_GAVEL('\ue90e'),
        GMDI_GESTURE('\ue155'),
        GMDI_GET_APP('\ue884'),
        GMDI_GIF('\ue908'),
        GMDI_GOLF_COURSE('\ueb45'),
        GMDI_GPS_FIXED('\ue1b3'),
        GMDI_GPS_NOT_FIXED('\ue1b4'),
        GMDI_GPS_OFF('\ue1b5'),
        GMDI_GRADE('\ue885'),
        GMDI_GRADIENT('\ue3e9'),
        GMDI_GRAIN('\ue3ea'),
        GMDI_GRAPHIC_EQ('\ue1b8'),
        GMDI_GRID_OFF('\ue3eb'),
        GMDI_GRID_ON('\ue3ec'),
        GMDI_GROUP('\ue7ef'),
        GMDI_GROUP_ADD('\ue7f0'),
        GMDI_GROUP_WORK('\ue886'),
        GMDI_HD('\ue052'),
        GMDI_HDR_OFF('\ue3ed'),
        GMDI_HDR_ON('\ue3ee'),
        GMDI_HDR_STRONG('\ue3f1'),
        GMDI_HDR_WEAK('\ue3f2'),
        GMDI_HEADSET('\ue310'),
        GMDI_HEADSET_MIC('\ue311'),
        GMDI_HEALING('\ue3f3'),
        GMDI_HEARING('\ue023'),
        GMDI_HELP('\ue887'),
        GMDI_HELP_OUTLINE('\ue8fd'),
        GMDI_HIGH_QUALITY('\ue024'),
        GMDI_HIGHLIGHT('\ue25f'),
        GMDI_HIGHLIGHT_OFF('\ue888'),
        GMDI_HISTORY('\ue889'),
        GMDI_HOME('\ue88a'),
        GMDI_HOT_TUB('\ueb46'),
        GMDI_HOTEL('\ue53a'),
        GMDI_HOURGLASS_EMPTY('\ue88b'),
        GMDI_HOURGLASS_FULL('\ue88c'),
        GMDI_HTTP('\ue902'),
        GMDI_HTTPS('\ue88d'),
        GMDI_IMAGE('\ue3f4'),
        GMDI_IMAGE_ASPECT_RATIO('\ue3f5'),
        GMDI_IMPORT_CONTACTS('\ue0e0'),
        GMDI_IMPORT_EXPORT('\ue0c3'),
        GMDI_IMPORTANT_DEVICES('\ue912'),
        GMDI_INBOX('\ue156'),
        GMDI_INDETERMINATE_CHECK_BOX('\ue909'),
        GMDI_INFO('\ue88e'),
        GMDI_INFO_OUTLINE('\ue88f'),
        GMDI_INPUT('\ue890'),
        GMDI_INSERT_CHART('\ue24b'),
        GMDI_INSERT_COMMENT('\ue24c'),
        GMDI_INSERT_DRIVE_FILE('\ue24d'),
        GMDI_INSERT_EMOTICON('\ue24e'),
        GMDI_INSERT_INVITATION('\ue24f'),
        GMDI_INSERT_LINK('\ue250'),
        GMDI_INSERT_PHOTO('\ue251'),
        GMDI_INVERT_COLORS('\ue891'),
        GMDI_INVERT_COLORS_OFF('\ue0c4'),
        GMDI_ISO('\ue3f6'),
        GMDI_KEYBOARD('\ue312'),
        GMDI_KEYBOARD_ARROW_DOWN('\ue313'),
        GMDI_KEYBOARD_ARROW_LEFT('\ue314'),
        GMDI_KEYBOARD_ARROW_RIGHT('\ue315'),
        GMDI_KEYBOARD_ARROW_UP('\ue316'),
        GMDI_KEYBOARD_BACKSPACE('\ue317'),
        GMDI_KEYBOARD_CAPSLOCK('\ue318'),
        GMDI_KEYBOARD_HIDE('\ue31a'),
        GMDI_KEYBOARD_RETURN('\ue31b'),
        GMDI_KEYBOARD_TAB('\ue31c'),
        GMDI_KEYBOARD_VOICE('\ue31d'),
        GMDI_KITCHEN('\ueb47'),
        GMDI_LABEL('\ue892'),
        GMDI_LABEL_OUTLINE('\ue893'),
        GMDI_LANDSCAPE('\ue3f7'),
        GMDI_LANGUAGE('\ue894'),
        GMDI_LAPTOP('\ue31e'),
        GMDI_LAPTOP_CHROMEBOOK('\ue31f'),
        GMDI_LAPTOP_MAC('\ue320'),
        GMDI_LAPTOP_WINDOWS('\ue321'),
        GMDI_LAST_PAGE('\ue5dd'),
        GMDI_LAUNCH('\ue895'),
        GMDI_LAYERS('\ue53b'),
        GMDI_LAYERS_CLEAR('\ue53c'),
        GMDI_LEAK_ADD('\ue3f8'),
        GMDI_LEAK_REMOVE('\ue3f9'),
        GMDI_LENS('\ue3fa'),
        GMDI_LIBRARY_ADD('\ue02e'),
        GMDI_LIBRARY_BOOKS('\ue02f'),
        GMDI_LIBRARY_MUSIC('\ue030'),
        GMDI_LIGHTBULB_OUTLINE('\ue90f'),
        GMDI_LINE_STYLE('\ue919'),
        GMDI_LINE_WEIGHT('\ue91a'),
        GMDI_LINEAR_SCALE('\ue260'),
        GMDI_LINK('\ue157'),
        GMDI_LINKED_CAMERA('\ue438'),
        GMDI_LIST('\ue896'),
        GMDI_LIVE_HELP('\ue0c6'),
        GMDI_LIVE_TV('\ue639'),
        GMDI_LOCAL_ACTIVITY('\ue53f'),
        GMDI_LOCAL_AIRPORT('\ue53d'),
        GMDI_LOCAL_ATM('\ue53e'),
        GMDI_LOCAL_BAR('\ue540'),
        GMDI_LOCAL_CAFE('\ue541'),
        GMDI_LOCAL_CAR_WASH('\ue542'),
        GMDI_LOCAL_CONVENIENCE_STORE('\ue543'),
        GMDI_LOCAL_DINING('\ue556'),
        GMDI_LOCAL_DRINK('\ue544'),
        GMDI_LOCAL_FLORIST('\ue545'),
        GMDI_LOCAL_GAS_STATION('\ue546'),
        GMDI_LOCAL_GROCERY_STORE('\ue547'),
        GMDI_LOCAL_HOSPITAL('\ue548'),
        GMDI_LOCAL_HOTEL('\ue549'),
        GMDI_LOCAL_LAUNDRY_SERVICE('\ue54a'),
        GMDI_LOCAL_LIBRARY('\ue54b'),
        GMDI_LOCAL_MALL('\ue54c'),
        GMDI_LOCAL_MOVIES('\ue54d'),
        GMDI_LOCAL_OFFER('\ue54e'),
        GMDI_LOCAL_PARKING('\ue54f'),
        GMDI_LOCAL_PHARMACY('\ue550'),
        GMDI_LOCAL_PHONE('\ue551'),
        GMDI_LOCAL_PIZZA('\ue552'),
        GMDI_LOCAL_PLAY('\ue553'),
        GMDI_LOCAL_POST_OFFICE('\ue554'),
        GMDI_LOCAL_PRINTSHOP('\ue555'),
        GMDI_LOCAL_SEE('\ue557'),
        GMDI_LOCAL_SHIPPING('\ue558'),
        GMDI_LOCAL_TAXI('\ue559'),
        GMDI_LOCATION_CITY('\ue7f1'),
        GMDI_LOCATION_DISABLED('\ue1b6'),
        GMDI_LOCATION_OFF('\ue0c7'),
        GMDI_LOCATION_ON('\ue0c8'),
        GMDI_LOCATION_SEARCHING('\ue1b7'),
        GMDI_LOCK('\ue897'),
        GMDI_LOCK_OPEN('\ue898'),
        GMDI_LOCK_OUTLINE('\ue899'),
        GMDI_LOOKS('\ue3fc'),
        GMDI_LOOKS_3('\ue3fb'),
        GMDI_LOOKS_4('\ue3fd'),
        GMDI_LOOKS_5('\ue3fe'),
        GMDI_LOOKS_6('\ue3ff'),
        GMDI_LOOKS_ONE('\ue400'),
        GMDI_LOOKS_TWO('\ue401'),
        GMDI_LOOP('\ue028'),
        GMDI_LOUPE('\ue402'),
        GMDI_LOW_PRIORITY('\ue16d'),
        GMDI_LOYALTY('\ue89a'),
        GMDI_MAIL('\ue158'),
        GMDI_MAIL_OUTLINE('\ue0e1'),
        GMDI_MAP('\ue55b'),
        GMDI_MARKUNREAD('\ue159'),
        GMDI_MARKUNREAD_MAILBOX('\ue89b'),
        GMDI_MEMORY('\ue322'),
        GMDI_MENU('\ue5d2'),
        GMDI_MERGE_TYPE('\ue252'),
        GMDI_MESSAGE('\ue0c9'),
        GMDI_MIC('\ue029'),
        GMDI_MIC_NONE('\ue02a'),
        GMDI_MIC_OFF('\ue02b'),
        GMDI_MMS('\ue618'),
        GMDI_MODE_COMMENT('\ue253'),
        GMDI_MODE_EDIT('\ue254'),
        GMDI_MONETIZATION_ON('\ue263'),
        GMDI_MONEY_OFF('\ue25c'),
        GMDI_MONOCHROME_PHOTOS('\ue403'),
        GMDI_MOOD('\ue7f2'),
        GMDI_MOOD_BAD('\ue7f3'),
        GMDI_MORE('\ue619'),
        GMDI_MORE_HORIZ('\ue5d3'),
        GMDI_MORE_VERT('\ue5d4'),
        GMDI_MOTORCYCLE('\ue91b'),
        GMDI_MOUSE('\ue323'),
        GMDI_MOVE_TO_INBOX('\ue168'),
        GMDI_MOVIE('\ue02c'),
        GMDI_MOVIE_CREATION('\ue404'),
        GMDI_MOVIE_FILTER('\ue43a'),
        GMDI_MULTILINE_CHART('\ue6df'),
        GMDI_MUSIC_NOTE('\ue405'),
        GMDI_MUSIC_VIDEO('\ue063'),
        GMDI_MY_LOCATION('\ue55c'),
        GMDI_NATURE('\ue406'),
        GMDI_NATURE_PEOPLE('\ue407'),
        GMDI_NAVIGATE_BEFORE('\ue408'),
        GMDI_NAVIGATE_NEXT('\ue409'),
        GMDI_NAVIGATION('\ue55d'),
        GMDI_NEAR_ME('\ue569'),
        GMDI_NETWORK_CELL('\ue1b9'),
        GMDI_NETWORK_CHECK('\ue640'),
        GMDI_NETWORK_LOCKED('\ue61a'),
        GMDI_NETWORK_WIFI('\ue1ba'),
        GMDI_NEW_RELEASES('\ue031'),
        GMDI_NEXT_WEEK('\ue16a'),
        GMDI_NFC('\ue1bb'),
        GMDI_NO_ENCRYPTION('\ue641'),
        GMDI_NO_SIM('\ue0cc'),
        GMDI_NOT_INTERESTED('\ue033'),
        GMDI_NOTE('\ue06f'),
        GMDI_NOTE_ADD('\ue89c'),
        GMDI_NOTIFICATIONS('\ue7f4'),
        GMDI_NOTIFICATIONS_ACTIVE('\ue7f7'),
        GMDI_NOTIFICATIONS_NONE('\ue7f5'),
        GMDI_NOTIFICATIONS_OFF('\ue7f6'),
        GMDI_NOTIFICATIONS_PAUSED('\ue7f8'),
        GMDI_OFFLINE_PIN('\ue90a'),
        GMDI_ONDEMAND_VIDEO('\ue63a'),
        GMDI_OPACITY('\ue91c'),
        GMDI_OPEN_IN_BROWSER('\ue89d'),
        GMDI_OPEN_IN_NEW('\ue89e'),
        GMDI_OPEN_WITH('\ue89f'),
        GMDI_PAGES('\ue7f9'),
        GMDI_PAGEVIEW('\ue8a0'),
        GMDI_PALETTE('\ue40a'),
        GMDI_PAN_TOOL('\ue925'),
        GMDI_PANORAMA('\ue40b'),
        GMDI_PANORAMA_FISH_EYE('\ue40c'),
        GMDI_PANORAMA_HORIZONTAL('\ue40d'),
        GMDI_PANORAMA_VERTICAL('\ue40e'),
        GMDI_PANORAMA_WIDE_ANGLE('\ue40f'),
        GMDI_PARTY_MODE('\ue7fa'),
        GMDI_PAUSE('\ue034'),
        GMDI_PAUSE_CIRCLE_FILLED('\ue035'),
        GMDI_PAUSE_CIRCLE_OUTLINE('\ue036'),
        GMDI_PAYMENT('\ue8a1'),
        GMDI_PEOPLE('\ue7fb'),
        GMDI_PEOPLE_OUTLINE('\ue7fc'),
        GMDI_PERM_CAMERA_MIC('\ue8a2'),
        GMDI_PERM_CONTACT_CALENDAR('\ue8a3'),
        GMDI_PERM_DATA_SETTING('\ue8a4'),
        GMDI_PERM_DEVICE_INFORMATION('\ue8a5'),
        GMDI_PERM_IDENTITY('\ue8a6'),
        GMDI_PERM_MEDIA('\ue8a7'),
        GMDI_PERM_PHONE_MSG('\ue8a8'),
        GMDI_PERM_SCAN_WIFI('\ue8a9'),
        GMDI_PERSON('\ue7fd'),
        GMDI_PERSON_ADD('\ue7fe'),
        GMDI_PERSON_OUTLINE('\ue7ff'),
        GMDI_PERSON_PIN('\ue55a'),
        GMDI_PERSON_PIN_CIRCLE('\ue56a'),
        GMDI_PERSONAL_VIDEO('\ue63b'),
        GMDI_PETS('\ue91d'),
        GMDI_PHONE('\ue0cd'),
        GMDI_PHONE_BLUETOOTH_SPEAKER('\ue61b'),
        GMDI_PHONE_FORWARDED('\ue61c'),
        GMDI_PHONE_IN_TALK('\ue61d'),
        GMDI_PHONE_IPHONE('\ue325'),
        GMDI_PHONE_LOCKED('\ue61e'),
        GMDI_PHONE_MISSED('\ue61f'),
        GMDI_PHONE_PAUSED('\ue620'),
        GMDI_PHONELINK('\ue326'),
        GMDI_PHONELINK_ERASE('\ue0db'),
        GMDI_PHONELINK_LOCK('\ue0dc'),
        GMDI_PHONELINK_OFF('\ue327'),
        GMDI_PHONELINK_RING('\ue0dd'),
        GMDI_PHONELINK_SETUP('\ue0de'),
        GMDI_PHOTO('\ue410'),
        GMDI_PHOTO_ALBUM('\ue411'),
        GMDI_PHOTO_CAMERA('\ue412'),
        GMDI_PHOTO_FILTER('\ue43b'),
        GMDI_PHOTO_LIBRARY('\ue413'),
        GMDI_PHOTO_SIZE_SELECT_ACTUAL('\ue432'),
        GMDI_PHOTO_SIZE_SELECT_LARGE('\ue433'),
        GMDI_PHOTO_SIZE_SELECT_SMALL('\ue434'),
        GMDI_PICTURE_AS_PDF('\ue415'),
        GMDI_PICTURE_IN_PICTURE('\ue8aa'),
        GMDI_PICTURE_IN_PICTURE_ALT('\ue911'),
        GMDI_PIE_CHART('\ue6c4'),
        GMDI_PIE_CHART_OUTLINED('\ue6c5'),
        GMDI_PIN_DROP('\ue55e'),
        GMDI_PLACE('\ue55f'),
        GMDI_PLAY_ARROW('\ue037'),
        GMDI_PLAY_CIRCLE_FILLED('\ue038'),
        GMDI_PLAY_CIRCLE_OUTLINE('\ue039'),
        GMDI_PLAY_FOR_WORK('\ue906'),
        GMDI_PLAYLIST_ADD('\ue03b'),
        GMDI_PLAYLIST_ADD_CHECK('\ue065'),
        GMDI_PLAYLIST_PLAY('\ue05f'),
        GMDI_PLUS_ONE('\ue800'),
        GMDI_POLL('\ue801'),
        GMDI_POLYMER('\ue8ab'),
        GMDI_POOL('\ueb48'),
        GMDI_PORTABLE_WIFI_OFF('\ue0ce'),
        GMDI_PORTRAIT('\ue416'),
        GMDI_POWER('\ue63c'),
        GMDI_POWER_INPUT('\ue336'),
        GMDI_POWER_SETTINGS_NEW('\ue8ac'),
        GMDI_PREGNANT_WOMAN('\ue91e'),
        GMDI_PRESENTI_TO_ALL('\ue0df'),
        GMDI_PRINT('\ue8ad'),
        GMDI_PRIORITY_HIGH('\ue645'),
        GMDI_PUBLIC('\ue80b'),
        GMDI_PUBLISH('\ue255'),
        GMDI_QUERY_BUILDER('\ue8ae'),
        GMDI_QUESTION_ANSWER('\ue8af'),
        GMDI_QUEUE('\ue03c'),
        GMDI_QUEUE_MUSIC('\ue03d'),
        GMDI_QUEUE_PLAY_NEXT('\ue066'),
        GMDI_RADIO('\ue03e'),
        GMDI_RADIO_BUTTON_CHECKED('\ue837'),
        GMDI_RADIO_BUTTON_UNCHECKED('\ue836'),
        GMDI_RATE_REVIEW('\ue560'),
        GMDI_RECEIPT('\ue8b0'),
        GMDI_RECENTI_ACTORS('\ue03f'),
        GMDI_RECORD_VOICE_OVER('\ue91f'),
        GMDI_REDEEM('\ue8b1'),
        GMDI_REDO('\ue15a'),
        GMDI_REFRESH('\ue5d5'),
        GMDI_REMOVE('\ue15b'),
        GMDI_REMOVE_CIRCLE('\ue15c'),
        GMDI_REMOVE_CIRCLE_OUTLINE('\ue15d'),
        GMDI_REMOVE_FROM_QUEUE('\ue067'),
        GMDI_REMOVE_RED_EYE('\ue417'),
        GMDI_REMOVE_SHOPPING_CART('\ue928'),
        GMDI_REORDER('\ue8fe'),
        GMDI_REPEAT('\ue040'),
        GMDI_REPEAT_ONE('\ue041'),
        GMDI_REPLAY('\ue042'),
        GMDI_REPLAY_10('\ue059'),
        GMDI_REPLAY_30('\ue05a'),
        GMDI_REPLAY_5('\ue05b'),
        GMDI_REPLY('\ue15e'),
        GMDI_REPLY_ALL('\ue15f'),
        GMDI_REPORT('\ue160'),
        GMDI_REPORT_PROBLEM('\ue8b2'),
        GMDI_RESTAURANT('\ue56c'),
        GMDI_RESTAURANT_MENU('\ue561'),
        GMDI_RESTORE('\ue8b3'),
        GMDI_RESTORE_PAGE('\ue929'),
        GMDI_RING_VOLUME('\ue0d1'),
        GMDI_ROOM('\ue8b4'),
        GMDI_ROOM_SERVICE('\ueb49'),
        GMDI_ROTATE_90_DEGREES_CCW('\ue418'),
        GMDI_ROTATE_LEFT('\ue419'),
        GMDI_ROTATE_RIGHT('\ue41a'),
        GMDI_ROUNDED_CORNER('\ue920'),
        GMDI_ROUTER('\ue328'),
        GMDI_ROWING('\ue921'),
        GMDI_RSS_FEED('\ue0e5'),
        GMDI_RV_HOOKUP('\ue642'),
        GMDI_SATELLITE('\ue562'),
        GMDI_SAVE('\ue161'),
        GMDI_SCANNER('\ue329'),
        GMDI_SCHEDULE('\ue8b5'),
        GMDI_SCHOOL('\ue80c'),
        GMDI_SCREEN_LOCK_LANDSCAPE('\ue1be'),
        GMDI_SCREEN_LOCK_PORTRAIT('\ue1bf'),
        GMDI_SCREEN_LOCK_ROTATION('\ue1c0'),
        GMDI_SCREEN_ROTATION('\ue1c1'),
        GMDI_SCREEN_SHARE('\ue0e2'),
        GMDI_SD_CARD('\ue623'),
        GMDI_SD_STORAGE('\ue1c2'),
        GMDI_SEARCH('\ue8b6'),
        GMDI_SECURITY('\ue32a'),
        GMDI_SELECT_ALL('\ue162'),
        GMDI_SEND('\ue163'),
        GMDI_SENTIMENTI_DISSATISFIED('\ue811'),
        GMDI_SENTIMENTI_NEUTRAL('\ue812'),
        GMDI_SENTIMENTI_SATISFIED('\ue813'),
        GMDI_SENTIMENTI_VERY_DISSATISFIED('\ue814'),
        GMDI_SENTIMENTI_VERY_SATISFIED('\ue815'),
        GMDI_SETTINGS('\ue8b8'),
        GMDI_SETTINGS_APPLICATIONS('\ue8b9'),
        GMDI_SETTINGS_BACKUP_RESTORE('\ue8ba'),
        GMDI_SETTINGS_BLUETOOTH('\ue8bb'),
        GMDI_SETTINGS_BRIGHTNESS('\ue8bd'),
        GMDI_SETTINGS_CELL('\ue8bc'),
        GMDI_SETTINGS_ETHERNET('\ue8be'),
        GMDI_SETTINGS_INPUT_ANTENNA('\ue8bf'),
        GMDI_SETTINGS_INPUT_COMPONENT('\ue8c0'),
        GMDI_SETTINGS_INPUT_COMPOSITE('\ue8c1'),
        GMDI_SETTINGS_INPUT_HDMI('\ue8c2'),
        GMDI_SETTINGS_INPUT_SVIDEO('\ue8c3'),
        GMDI_SETTINGS_OVERSCAN('\ue8c4'),
        GMDI_SETTINGS_PHONE('\ue8c5'),
        GMDI_SETTINGS_POWER('\ue8c6'),
        GMDI_SETTINGS_REMOTE('\ue8c7'),
        GMDI_SETTINGS_SYSTEM_DAYDREAM('\ue1c3'),
        GMDI_SETTINGS_VOICE('\ue8c8'),
        GMDI_SHARE('\ue80d'),
        GMDI_SHOP('\ue8c9'),
        GMDI_SHOP_TWO('\ue8ca'),
        GMDI_SHOPPING_BASKET('\ue8cb'),
        GMDI_SHOPPING_CART('\ue8cc'),
        GMDI_SHORT_TEXT('\ue261'),
        GMDI_SHOW_CHART('\ue6e1'),
        GMDI_SHUFFLE('\ue043'),
        GMDI_SIGNAL_CELLULAR_4_BAR('\ue1c8'),
        GMDI_SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR('\ue1cd'),
        GMDI_SIGNAL_CELLULAR_NO_SIM('\ue1ce'),
        GMDI_SIGNAL_CELLULAR_NULL('\ue1cf'),
        GMDI_SIGNAL_CELLULAR_OFF('\ue1d0'),
        GMDI_SIGNAL_WIFI_4_BAR('\ue1d8'),
        GMDI_SIGNAL_WIFI_4_BAR_LOCK('\ue1d9'),
        GMDI_SIGNAL_WIFI_OFF('\ue1da'),
        GMDI_SIM_CARD('\ue32b'),
        GMDI_SIM_CARD_ALERT('\ue624'),
        GMDI_SKIP_NEXT('\ue044'),
        GMDI_SKIP_PREVIOUS('\ue045'),
        GMDI_SLIDESHOW('\ue41b'),
        GMDI_SLOW_MOTION_VIDEO('\ue068'),
        GMDI_SMARTPHONE('\ue32c'),
        GMDI_SMOKE_FREE('\ueb4a'),
        GMDI_SMOKING_ROOMS('\ueb4b'),
        GMDI_SMS('\ue625'),
        GMDI_SMS_FAILED('\ue626'),
        GMDI_SNOOZE('\ue046'),
        GMDI_SORT('\ue164'),
        GMDI_SORT_BY_ALPHA('\ue053'),
        GMDI_SPA('\ueb4c'),
        GMDI_SPACE_BAR('\ue256'),
        GMDI_SPEAKER('\ue32d'),
        GMDI_SPEAKER_GROUP('\ue32e'),
        GMDI_SPEAKER_NOTES('\ue8cd'),
        GMDI_SPEAKER_NOTES_OFF('\ue92a'),
        GMDI_SPEAKER_PHONE('\ue0d2'),
        GMDI_SPELLCHECK('\ue8ce'),
        GMDI_STAR('\ue838'),
        GMDI_STAR_BORDER('\ue83a'),
        GMDI_STAR_HALF('\ue839'),
        GMDI_STARS('\ue8d0'),
        GMDI_STAY_CURRENTI_LANDSCAPE('\ue0d3'),
        GMDI_STAY_CURRENTI_PORTRAIT('\ue0d4'),
        GMDI_STAY_PRIMARY_LANDSCAPE('\ue0d5'),
        GMDI_STAY_PRIMARY_PORTRAIT('\ue0d6'),
        GMDI_STOP('\ue047'),
        GMDI_STOP_SCREEN_SHARE('\ue0e3'),
        GMDI_STORAGE('\ue1db'),
        GMDI_STORE('\ue8d1'),
        GMDI_STORE_MALL_DIRECTORY('\ue563'),
        GMDI_STRAIGHTEN('\ue41c'),
        GMDI_STREETVIEW('\ue56e'),
        GMDI_STRIKETHROUGH_S('\ue257'),
        GMDI_STYLE('\ue41d'),
        GMDI_SUBDIRECTORY_ARROW_LEFT('\ue5d9'),
        GMDI_SUBDIRECTORY_ARROW_RIGHT('\ue5da'),
        GMDI_SUBJECT('\ue8d2'),
        GMDI_SUBSCRIPTIONS('\ue064'),
        GMDI_SUBTITLES('\ue048'),
        GMDI_SUBWAY('\ue56f'),
        GMDI_SUPERVISOR_ACCOUNT('\ue8d3'),
        GMDI_SURROUND_SOUND('\ue049'),
        GMDI_SWAP_CALLS('\ue0d7'),
        GMDI_SWAP_HORIZ('\ue8d4'),
        GMDI_SWAP_VERT('\ue8d5'),
        GMDI_SWAP_VERTICAL_CIRCLE('\ue8d6'),
        GMDI_SWITCH_CAMERA('\ue41e'),
        GMDI_SWITCH_VIDEO('\ue41f'),
        GMDI_SYNC('\ue627'),
        GMDI_SYNC_DISABLED('\ue628'),
        GMDI_SYNC_PROBLEM('\ue629'),
        GMDI_SYSTEM_UPDATE('\ue62a'),
        GMDI_SYSTEM_UPDATE_ALT('\ue8d7'),
        GMDI_TAB('\ue8d8'),
        GMDI_TAB_UNSELECTED('\ue8d9'),
        GMDI_TABLET('\ue32f'),
        GMDI_TABLET_MAC('\ue331'),
        GMDI_TAG_FACES('\ue420'),
        GMDI_TAP_AND_PLAY('\ue62b'),
        GMDI_TERRAIN('\ue564'),
        GMDI_TEXT_FIELDS('\ue262'),
        GMDI_TEXT_FORMAT('\ue165'),
        GMDI_TEXTSMS('\ue0d8'),
        GMDI_TEXTURE('\ue421'),
        GMDI_THEATERS('\ue8da'),
        GMDI_THUMB_DOWN('\ue8db'),
        GMDI_THUMB_UP('\ue8dc'),
        GMDI_THUMBS_UP_DOWN('\ue8dd'),
        GMDI_TIME_TO_LEAVE('\ue62c'),
        GMDI_TIMELAPSE('\ue422'),
        GMDI_TIMELINE('\ue922'),
        GMDI_TIMER('\ue425'),
        GMDI_TIMER_10('\ue423'),
        GMDI_TIMER_3('\ue424'),
        GMDI_TIMER_OFF('\ue426'),
        GMDI_TITLE('\ue264'),
        GMDI_TOC('\ue8de'),
        GMDI_TODAY('\ue8df'),
        GMDI_TOLL('\ue8e0'),
        GMDI_TONALITY('\ue427'),
        GMDI_TOUCH_APP('\ue913'),
        GMDI_TOYS('\ue332'),
        GMDI_TRACK_CHANGES('\ue8e1'),
        GMDI_TRAFFIC('\ue565'),
        GMDI_TRAIN('\ue570'),
        GMDI_TRAM('\ue571'),
        GMDI_TRANSFER_WITHIN_A_STATION('\ue572'),
        GMDI_TRANSFORM('\ue428'),
        GMDI_TRANSLATE('\ue8e2'),
        GMDI_TRENDING_DOWN('\ue8e3'),
        GMDI_TRENDING_FLAT('\ue8e4'),
        GMDI_TRENDING_UP('\ue8e5'),
        GMDI_TUNE('\ue429'),
        GMDI_TURNED_IN('\ue8e6'),
        GMDI_TURNED_IN_NOT('\ue8e7'),
        GMDI_TV('\ue333'),
        GMDI_UNARCHIVE('\ue169'),
        GMDI_UNDO('\ue166'),
        GMDI_UNFOLD_LESS('\ue5d6'),
        GMDI_UNFOLD_MORE('\ue5d7'),
        GMDI_UPDATE('\ue923'),
        GMDI_USB('\ue1e0'),
        GMDI_VERIFIED_USER('\ue8e8'),
        GMDI_VERTICAL_ALIGN_BOTTOM('\ue258'),
        GMDI_VERTICAL_ALIGN_CENTER('\ue259'),
        GMDI_VERTICAL_ALIGN_TOP('\ue25a'),
        GMDI_VIBRATION('\ue62d'),
        GMDI_VIDEO_CALL('\ue070'),
        GMDI_VIDEO_LABEL('\ue071'),
        GMDI_VIDEO_LIBRARY('\ue04a'),
        GMDI_VIDEOCAM('\ue04b'),
        GMDI_VIDEOCAM_OFF('\ue04c'),
        GMDI_VIDEOGAME_ASSET('\ue338'),
        GMDI_VIEW_AGENDA('\ue8e9'),
        GMDI_VIEW_ARRAY('\ue8ea'),
        GMDI_VIEW_CAROUSEL('\ue8eb'),
        GMDI_VIEW_COLUMN('\ue8ec'),
        GMDI_VIEW_COMFY('\ue42a'),
        GMDI_VIEW_COMPACT('\ue42b'),
        GMDI_VIEW_DAY('\ue8ed'),
        GMDI_VIEW_HEADLINE('\ue8ee'),
        GMDI_VIEW_LIST('\ue8ef'),
        GMDI_VIEW_MODULE('\ue8f0'),
        GMDI_VIEW_QUILT('\ue8f1'),
        GMDI_VIEW_STREAM('\ue8f2'),
        GMDI_VIEW_WEEK('\ue8f3'),
        GMDI_VIGNETTE('\ue435'),
        GMDI_VISIBILITY('\ue8f4'),
        GMDI_VISIBILITY_OFF('\ue8f5'),
        GMDI_VOICE_CHAT('\ue62e'),
        GMDI_VOICEMAIL('\ue0d9'),
        GMDI_VOLUME_DOWN('\ue04d'),
        GMDI_VOLUME_MUTE('\ue04e'),
        GMDI_VOLUME_OFF('\ue04f'),
        GMDI_VOLUME_UP('\ue050'),
        GMDI_VPN_KEY('\ue0da'),
        GMDI_VPN_LOCK('\ue62f'),
        GMDI_WALLPAPER('\ue1bc'),
        GMDI_WARNING('\ue002'),
        GMDI_WATCH('\ue334'),
        GMDI_WATCH_LATER('\ue924'),
        GMDI_WB_AUTO('\ue42c'),
        GMDI_WB_CLOUDY('\ue42d'),
        GMDI_WB_INCANDESCENT('\ue42e'),
        GMDI_WB_IRIDESCENT('\ue436'),
        GMDI_WB_SUNNY('\ue430'),
        GMDI_WC('\ue63d'),
        GMDI_WEB('\ue051'),
        GMDI_WEB_ASSET('\ue069'),
        GMDI_WEEKEND('\ue16b'),
        GMDI_WHATSHOT('\ue80e'),
        GMDI_WIDGETS('\ue1bd'),
        GMDI_WIFI('\ue63e'),
        GMDI_WIFI_LOCK('\ue1e1'),
        GMDI_WIFI_TETHERING('\ue1e2'),
        GMDI_WORK('\ue8f9'),
        GMDI_WRAP_TEXT('\ue25b'),
        GMDI_YOUTUBE_SEARCHED_FOR('\ue8fa'),
        GMDI_ZOOM_IN('\ue8ff'),
        GMDI_ZOOM_OUT('\ue900'),
        GMDI_ZOOM_OUT_MAP('\ue56b');

        char googleMaterialCharacter;

        Icon(char character) {
            this.googleMaterialCharacter = character;
        }

        public String getFormattedName() {
            return "{" + name() + "}";
        }

        public char getCharacter() {
            return googleMaterialCharacter;
        }

        public String getName() {
            return name();
        }

        // remember the typeface so we can use it later
        private static ITypeface googleMaterialTypeface;

        @Override
        public ITypeface getTypeface() {
            if (googleMaterialTypeface == null) {
                setTypeface(new GoogleMaterial());
            }
            return googleMaterialTypeface;
        }

        private static void setTypeface(GoogleMaterial googleMaterialTypeface) {
            Icon.googleMaterialTypeface = googleMaterialTypeface;
        }
    }
}
