package com.rilixtech.material_design_iconic_typeface;

import ohos.agp.text.Font;
import ohos.app.AbilityContext;
import com.rilixtech.materialfancybutton.typeface.IIcon;
import com.rilixtech.materialfancybutton.typeface.ITypeface;
import com.rilixtech.materialfancybutton.utils.FontUtil;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;

/**
 * ITypeface implementation using the MaterialDesignIconic font. It hosts a variety of icons that can be used by
 * the MaterialFancyButton Components.
 */
public class MaterialDesignIconic implements ITypeface {
    private static final String TTF_FILE = "material-design-iconic-font-v2.2.0.ttf";
    private static final String MATERIAL_DESIGN_ICONIC_PREFIX = "MDII";
    public static final String MATERIAL_DESIGN_ICONIC_NAME = "Material Design Iconic";
    public static final String MATERIAL_DESIGN_ICONIC_VERSION = "2" + ".2.0";
    public static final String MATERIAL_DESIGN_ICONIC_AUTHOR = "Google. TTF created by Sergey Kupletsky";
    public static final String MATERIAL_DESIGN_ICONIC_URL = "http://zavoloklom.github.io/material-design-iconic-font/";
    public static final String MATERIAL_DESIGN_ICONIC_DESC = "Material Design Iconic Font is a full suite of material"
            + " design icons (created and maintained by Google) for easy scalable vector graphics on websites.";
    public static final String MATERIAL_DESIGN_ICONIC_LICENSE = "SIL OFL 1.1";
    public static final String MATERIAL_DESIGN_ICONIC_LICENSE_URL = "http://scripts.sil.org/OFL";

    private static Font materialDesignIconicTypeface = null;

    private static HashMap<String, Character> materialDesignIconicCharMap;

    /**
     * MaterialDesignIconic IIcon object corresponding to this typeface for the given key.
     *
     * @param key Key for which MaterialDesignIconic IIcon is to be retrieved.
     */
    @Override public IIcon getIcon(String key) {
        return Icon.valueOf(key);
    }

    /**
     * Get all the MaterialDesignIconic icon characters in a HashMap.
     *
     * @return HashMap of all MaterialDesignIconic icon character names mapped to their character values.
     */
    @Override public HashMap<String, Character> getCharacters() {
        if (materialDesignIconicCharMap == null) {
            HashMap<String, Character> characterHashMap = new HashMap<>();
            for (Icon v : Icon.values()) {
                characterHashMap.put(v.name(), v.materialDesignIconicCharacter);
            }
            setChars(characterHashMap);
        }

        return materialDesignIconicCharMap;
    }

    /**
     * Set the MaterialDesignIconic Characters into a HashMap.
     */
    private static void setChars(HashMap<String, Character> characterHashMap) {
        materialDesignIconicCharMap = characterHashMap;
    }

    /**
     * Return the MaterialDesignIconic Mapping Prefix.
     *
     * @return MaterialDesignIconic Mapping Prefix, used by all MaterialDesignIconic icons.
     */
    @Override public String getMappingPrefix() {
        return MATERIAL_DESIGN_ICONIC_PREFIX;
    }

    @Override public String getFontName() {
        return MATERIAL_DESIGN_ICONIC_NAME;
    }

    @Override public String getVersion() {
        return MATERIAL_DESIGN_ICONIC_VERSION;
    }

    @Override public int getIconCount() {
        return materialDesignIconicCharMap.size();
    }

    @Override public Collection<String> getIcons() {
        Collection<String> materialDesignIconicKeyList = new LinkedList<>();

        for (Icon value : Icon.values()) {
            materialDesignIconicKeyList.add(value.name());
        }

        return materialDesignIconicKeyList;
    }

    @Override public String getAuthor() {
        return MATERIAL_DESIGN_ICONIC_AUTHOR;
    }

    @Override public String getUrl() {
        return MATERIAL_DESIGN_ICONIC_URL;
    }

    @Override public String getDescription() {
        return MATERIAL_DESIGN_ICONIC_DESC;
    }

    @Override public String getLicense() {
        return MATERIAL_DESIGN_ICONIC_LICENSE;
    }

    @Override public String getLicenseUrl() {
        return MATERIAL_DESIGN_ICONIC_LICENSE_URL;
    }

    @Override
    public Font getTypeface(AbilityContext context) {
        if (materialDesignIconicTypeface == null) {
            try {
                cacheTypeface(FontUtil.getFontFromRawFile(context, TTF_FILE));
            } catch (IllegalStateException e) {
                throw new IllegalStateException(e);
            }
        }
        return materialDesignIconicTypeface;
    }

    private static void cacheTypeface(Font font) {
        materialDesignIconicTypeface = font;
    }

    /**
     * Enumerates all the supported Custom Icon Unicode characters by MaterialDesignIconic ITypeface.
     */
    public enum Icon implements IIcon {
        MDII_3D_ROTATION('\uf101'),
        MDII_AIRPLANE_OFF('\uf102'),
        MDII_AIRPLANE('\uf103'),
        MDII_ALBUM('\uf104'),
        MDII_ARCHIVE('\uf105'),
        MDII_ASSIGNMENTI_ACCOUNT('\uf106'),
        MDII_ASSIGNMENTI_ALERT('\uf107'),
        MDII_ASSIGNMENTI_CHECK('\uf108'),
        MDII_ASSIGNMENTI_O('\uf109'),
        MDII_ASSIGNMENTI_RETURN('\uf10a'),
        MDII_ASSIGNMENTI_RETURNED('\uf10b'),
        MDII_ASSIGNMENT('\uf10c'),
        MDII_ATTACHMENTI_ALT('\uf10d'),
        MDII_ATTACHMENT('\uf10e'),
        MDII_AUDIO('\uf10f'),
        MDII_BADGE_CHECK('\uf110'),
        MDII_BALANCE_WALLET('\uf111'),
        MDII_BALANCE('\uf112'),
        MDII_BATTERY_ALERT('\uf113'),
        MDII_BATTERY_FLASH('\uf114'),
        MDII_BATTERY_UNKNOWN('\uf115'),
        MDII_BATTERY('\uf116'),
        MDII_BIKE('\uf117'),
        MDII_BLOCK_ALT('\uf118'),
        MDII_BLOCK('\uf119'),
        MDII_BOAT('\uf11a'),
        MDII_BOOK_IMAGE('\uf11b'),
        MDII_BOOK('\uf11c'),
        MDII_BOOKMARK_OUTLINE('\uf11d'),
        MDII_BOOKMARK('\uf11e'),
        MDII_BRUSH('\uf11f'),
        MDII_BUG('\uf120'),
        MDII_BUS('\uf121'),
        MDII_CAKE('\uf122'),
        MDII_CAR_TAXI('\uf123'),
        MDII_CAR_WASH('\uf124'),
        MDII_CAR('\uf125'),
        MDII_CARD_GIFTCARD('\uf126'),
        MDII_CARD_MEMBERSHIP('\uf127'),
        MDII_CARD_TRAVEL('\uf128'),
        MDII_CARD('\uf129'),
        MDII_CASE_CHECK('\uf12a'),
        MDII_CASE_DOWNLOAD('\uf12b'),
        MDII_CASE_PLAY('\uf12c'),
        MDII_CASE('\uf12d'),
        MDII_CAST_CONNECTED('\uf12e'),
        MDII_CAST('\uf12f'),
        MDII_CHART_DONUT('\uf130'),
        MDII_CHART('\uf131'),
        MDII_CITY_ALT('\uf132'),
        MDII_CITY('\uf133'),
        MDII_CLOSE_CIRCLE_O('\uf134'),
        MDII_CLOSE_CIRCLE('\uf135'),
        MDII_CLOSE('\uf136'),
        MDII_COCKTAIL('\uf137'),
        MDII_CODE_SETTING('\uf138'),
        MDII_CODE_SMARTPHONE('\uf139'),
        MDII_CODE('\uf13a'),
        MDII_COFFEE('\uf13b'),
        MDII_COLLECTION_BOOKMARK('\uf13c'),
        MDII_COLLECTION_CASE_PLAY('\uf13d'),
        MDII_COLLECTION_FOLDER_IMAGE('\uf13e'),
        MDII_COLLECTION_IMAGE_O('\uf13f'),
        MDII_COLLECTION_IMAGE('\uf140'),
        MDII_COLLECTION_ITEM_1('\uf141'),
        MDII_COLLECTION_ITEM_2('\uf142'),
        MDII_COLLECTION_ITEM_3('\uf143'),
        MDII_COLLECTION_ITEM_4('\uf144'),
        MDII_COLLECTION_ITEM_5('\uf145'),
        MDII_COLLECTION_ITEM_6('\uf146'),
        MDII_COLLECTION_ITEM_7('\uf147'),
        MDII_COLLECTION_ITEM_8('\uf148'),
        MDII_COLLECTION_ITEM_9_PLUS('\uf149'),
        MDII_COLLECTION_ITEM_9('\uf14a'),
        MDII_COLLECTION_ITEM('\uf14b'),
        MDII_COLLECTION_MUSIC('\uf14c'),
        MDII_COLLECTION_PDF('\uf14d'),
        MDII_COLLECTION_PLUS('\uf14e'),
        MDII_COLLECTION_SPEAKER('\uf14f'),
        MDII_COLLECTION_TEXT('\uf150'),
        MDII_COLLECTION_VIDEO('\uf151'),
        MDII_COMPASS('\uf152'),
        MDII_CUTLERY('\uf153'),
        MDII_DELETE('\uf154'),
        MDII_DIALPAD('\uf155'),
        MDII_DNS('\uf156'),
        MDII_DRINK('\uf157'),
        MDII_EDIT('\uf158'),
        MDII_EMAIL_OPEN('\uf159'),
        MDII_EMAIL('\uf15a'),
        MDII_EYE_OFF('\uf15b'),
        MDII_EYE('\uf15c'),
        MDII_EYEDROPPER('\uf15d'),
        MDII_FAVORITE_OUTLINE('\uf15e'),
        MDII_FAVORITE('\uf15f'),
        MDII_FILTER_LIST('\uf160'),
        MDII_FIRE('\uf161'),
        MDII_FLAG('\uf162'),
        MDII_FLARE('\uf163'),
        MDII_FLASH_AUTO('\uf164'),
        MDII_FLASH_OFF('\uf165'),
        MDII_FLASH('\uf166'),
        MDII_FLIP('\uf167'),
        MDII_FLOWER_ALT('\uf168'),
        MDII_FLOWER('\uf169'),
        MDII_FONT('\uf16a'),
        MDII_FULLSCREEN_ALT('\uf16b'),
        MDII_FULLSCREEN_EXIT('\uf16c'),
        MDII_FULLSCREEN('\uf16d'),
        MDII_FUNCTIONS('\uf16e'),
        MDII_GAS_STATION('\uf16f'),
        MDII_GESTURE('\uf170'),
        MDII_GLOBE_ALT('\uf171'),
        MDII_GLOBE_LOCK('\uf172'),
        MDII_GLOBE('\uf173'),
        MDII_GRADUATION_CAP('\uf174'),
        MDII_HOME('\uf175'),
        MDII_HOSPITAL_ALT('\uf176'),
        MDII_HOSPITAL('\uf177'),
        MDII_HOTEL('\uf178'),
        MDII_HOURGLASS_ALT('\uf179'),
        MDII_HOURGLASS_OUTLINE('\uf17a'),
        MDII_HOURGLASS('\uf17b'),
        MDII_HTTP('\uf17c'),
        MDII_IMAGE_ALT('\uf17d'),
        MDII_IMAGE_O('\uf17e'),
        MDII_IMAGE('\uf17f'),
        MDII_INBOX('\uf180'),
        MDII_INVERT_COLORS_OFF('\uf181'),
        MDII_INVERT_COLORS('\uf182'),
        MDII_KEY('\uf183'),
        MDII_LABEL_ALT_OUTLINE('\uf184'),
        MDII_LABEL_ALT('\uf185'),
        MDII_LABEL_HEART('\uf186'),
        MDII_LABEL('\uf187'),
        MDII_LABELS('\uf188'),
        MDII_LAMP('\uf189'),
        MDII_LANDSCAPE('\uf18a'),
        MDII_LAYERS_OFF('\uf18b'),
        MDII_LAYERS('\uf18c'),
        MDII_LIBRARY('\uf18d'),
        MDII_LINK('\uf18e'),
        MDII_LOCK_OPEN('\uf18f'),
        MDII_LOCK_OUTLINE('\uf190'),
        MDII_LOCK('\uf191'),
        MDII_MAIL_REPLY_ALL('\uf192'),
        MDII_MAIL_REPLY('\uf193'),
        MDII_MAIL_SEND('\uf194'),
        MDII_MALL('\uf195'),
        MDII_MAP('\uf196'),
        MDII_MENU('\uf197'),
        MDII_MONEY_BOX('\uf198'),
        MDII_MONEY_OFF('\uf199'),
        MDII_MONEY('\uf19a'),
        MDII_MORE_VERT('\uf19b'),
        MDII_MORE('\uf19c'),
        MDII_MOVIE_ALT('\uf19d'),
        MDII_MOVIE('\uf19e'),
        MDII_NATURE_PEOPLE('\uf19f'),
        MDII_NATURE('\uf1a0'),
        MDII_NAVIGATION('\uf1a1'),
        MDII_OPEN_IN_BROWSER('\uf1a2'),
        MDII_OPEN_IN_NEW('\uf1a3'),
        MDII_PALETTE('\uf1a4'),
        MDII_PARKING('\uf1a5'),
        MDII_PIN_ACCOUNT('\uf1a6'),
        MDII_PIN_ASSISTANT('\uf1a7'),
        MDII_PIN_DROP('\uf1a8'),
        MDII_PIN_HELP('\uf1a9'),
        MDII_PIN_OFF('\uf1aa'),
        MDII_PIN('\uf1ab'),
        MDII_PIZZA('\uf1ac'),
        MDII_PLASTER('\uf1ad'),
        MDII_POWER_SETTING('\uf1ae'),
        MDII_POWER('\uf1af'),
        MDII_PRINT('\uf1b0'),
        MDII_PUZZLE_PIECE('\uf1b1'),
        MDII_QUOTE('\uf1b2'),
        MDII_RAILWAY('\uf1b3'),
        MDII_RECEIPT('\uf1b4'),
        MDII_REFRESH_ALT('\uf1b5'),
        MDII_REFRESH_SYNC_ALERT('\uf1b6'),
        MDII_REFRESH_SYNC_OFF('\uf1b7'),
        MDII_REFRESH_SYNC('\uf1b8'),
        MDII_REFRESH('\uf1b9'),
        MDII_ROLLER('\uf1ba'),
        MDII_RULER('\uf1bb'),
        MDII_SCISSORS('\uf1bc'),
        MDII_SCREEN_ROTATION_LOCK('\uf1bd'),
        MDII_SCREEN_ROTATION('\uf1be'),
        MDII_SEARCH_FOR('\uf1bf'),
        MDII_SEARCH_IN_FILE('\uf1c0'),
        MDII_SEARCH_IN_PAGE('\uf1c1'),
        MDII_SEARCH_REPLACE('\uf1c2'),
        MDII_SEARCH('\uf1c3'),
        MDII_SEAT('\uf1c4'),
        MDII_SETTINGS_SQUARE('\uf1c5'),
        MDII_SETTINGS('\uf1c6'),
        MDII_SHIELD_CHECK('\uf1c7'),
        MDII_SHIELD_SECURITY('\uf1c8'),
        MDII_SHOPPING_BASKET('\uf1c9'),
        MDII_SHOPPING_CART_PLUS('\uf1ca'),
        MDII_SHOPPING_CART('\uf1cb'),
        MDII_SIGN_IN('\uf1cc'),
        MDII_SORT_AMOUNT_ASC('\uf1cd'),
        MDII_SORT_AMOUNT_DESC('\uf1ce'),
        MDII_SORT_ASC('\uf1cf'),
        MDII_SORT_DESC('\uf1d0'),
        MDII_SPELLCHECK('\uf1d1'),
        MDII_STORAGE('\uf1d2'),
        MDII_STORE_24('\uf1d3'),
        MDII_STORE('\uf1d4'),
        MDII_SUBWAY('\uf1d5'),
        MDII_SUN('\uf1d6'),
        MDII_TAB_UNSELECTED('\uf1d7'),
        MDII_TAB('\uf1d8'),
        MDII_TAG_CLOSE('\uf1d9'),
        MDII_TAG_MORE('\uf1da'),
        MDII_TAG('\uf1db'),
        MDII_THUMB_DOWN('\uf1dc'),
        MDII_THUMB_UP_DOWN('\uf1dd'),
        MDII_THUMB_UP('\uf1de'),
        MDII_TICKET_STAR('\uf1df'),
        MDII_TOLL('\uf1e0'),
        MDII_TOYS('\uf1e1'),
        MDII_TRAFFIC('\uf1e2'),
        MDII_TRANSLATE('\uf1e3'),
        MDII_TRIANGLE_DOWN('\uf1e4'),
        MDII_TRIANGLE_UP('\uf1e5'),
        MDII_TRUCK('\uf1e6'),
        MDII_TURNING_SIGN('\uf1e7'),
        MDII_WALLPAPER('\uf1e8'),
        MDII_WASHING_MACHINE('\uf1e9'),
        MDII_WINDOW_MAXIMIZE('\uf1ea'),
        MDII_WINDOW_MINIMIZE('\uf1eb'),
        MDII_WINDOW_RESTORE('\uf1ec'),
        MDII_WRENCH('\uf1ed'),
        MDII_ZOOM_IN('\uf1ee'),
        MDII_ZOOM_OUT('\uf1ef'),
        MDII_ALERT_CIRCLE_O('\uf1f0'),
        MDII_ALERT_CIRCLE('\uf1f1'),
        MDII_ALERT_OCTAGON('\uf1f2'),
        MDII_ALERT_POLYGON('\uf1f3'),
        MDII_ALERT_TRIANGLE('\uf1f4'),
        MDII_HELP_OUTLINE('\uf1f5'),
        MDII_HELP('\uf1f6'),
        MDII_INFO_OUTLINE('\uf1f7'),
        MDII_INFO('\uf1f8'),
        MDII_NOTIFICATIONS_ACTIVE('\uf1f9'),
        MDII_NOTIFICATIONS_ADD('\uf1fa'),
        MDII_NOTIFICATIONS_NONE('\uf1fb'),
        MDII_NOTIFICATIONS_OFF('\uf1fc'),
        MDII_NOTIFICATIONS_PAUSED('\uf1fd'),
        MDII_NOTIFICATIONS('\uf1fe'),
        MDII_ACCOUNT_ADD('\uf1ff'),
        MDII_ACCOUNT_BOX_MAIL('\uf200'),
        MDII_ACCOUNT_BOX_O('\uf201'),
        MDII_ACCOUNT_BOX_PHONE('\uf202'),
        MDII_ACCOUNT_BOX('\uf203'),
        MDII_ACCOUNT_CALENDAR('\uf204'),
        MDII_ACCOUNT_CIRCLE('\uf205'),
        MDII_ACCOUNT_O('\uf206'),
        MDII_ACCOUNT('\uf207'),
        MDII_ACCOUNTS_ADD('\uf208'),
        MDII_ACCOUNTS_ALT('\uf209'),
        MDII_ACCOUNTS_LIST_ALT('\uf20a'),
        MDII_ACCOUNTS_LIST('\uf20b'),
        MDII_ACCOUNTS_OUTLINE('\uf20c'),
        MDII_ACCOUNTS('\uf20d'),
        MDII_FACE('\uf20e'),
        MDII_FEMALE('\uf20f'),
        MDII_MALE_ALT('\uf210'),
        MDII_MALE_FEMALE('\uf211'),
        MDII_MALE('\uf212'),
        MDII_MOOD_BAD('\uf213'),
        MDII_MOOD('\uf214'),
        MDII_RUN('\uf215'),
        MDII_WALK('\uf216'),
        MDII_CLOUD_BOX('\uf217'),
        MDII_CLOUD_CIRCLE('\uf218'),
        MDII_CLOUD_DONE('\uf219'),
        MDII_CLOUD_DOWNLOAD('\uf21a'),
        MDII_CLOUD_OFF('\uf21b'),
        MDII_CLOUD_OUTLINE_ALT('\uf21c'),
        MDII_CLOUD_OUTLINE('\uf21d'),
        MDII_CLOUD_UPLOAD('\uf21e'),
        MDII_CLOUD('\uf21f'),
        MDII_DOWNLOAD('\uf220'),
        MDII_FILE_PLUS('\uf221'),
        MDII_FILE_TEXT('\uf222'),
        MDII_FILE('\uf223'),
        MDII_FOLDER_OUTLINE('\uf224'),
        MDII_FOLDER_PERSON('\uf225'),
        MDII_FOLDER_STAR_ALT('\uf226'),
        MDII_FOLDER_STAR('\uf227'),
        MDII_FOLDER('\uf228'),
        MDII_GIF('\uf229'),
        MDII_UPLOAD('\uf22a'),
        MDII_BORDER_ALL('\uf22b'),
        MDII_BORDER_BOTTOM('\uf22c'),
        MDII_BORDER_CLEAR('\uf22d'),
        MDII_BORDER_COLOR('\uf22e'),
        MDII_BORDER_HORIZONTAL('\uf22f'),
        MDII_BORDER_INNER('\uf230'),
        MDII_BORDER_LEFT('\uf231'),
        MDII_BORDER_OUTER('\uf232'),
        MDII_BORDER_RIGHT('\uf233'),
        MDII_BORDER_STYLE('\uf234'),
        MDII_BORDER_TOP('\uf235'),
        MDII_BORDER_VERTICAL('\uf236'),
        MDII_COPY('\uf237'),
        MDII_CROP('\uf238'),
        MDII_FORMAT_ALIGN_CENTER('\uf239'),
        MDII_FORMAT_ALIGN_JUSTIFY('\uf23a'),
        MDII_FORMAT_ALIGN_LEFT('\uf23b'),
        MDII_FORMAT_ALIGN_RIGHT('\uf23c'),
        MDII_FORMAT_BOLD('\uf23d'),
        MDII_FORMAT_CLEAR_ALL('\uf23e'),
        MDII_FORMAT_CLEAR('\uf23f'),
        MDII_FORMAT_COLOR_FILL('\uf240'),
        MDII_FORMAT_COLOR_RESET('\uf241'),
        MDII_FORMAT_COLOR_TEXT('\uf242'),
        MDII_FORMAT_INDENTI_DECREASE('\uf243'),
        MDII_FORMAT_INDENTI_INCREASE('\uf244'),
        MDII_FORMAT_ITALIC('\uf245'),
        MDII_FORMAT_LINE_SPACING('\uf246'),
        MDII_FORMAT_LIST_BULLETED('\uf247'),
        MDII_FORMAT_LIST_NUMBERED('\uf248'),
        MDII_FORMAT_LTR('\uf249'),
        MDII_FORMAT_RTL('\uf24a'),
        MDII_FORMAT_SIZE('\uf24b'),
        MDII_FORMAT_STRIKETHROUGH_S('\uf24c'),
        MDII_FORMAT_STRIKETHROUGH('\uf24d'),
        MDII_FORMAT_SUBJECT('\uf24e'),
        MDII_FORMAT_UNDERLINED('\uf24f'),
        MDII_FORMAT_VALIGN_BOTTOM('\uf250'),
        MDII_FORMAT_VALIGN_CENTER('\uf251'),
        MDII_FORMAT_VALIGN_TOP('\uf252'),
        MDII_REDO('\uf253'),
        MDII_SELECT_ALL('\uf254'),
        MDII_SPACE_BAR('\uf255'),
        MDII_TEXT_FORMAT('\uf256'),
        MDII_TRANSFORM('\uf257'),
        MDII_UNDO('\uf258'),
        MDII_WRAP_TEXT('\uf259'),
        MDII_COMMENTI_ALERT('\uf25a'),
        MDII_COMMENTI_ALT_TEXT('\uf25b'),
        MDII_COMMENTI_ALT('\uf25c'),
        MDII_COMMENTI_EDIT('\uf25d'),
        MDII_COMMENTI_IMAGE('\uf25e'),
        MDII_COMMENTI_LIST('\uf25f'),
        MDII_COMMENTI_MORE('\uf260'),
        MDII_COMMENTI_OUTLINE('\uf261'),
        MDII_COMMENTI_TEXT_ALT('\uf262'),
        MDII_COMMENTI_TEXT('\uf263'),
        MDII_COMMENTI_VIDEO('\uf264'),
        MDII_COMMENT('\uf265'),
        MDII_COMMENTS('\uf266'),
        MDII_CHECK_ALL('\uf267'),
        MDII_CHECK_CIRCLE_U('\uf268'),
        MDII_CHECK_CIRCLE('\uf269'),
        MDII_CHECK_SQUARE('\uf26a'),
        MDII_CHECK('\uf26b'),
        MDII_CIRCLE_O('\uf26c'),
        MDII_CIRCLE('\uf26d'),
        MDII_DOT_CIRCLE_ALT('\uf26e'),
        MDII_DOT_CIRCLE('\uf26f'),
        MDII_MINUS_CIRCLE_OUTLINE('\uf270'),
        MDII_MINUS_CIRCLE('\uf271'),
        MDII_MINUS_SQUARE('\uf272'),
        MDII_MINUS('\uf273'),
        MDII_PLUS_CIRCLE_O_DUPLICATE('\uf274'),
        MDII_PLUS_CIRCLE_O('\uf275'),
        MDII_PLUS_CIRCLE('\uf276'),
        MDII_PLUS_SQUARE('\uf277'),
        MDII_PLUS('\uf278'),
        MDII_SQUARE_O('\uf279'),
        MDII_STAR_CIRCLE('\uf27a'),
        MDII_STAR_HALF('\uf27b'),
        MDII_STAR_OUTLINE('\uf27c'),
        MDII_STAR('\uf27d'),
        MDII_BLUETOOTH_CONNECTED('\uf27e'),
        MDII_BLUETOOTH_OFF('\uf27f'),
        MDII_BLUETOOTH_SEARCH('\uf280'),
        MDII_BLUETOOTH_SETTING('\uf281'),
        MDII_BLUETOOTH('\uf282'),
        MDII_CAMERA_ADD('\uf283'),
        MDII_CAMERA_ALT('\uf284'),
        MDII_CAMERA_BW('\uf285'),
        MDII_CAMERA_FRONT('\uf286'),
        MDII_CAMERA_MIC('\uf287'),
        MDII_CAMERA_PARTY_MODE('\uf288'),
        MDII_CAMERA_REAR('\uf289'),
        MDII_CAMERA_ROLL('\uf28a'),
        MDII_CAMERA_SWITCH('\uf28b'),
        MDII_CAMERA('\uf28c'),
        MDII_CARD_ALERT('\uf28d'),
        MDII_CARD_OFF('\uf28e'),
        MDII_CARD_SD('\uf28f'),
        MDII_CARD_SIM('\uf290'),
        MDII_DESKTOP_MAC('\uf291'),
        MDII_DESKTOP_WINDOWS('\uf292'),
        MDII_DEVICE_HUB('\uf293'),
        MDII_DEVICES_OFF('\uf294'),
        MDII_DEVICES('\uf295'),
        MDII_DOCK('\uf296'),
        MDII_FLOPPY('\uf297'),
        MDII_GAMEPAD('\uf298'),
        MDII_GPS_DOT('\uf299'),
        MDII_GPS_OFF('\uf29a'),
        MDII_GPS('\uf29b'),
        MDII_HEADSET_MIC('\uf29c'),
        MDII_HEADSET('\uf29d'),
        MDII_INPUT_ANTENNA('\uf29e'),
        MDII_INPUT_COMPOSITE('\uf29f'),
        MDII_INPUT_HDMI('\uf2a0'),
        MDII_INPUT_POWER('\uf2a1'),
        MDII_INPUT_SVIDEO('\uf2a2'),
        MDII_KEYBOARD_HIDE('\uf2a3'),
        MDII_KEYBOARD('\uf2a4'),
        MDII_LAPTOP_CHROMEBOOK('\uf2a5'),
        MDII_LAPTOP_MAC('\uf2a6'),
        MDII_LAPTOP('\uf2a7'),
        MDII_MIC_OFF('\uf2a8'),
        MDII_MIC_OUTLINE('\uf2a9'),
        MDII_MIC_SETTING('\uf2aa'),
        MDII_MIC('\uf2ab'),
        MDII_MOUSE('\uf2ac'),
        MDII_NETWORK_ALERT('\uf2ad'),
        MDII_NETWORK_LOCKED('\uf2ae'),
        MDII_NETWORK_OFF('\uf2af'),
        MDII_NETWORK_OUTLINE('\uf2b0'),
        MDII_NETWORK_SETTING('\uf2b1'),
        MDII_NETWORK('\uf2b2'),
        MDII_PHONE_BLUETOOTH('\uf2b3'),
        MDII_PHONE_END('\uf2b4'),
        MDII_PHONE_FORWARDED('\uf2b5'),
        MDII_PHONE_IN_TALK('\uf2b6'),
        MDII_PHONE_LOCKED('\uf2b7'),
        MDII_PHONE_MISSED('\uf2b8'),
        MDII_PHONE_MSG('\uf2b9'),
        MDII_PHONE_PAUSED('\uf2ba'),
        MDII_PHONE_RING('\uf2bb'),
        MDII_PHONE_SETTING('\uf2bc'),
        MDII_PHONE_SIP('\uf2bd'),
        MDII_PHONE('\uf2be'),
        MDII_PORTABLE_WIFI_CHANGES('\uf2bf'),
        MDII_PORTABLE_WIFI_OFF('\uf2c0'),
        MDII_PORTABLE_WIFI('\uf2c1'),
        MDII_RADIO('\uf2c2'),
        MDII_READER('\uf2c3'),
        MDII_REMOTE_CONTROL_ALT('\uf2c4'),
        MDII_REMOTE_CONTROL('\uf2c5'),
        MDII_ROUTER('\uf2c6'),
        MDII_SCANNER('\uf2c7'),
        MDII_SMARTPHONE_DOWNLOAD('\uf2c9'),
        MDII_SMARTPHONE_ERASE('\uf2ca'),
        MDII_SMARTPHONE_INFO('\uf2cb'),
        MDII_SMARTPHONE_IPHONE('\uf2cc'),
        MDII_SMARTPHONE_LANDSCAPE_LOCK('\uf2cd'),
        MDII_SMARTPHONE_LANDSCAPE('\uf2ce'),
        MDII_SMARTPHONE_LOCK('\uf2cf'),
        MDII_SMARTPHONE_PORTRAIT_LOCK('\uf2d0'),
        MDII_SMARTPHONE_RING('\uf2d1'),
        MDII_SMARTPHONE_SETTING('\uf2d2'),
        MDII_SMARTPHONE_SETUP('\uf2d3'),
        MDII_SMARTPHONE('\uf2d4'),
        MDII_SPEAKER('\uf2d5'),
        MDII_TABLET_MAC('\uf2d7'),
        MDII_TABLET('\uf2d8'),
        MDII_TV_ALT_PLAY('\uf2d9'),
        MDII_TV_LIST('\uf2da'),
        MDII_TV_PLAY('\uf2db'),
        MDII_TV('\uf2dc'),
        MDII_USB('\uf2dd'),
        MDII_VIDEOCAM_OFF('\uf2de'),
        MDII_VIDEOCAM_SWITCH('\uf2df'),
        MDII_VIDEOCAM('\uf2e0'),
        MDII_WATCH('\uf2e1'),
        MDII_WIFI_ALT_2('\uf2e2'),
        MDII_WIFI_ALT('\uf2e3'),
        MDII_WIFI_INFO('\uf2e4'),
        MDII_WIFI_LOCK('\uf2e5'),
        MDII_WIFI_OFF('\uf2e6'),
        MDII_WIFI_OUTLINE('\uf2e7'),
        MDII_WIFI('\uf2e8'),
        MDII_ARROW_LEFT_BOTTOM('\uf2e9'),
        MDII_ARROW_LEFT('\uf2ea'),
        MDII_ARROW_MERGE('\uf2eb'),
        MDII_ARROW_MISSED('\uf2ec'),
        MDII_ARROW_RIGHT_TOP('\uf2ed'),
        MDII_ARROW_RIGHT('\uf2ee'),
        MDII_ARROW_SPLIT('\uf2ef'),
        MDII_ARROWS('\uf2f0'),
        MDII_CARET_DOWN_CIRCLE('\uf2f1'),
        MDII_CARET_DOWN('\uf2f2'),
        MDII_CARET_LEFT_CIRCLE('\uf2f3'),
        MDII_CARET_LEFT('\uf2f4'),
        MDII_CARET_RIGHT_CIRCLE('\uf2f5'),
        MDII_CARET_RIGHT('\uf2f6'),
        MDII_CARET_UP_CIRCLE('\uf2f7'),
        MDII_CARET_UP('\uf2f8'),
        MDII_CHEVRON_DOWN('\uf2f9'),
        MDII_CHEVRON_LEFT('\uf2fa'),
        MDII_CHEVRON_RIGHT('\uf2fb'),
        MDII_CHEVRON_UP('\uf2fc'),
        MDII_FORWARD('\uf2fd'),
        MDII_LONG_ARROW_DOWN('\uf2fe'),
        MDII_LONG_ARROW_LEFT('\uf2ff'),
        MDII_LONG_ARROW_RETURN('\uf300'),
        MDII_LONG_ARROW_RIGHT('\uf301'),
        MDII_LONG_ARROW_TAB('\uf302'),
        MDII_LONG_ARROW_UP('\uf303'),
        MDII_ROTATE_CCW('\uf304'),
        MDII_ROTATE_CW('\uf305'),
        MDII_ROTATE_LEFT('\uf306'),
        MDII_ROTATE_RIGHT('\uf307'),
        MDII_SQUARE_DOWN('\uf308'),
        MDII_SQUARE_RIGHT('\uf309'),
        MDII_SWAP_ALT('\uf30a'),
        MDII_SWAP_VERTICAL_CIRCLE('\uf30b'),
        MDII_SWAP_VERTICAL('\uf30c'),
        MDII_SWAP('\uf30d'),
        MDII_TRENDING_DOWN('\uf30e'),
        MDII_TRENDING_FLAT('\uf30f'),
        MDII_TRENDING_UP('\uf310'),
        MDII_UNFOLD_LESS('\uf311'),
        MDII_UNFOLD_MORE('\uf312'),
        MDII_APPS('\uf313'),
        MDII_GRID_OFF('\uf314'),
        MDII_GRID('\uf315'),
        MDII_VIEW_AGENDA('\uf316'),
        MDII_VIEW_ARRAY('\uf317'),
        MDII_VIEW_CAROUSEL('\uf318'),
        MDII_VIEW_COLUMN('\uf319'),
        MDII_VIEW_COMFY('\uf31a'),
        MDII_VIEW_COMPACT('\uf31b'),
        MDII_VIEW_DASHBOARD('\uf31c'),
        MDII_VIEW_DAY('\uf31d'),
        MDII_VIEW_HEADLINE('\uf31e'),
        MDII_VIEW_LIST_ALT('\uf31f'),
        MDII_VIEW_LIST('\uf320'),
        MDII_VIEW_MODULE('\uf321'),
        MDII_VIEW_QUILT('\uf322'),
        MDII_VIEW_STREAM('\uf323'),
        MDII_VIEW_SUBTITLES('\uf324'),
        MDII_VIEW_TOC('\uf325'),
        MDII_VIEW_WEB('\uf326'),
        MDII_VIEW_WEEK('\uf327'),
        MDII_WIDGETS('\uf328'),
        MDII_ALARM_CHECK('\uf329'),
        MDII_ALARM_OFF('\uf32a'),
        MDII_ALARM_PLUS('\uf32b'),
        MDII_ALARM_SNOOZE('\uf32c'),
        MDII_ALARM('\uf32d'),
        MDII_CALENDAR_ALT('\uf32e'),
        MDII_CALENDAR_CHECK('\uf32f'),
        MDII_CALENDAR_CLOSE('\uf330'),
        MDII_CALENDAR_NOTE('\uf331'),
        MDII_CALENDAR('\uf332'),
        MDII_TIME_COUNTDOWN('\uf333'),
        MDII_TIME_INTERVAL('\uf334'),
        MDII_TIME_RESTORE_SETTING('\uf335'),
        MDII_TIME_RESTORE('\uf336'),
        MDII_TIME('\uf337'),
        MDII_TIMER_OFF('\uf338'),
        MDII_TIMER('\uf339'),
        MDII_APPLE('\uf33c'),
        MDII_BEHANCE('\uf33d'),
        MDII_CODEPEN('\uf33e'),
        MDII_DRIBBBLE('\uf33f'),
        MDII_DROPBOX('\uf340'),
        MDII_EVERNOTE('\uf341'),
        MDII_FACEBOOK_BOX('\uf342'),
        MDII_FACEBOOK('\uf343'),
        MDII_GITHUB_BOX('\uf344'),
        MDII_GITHUB('\uf345'),
        MDII_GOOGLE_DRIVE('\uf346'),
        MDII_GOOGLE_EARTH('\uf347'),
        MDII_GOOGLE_GLASS('\uf348'),
        MDII_GOOGLE_MAPS('\uf349'),
        MDII_GOOGLE_PAGES('\uf34a'),
        MDII_GOOGLE_PLAY('\uf34b'),
        MDII_GOOGLE_PLUS_BOX('\uf34c'),
        MDII_GOOGLE_PLUS('\uf34d'),
        MDII_GOOGLE('\uf34e'),
        MDII_INSTAGRAM('\uf34f'),
        MDII_LANGUAGE_CSS3('\uf350'),
        MDII_LANGUAGE_HTML5('\uf351'),
        MDII_LANGUAGE_JAVASCRIPT('\uf352'),
        MDII_LANGUAGE_PYTHON_ALT('\uf353'),
        MDII_LANGUAGE_PYTHON('\uf354'),
        MDII_LASTFM('\uf355'),
        MDII_LINKEDIN_BOX('\uf356'),
        MDII_PAYPAL('\uf357'),
        MDII_PINTEREST_BOX('\uf358'),
        MDII_POCKET('\uf359'),
        MDII_POLYMER('\uf35a'),
        MDII_SHARE('\uf35b'),
        MDII_STACKOVERFLOW('\uf35c'),
        MDII_STEAM_SQUARE('\uf35d'),
        MDII_STEAM('\uf35e'),
        MDII_TWITTER_BOX('\uf35f'),
        MDII_TWITTER('\uf360'),
        MDII_VK('\uf361'),
        MDII_WIKIPEDIA('\uf362'),
        MDII_WINDOWS('\uf363'),
        MDII_ASPECT_RATIO_ALT('\uf364'),
        MDII_ASPECT_RATIO('\uf365'),
        MDII_BLUR_CIRCULAR('\uf366'),
        MDII_BLUR_LINEAR('\uf367'),
        MDII_BLUR_OFF('\uf368'),
        MDII_BLUR('\uf369'),
        MDII_BRIGHTNESS_2('\uf36a'),
        MDII_BRIGHTNESS_3('\uf36b'),
        MDII_BRIGHTNESS_4('\uf36c'),
        MDII_BRIGHTNESS_5('\uf36d'),
        MDII_BRIGHTNESS_6('\uf36e'),
        MDII_BRIGHTNESS_7('\uf36f'),
        MDII_BRIGHTNESS_AUTO('\uf370'),
        MDII_BRIGHTNESS_SETTING('\uf371'),
        MDII_BROKEN_IMAGE('\uf372'),
        MDII_CENTER_FOCUS_STRONG('\uf373'),
        MDII_CENTER_FOCUS_WEAK('\uf374'),
        MDII_COMPARE('\uf375'),
        MDII_CROP_16_9('\uf376'),
        MDII_CROP_3_2('\uf377'),
        MDII_CROP_5_4('\uf378'),
        MDII_CROP_7_5('\uf379'),
        MDII_CROP_DIN('\uf37a'),
        MDII_CROP_FREE('\uf37b'),
        MDII_CROP_LANDSCAPE('\uf37c'),
        MDII_CROP_PORTRAIT('\uf37d'),
        MDII_CROP_SQUARE('\uf37e'),
        MDII_EXPOSURE_ALT('\uf37f'),
        MDII_EXPOSURE('\uf380'),
        MDII_FILTER_B_AND_W('\uf381'),
        MDII_FILTER_CENTER_FOCUS('\uf382'),
        MDII_FILTER_FRAMES('\uf383'),
        MDII_FILTER_TILT_SHIFT('\uf384'),
        MDII_GRADIENT('\uf385'),
        MDII_GRAIN('\uf386'),
        MDII_GRAPHIC_EQ('\uf387'),
        MDII_HDR_OFF('\uf388'),
        MDII_HDR_STRONG('\uf389'),
        MDII_HDR_WEAK('\uf38a'),
        MDII_HDR('\uf38b'),
        MDII_IRIDESCENT('\uf38c'),
        MDII_LEAK_OFF('\uf38d'),
        MDII_LEAK('\uf38e'),
        MDII_LOOKS('\uf38f'),
        MDII_LOUPE('\uf390'),
        MDII_PANORAMA_HORIZONTAL('\uf391'),
        MDII_PANORAMA_VERTICAL('\uf392'),
        MDII_PANORAMA_WIDE_ANGLE('\uf393'),
        MDII_PHOTO_SIZE_SELECT_LARGE('\uf394'),
        MDII_PHOTO_SIZE_SELECT_SMALL('\uf395'),
        MDII_PICTURE_IN_PICTURE('\uf396'),
        MDII_SLIDESHOW('\uf397'),
        MDII_TEXTURE('\uf398'),
        MDII_TONALITY('\uf399'),
        MDII_VIGNETTE('\uf39a'),
        MDII_WB_AUTO('\uf39b'),
        MDII_EJECT_ALT('\uf39c'),
        MDII_EJECT('\uf39d'),
        MDII_EQUALIZER('\uf39e'),
        MDII_FAST_FORWARD('\uf39f'),
        MDII_FAST_REWIND('\uf3a0'),
        MDII_FORWARD_10('\uf3a1'),
        MDII_FORWARD_30('\uf3a2'),
        MDII_FORWARD_5('\uf3a3'),
        MDII_HEARING('\uf3a4'),
        MDII_PAUSE_CIRCLE_OUTLINE('\uf3a5'),
        MDII_PAUSE_CIRCLE('\uf3a6'),
        MDII_PAUSE('\uf3a7'),
        MDII_PLAY_CIRCLE_OUTLINE('\uf3a8'),
        MDII_PLAY_CIRCLE('\uf3a9'),
        MDII_PLAY('\uf3aa'),
        MDII_PLAYLIST_AUDIO('\uf3ab'),
        MDII_PLAYLIST_PLUS('\uf3ac'),
        MDII_REPEAT_ONE('\uf3ad'),
        MDII_REPEAT('\uf3ae'),
        MDII_REPLAY_10('\uf3af'),
        MDII_REPLAY_30('\uf3b0'),
        MDII_REPLAY_5('\uf3b1'),
        MDII_REPLAY('\uf3b2'),
        MDII_SHUFFLE('\uf3b3'),
        MDII_SKIP_NEXT('\uf3b4'),
        MDII_SKIP_PREVIOUS('\uf3b5'),
        MDII_STOP('\uf3b6'),
        MDII_SURROUND_SOUND('\uf3b7'),
        MDII_TUNE('\uf3b8'),
        MDII_VOLUME_DOWN('\uf3b9'),
        MDII_VOLUME_MUTE('\uf3ba'),
        MDII_VOLUME_OFF('\uf3bb'),
        MDII_VOLUME_UP('\uf3bc'),
        MDII_N_1_SQUARE('\uf3bd'),
        MDII_N_2_SQUARE('\uf3be'),
        MDII_N_3_SQUARE('\uf3bf'),
        MDII_N_4_SQUARE('\uf3c0'),
        MDII_N_5_SQUARE('\uf3c1'),
        MDII_N_6_SQUARE('\uf3c2'),
        MDII_NEG_1('\uf3c3'),
        MDII_NEG_2('\uf3c4'),
        MDII_PLUS_1('\uf3c5'),
        MDII_PLUS_2('\uf3c6'),
        MDII_SEC_10('\uf3c7'),
        MDII_SEC_3('\uf3c8'),
        MDII_ZERO('\uf3c9'),
        MDII_AIRLINE_SEAT_FLAT_ANGLED('\uf3ca'),
        MDII_AIRLINE_SEAT_FLAT('\uf3cb'),
        MDII_AIRLINE_SEAT_INDIVIDUAL_SUITE('\uf3cc'),
        MDII_AIRLINE_SEAT_LEGROOM_EXTRA('\uf3cd'),
        MDII_AIRLINE_SEAT_LEGROOM_NORMAL('\uf3ce'),
        MDII_AIRLINE_SEAT_LEGROOM_REDUCED('\uf3cf'),
        MDII_AIRLINE_SEAT_RECLINE_EXTRA('\uf3d0'),
        MDII_AIRLINE_SEAT_RECLINE_NORMAL('\uf3d1'),
        MDII_AIRPLAY('\uf3d2'),
        MDII_CLOSED_CAPTION('\uf3d3'),
        MDII_CONFIRMATION_NUMBER('\uf3d4'),
        MDII_DEVELOPER_BOARD('\uf3d5'),
        MDII_DISC_FULL('\uf3d6'),
        MDII_EXPLICIT('\uf3d7'),
        MDII_FLIGHT_LAND('\uf3d8'),
        MDII_FLIGHT_TAKEOFF('\uf3d9'),
        MDII_FLIP_TO_BACK('\uf3da'),
        MDII_FLIP_TO_FRONT('\uf3db'),
        MDII_GROUP_WORK('\uf3dc'),
        MDII_HD('\uf3dd'),
        MDII_HQ('\uf3de'),
        MDII_MARKUNREAD_MAILBOX('\uf3df'),
        MDII_MEMORY('\uf3e0'),
        MDII_NFC('\uf3e1'),
        MDII_PLAY_FOR_WORK('\uf3e2'),
        MDII_POWER_INPUT('\uf3e3'),
        MDII_PRESENTI_TO_ALL('\uf3e4'),
        MDII_SATELLITE('\uf3e5'),
        MDII_TAP_AND_PLAY('\uf3e6'),
        MDII_VIBRATION('\uf3e7'),
        MDII_VOICEMAIL('\uf3e8'),
        MDII_GROUP('\uf3e9'),
        MDII_RSS('\uf3ea'),
        MDII_SHAPE('\uf3eb'),
        MDII_SPINNER('\uf3ec'),
        MDII_UNGROUP('\uf3ed'),
        MDII_500PX('\uf3ee'),
        MDII_8TRACKS('\uf3ef'),
        MDII_AMAZON('\uf3f0'),
        MDII_BLOGGER('\uf3f1'),
        MDII_DELICIOUS('\uf3f2'),
        MDII_DISQUS('\uf3f3'),
        MDII_FLATTR('\uf3f4'),
        MDII_FLICKR('\uf3f5'),
        MDII_GITHUB_ALT('\uf3f6'),
        MDII_GOOGLE_OLD('\uf3f7'),
        MDII_LINKEDIN('\uf3f8'),
        MDII_ODNOKLASSNIKI('\uf3f9'),
        MDII_OUTLOOK('\uf3fa'),
        MDII_PAYPAL_ALT('\uf3fb'),
        MDII_PINTEREST('\uf3fc'),
        MDII_PLAYSTATION('\uf3fd'),
        MDII_REDDIT('\uf3fe'),
        MDII_SKYPE('\uf3ff'),
        MDII_SLIDESHARE('\uf400'),
        MDII_SOUNDCLOUD('\uf401'),
        MDII_TUMBLR('\uf402'),
        MDII_TWITCH('\uf403'),
        MDII_VIMEO('\uf404'),
        MDII_WHATSAPP('\uf405'),
        MDII_XBOX('\uf406'),
        MDII_YAHOO('\uf407'),
        MDII_YOUTUBE_PLAY('\uf408'),
        MDII_YOUTUBE('\uf409'),
        MDII_IMPORT_EXPORT('\uf30c'),
        MDII_AIRPLANEMODE_INACTIVE('\uf102'),
        MDII_AIRPLANEMODE_ACTIVE('\uf103'),
        MDII_RATE_REVIEW('\uf103'),
        MDII_COMMENTI_SIGN('\uf25a'),
        MDII_NETWORK_WARNING('\uf2ad'),
        MDII_SHOPPING_CART_ADD('\uf1ca'),
        MDII_FILE_ADD('\uf221'),
        MDII_NETWORK_WIFI_SCAN('\uf2e4'),
        MDII_COLLECTION_ADD('\uf14e'),
        MDII_FORMAT_PLAYLIST_ADD('\uf3ac'),
        MDII_FORMAT_QUEUE_MUSIC('\uf3ab'),
        MDII_PLUS_BOX('\uf277'),
        MDII_TAG_BACKSPACE('\uf1d9'),
        MDII_ALARM_ADD('\uf32b'),
        MDII_BATTERY_CHARGING('\uf114'),
        MDII_DAYDREAM_SETTING('\uf217'),
        MDII_MORE_HORIZ('\uf19c'),
        MDII_BOOK_PHOTO('\uf11b'),
        MDII_INCANDESCENT('\uf189'),
        MDII_WB_IRIDESCENT('\uf38c'),
        MDII_CALENDAR_REMOVE('\uf330'),
        MDII_REFRESH_SYNC_DISABLED('\uf1b7'),
        MDII_REFRESH_SYNC_PROBLEM('\uf1b6'),
        MDII_CROP_ORIGINAL('\uf17e'),
        MDII_POWER_OFF('\uf1af'),
        MDII_POWER_OFF_SETTING('\uf1ae'),
        MDII_LEAK_REMOVE('\uf38d'),
        MDII_STAR_BORDER('\uf27c'),
        MDII_BRIGHTNESS_LOW('\uf36d'),
        MDII_BRIGHTNESS_MEDIUM('\uf36e'),
        MDII_BRIGHTNESS_HIGH('\uf36f'),
        MDII_SMARTPHONE_PORTRAIT('\uf2d4'),
        MDII_LIVE_TV('\uf2d9'),
        MDII_FORMAT_TEXTDIRECTION_L_TO_R('\uf249'),
        MDII_FORMAT_TEXTDIRECTION_R_TO_L('\uf24a'),
        MDII_ARROW_BACK('\uf2ea'),
        MDII_ARROW_FORWARD('\uf2ee'),
        MDII_ARROW_IN('\uf2e9'),
        MDII_ARROW_OUT('\uf2ed'),
        MDII_ROTATE_90_DEGREES_CCW('\uf304'),
        MDII_ADB('\uf33a'),
        MDII_NETWORK_WIFI('\uf2e8'),
        MDII_NETWORK_WIFI_ALT('\uf2e3'),
        MDII_NETWORK_WIFI_LOCK('\uf2e5'),
        MDII_NETWORK_WIFI_OFF('\uf2e6'),
        MDII_NETWORK_WIFI_OUTLINE('\uf2e7'),
        MDII_NETWORK_WIFI_INFO('\uf2e4'),
        MDII_LAYERS_CLEAR('\uf18b'),
        MDII_COLORIZE('\uf15d'),
        MDII_FORMAT_PAINT('\uf1ba'),
        MDII_FORMAT_QUOTE('\uf1b2'),
        MDII_CAMERA_MONOCHROME_PHOTOS('\uf285'),
        MDII_SORT_BY_ALPHA('\uf1cf'),
        MDII_FOLDER_SHARED('\uf225'),
        MDII_FOLDER_SPECIAL('\uf226'),
        MDII_COMMENTI_DOTS('\uf260'),
        MDII_REORDER('\uf31e'),
        MDII_DEHAZE('\uf197'),
        MDII_SORT('\uf1ce'),
        MDII_PAGES('\uf34a'),
        MDII_STACK_OVERFLOW('\uf35c'),
        MDII_CALENDAR_ACCOUNT('\uf204'),
        MDII_PASTE('\uf109'),
        MDII_CUT('\uf1bc'),
        MDII_SAVE('\uf297'),
        MDII_SMARTPHONE_CODE('\uf139'),
        MDII_DIRECTIONS_BIKE('\uf117'),
        MDII_DIRECTIONS_BOAT('\uf11a'),
        MDII_DIRECTIONS_BUS('\uf121'),
        MDII_DIRECTIONS_CAR('\uf125'),
        MDII_DIRECTIONS_RAILWAY('\uf1b3'),
        MDII_DIRECTIONS_RUN('\uf215'),
        MDII_DIRECTIONS_SUBWAY('\uf1d5'),
        MDII_DIRECTIONS_WALK('\uf216'),
        MDII_LOCAL_HOTEL('\uf178'),
        MDII_LOCAL_ACTIVITY('\uf1df'),
        MDII_LOCAL_PLAY('\uf1df'),
        MDII_LOCAL_AIRPORT('\uf103'),
        MDII_LOCAL_ATM('\uf198'),
        MDII_LOCAL_BAR('\uf137'),
        MDII_LOCAL_CAFE('\uf13b'),
        MDII_LOCAL_CAR_WASH('\uf124'),
        MDII_LOCAL_CONVENIENCE_STORE('\uf1d3'),
        MDII_LOCAL_DINING('\uf153'),
        MDII_LOCAL_DRINK('\uf157'),
        MDII_LOCAL_FLORIST('\uf168'),
        MDII_LOCAL_GAS_STATION('\uf16f'),
        MDII_LOCAL_GROCERY_STORE('\uf1cb'),
        MDII_LOCAL_HOSPITAL('\uf177'),
        MDII_LOCAL_LAUNDRY_SERVICE('\uf1e9'),
        MDII_LOCAL_LIBRARY('\uf18d'),
        MDII_LOCAL_MALL('\uf195'),
        MDII_LOCAL_MOVIES('\uf19d'),
        MDII_LOCAL_OFFER('\uf187'),
        MDII_LOCAL_PARKING('\uf1a5'),
        MDII_LOCAL_PHARMACY('\uf176'),
        MDII_LOCAL_PHONE('\uf2be'),
        MDII_LOCAL_PIZZA('\uf1ac'),
        MDII_LOCAL_POST_OFFICE('\uf15a'),
        MDII_LOCAL_PRINTSHOP('\uf1b0'),
        MDII_LOCAL_SEE('\uf28c'),
        MDII_LOCAL_SHIPPING('\uf1e6'),
        MDII_LOCAL_STORE('\uf1d4'),
        MDII_LOCAL_TAXI('\uf123'),
        MDII_LOCAL_WC('\uf211'),
        MDII_MY_LOCATION('\uf299'),
        MDII_DIRECTIONS('\uf1e7');

        char materialDesignIconicCharacter;

        Icon(char character) {
            this.materialDesignIconicCharacter = character;
        }

        public String getFormattedName() {
            return "{" + name() + "}";
        }

        public char getCharacter() {
            return materialDesignIconicCharacter;
        }

        public String getName() {
            return name();
        }

        // remember the typeface so we can use it later
        private static ITypeface materialDesignIconicTypeface;

        @Override
        public ITypeface getTypeface() {
            if (materialDesignIconicTypeface == null) {
                setTypeface(new MaterialDesignIconic());
            }
            return materialDesignIconicTypeface;
        }

        private static void setTypeface(MaterialDesignIconic materialDesignIconicTypeface) {
            Icon.materialDesignIconicTypeface = materialDesignIconicTypeface;
        }
    }
}
