package com.rilixtech.materialdesigniconictypeface;

import ohos.agp.text.Font;
import ohos.app.AbilityContext;
import com.rilixtech.materialfancybutton.typeface.MfbIcon;
import com.rilixtech.materialfancybutton.typeface.MfbTypeface;
import com.rilixtech.materialfancybutton.utils.FontUtil;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;

/**
 * MfbTypeface implementation using the MaterialDesignIconic font. It hosts a variety of icons that can be used by
 * the MaterialFancyButton Components.
 */
public class MaterialDesignIconic implements MfbTypeface {
    private static final String TTF_FILE = "material-design-iconic-font-v2.2.0.ttf";
    private static final String MATERIAL_DESIGN_ICONIC_PREFIX = "MDII";
    public static final String MATERIAL_DESIGN_ICONIC_NAME = "Material Design Iconic";
    public static final String MATERIAL_DESIGN_ICONIC_VERSION = "2" + ".2.0";
    public static final String MATERIAL_DESIGN_ICONIC_AUTHOR = "Google. TTF created by Sergey Kupletsky";
    public static final String MATERIAL_DESIGN_ICONIC_URL = "http://zavoloklom.github.io/material-design-iconic-font/";
    public static final String MATERIAL_DESIGN_ICONIC_DESC = "Material Design Iconic Font is a full suite of material"
            + " design icons (created and maintained by Google) for easy scalable vector graphics on websites.";
    public static final String MATERIAL_DESIGN_ICONIC_LICENSE = "SIL OFL 1.1";
    public static final String MATERIAL_DESIGN_ICONIC_LICENSE_URL = "http://scripts.sil.org/OFL";

    private static Font materialDesignIconicTypeface = null;

    private static HashMap<String, Character> materialDesignIconicCharMap;

    /**
     * MaterialDesignIconic MfbIcon object corresponding to this typeface for the given key.
     *
     * @param key Key for which MaterialDesignIconic MfbIcon is to be retrieved.
     */
    @Override public MfbIcon getIcon(String key) {
        return Icon.valueOf(key);
    }

    /**
     * Get all the MaterialDesignIconic icon characters in a HashMap.
     *
     * @return HashMap of all MaterialDesignIconic icon character names mapped to their character values.
     */
    @Override public HashMap<String, Character> getCharacters() {
        if (materialDesignIconicCharMap == null) {
            HashMap<String, Character> characterHashMap = new HashMap<>();
            for (Icon v : Icon.values()) {
                characterHashMap.put(v.name(), v.materialDesignIconicCharacter);
            }
            setChars(characterHashMap);
        }

        return materialDesignIconicCharMap;
    }

    /**
     * Set the MaterialDesignIconic Characters into a HashMap.
     */
    private static void setChars(HashMap<String, Character> characterHashMap) {
        materialDesignIconicCharMap = characterHashMap;
    }

    /**
     * Return the MaterialDesignIconic Mapping Prefix.
     *
     * @return MaterialDesignIconic Mapping Prefix, used by all MaterialDesignIconic icons.
     */
    @Override public String getMappingPrefix() {
        return MATERIAL_DESIGN_ICONIC_PREFIX;
    }

    @Override public String getFontName() {
        return MATERIAL_DESIGN_ICONIC_NAME;
    }

    @Override public String getVersion() {
        return MATERIAL_DESIGN_ICONIC_VERSION;
    }

    @Override public int getIconCount() {
        return materialDesignIconicCharMap.size();
    }

    @Override public Collection<String> getIcons() {
        Collection<String> materialDesignIconicKeyList = new LinkedList<>();

        for (Icon value : Icon.values()) {
            materialDesignIconicKeyList.add(value.name());
        }

        return materialDesignIconicKeyList;
    }

    @Override public String getAuthor() {
        return MATERIAL_DESIGN_ICONIC_AUTHOR;
    }

    @Override public String getUrl() {
        return MATERIAL_DESIGN_ICONIC_URL;
    }

    @Override public String getDescription() {
        return MATERIAL_DESIGN_ICONIC_DESC;
    }

    @Override public String getLicense() {
        return MATERIAL_DESIGN_ICONIC_LICENSE;
    }

    @Override public String getLicenseUrl() {
        return MATERIAL_DESIGN_ICONIC_LICENSE_URL;
    }

    @Override
    public Font getTypeface(AbilityContext context) {
        if (materialDesignIconicTypeface == null) {
            try {
                cacheTypeface(FontUtil.getFontFromRawFile(context, TTF_FILE));
            } catch (IllegalStateException e) {
                throw new IllegalStateException(e);
            }
        }
        return materialDesignIconicTypeface;
    }

    private static void cacheTypeface(Font font) {
        materialDesignIconicTypeface = font;
    }

    /**
     * Enumerates all the supported Custom Icon Unicode characters by MaterialDesignIconic MfbTypeface.
     */
    public enum Icon implements MfbIcon {
        MDII_3D_ROTATION((char) 0xf101),
        MDII_AIRPLANE_OFF((char) 0xf102),
        MDII_AIRPLANE((char) 0xf103),
        MDII_ALBUM((char) 0xf104),
        MDII_ARCHIVE((char) 0xf105),
        MDII_ASSIGNMENTI_ACCOUNT((char) 0xf106),
        MDII_ASSIGNMENTI_ALERT((char) 0xf107),
        MDII_ASSIGNMENTI_CHECK((char) 0xf108),
        MDII_ASSIGNMENTI_O((char) 0xf109),
        MDII_ASSIGNMENTI_RETURN((char) 0xf10a),
        MDII_ASSIGNMENTI_RETURNED((char) 0xf10b),
        MDII_ASSIGNMENT((char) 0xf10c),
        MDII_ATTACHMENTI_ALT((char) 0xf10d),
        MDII_ATTACHMENT((char) 0xf10e),
        MDII_AUDIO((char) 0xf10f),
        MDII_BADGE_CHECK((char) 0xf110),
        MDII_BALANCE_WALLET((char) 0xf111),
        MDII_BALANCE((char) 0xf112),
        MDII_BATTERY_ALERT((char) 0xf113),
        MDII_BATTERY_FLASH((char) 0xf114),
        MDII_BATTERY_UNKNOWN((char) 0xf115),
        MDII_BATTERY((char) 0xf116),
        MDII_BIKE((char) 0xf117),
        MDII_BLOCK_ALT((char) 0xf118),
        MDII_BLOCK((char) 0xf119),
        MDII_BOAT((char) 0xf11a),
        MDII_BOOK_IMAGE((char) 0xf11b),
        MDII_BOOK((char) 0xf11c),
        MDII_BOOKMARK_OUTLINE((char) 0xf11d),
        MDII_BOOKMARK((char) 0xf11e),
        MDII_BRUSH((char) 0xf11f),
        MDII_BUG((char) 0xf120),
        MDII_BUS((char) 0xf121),
        MDII_CAKE((char) 0xf122),
        MDII_CAR_TAXI((char) 0xf123),
        MDII_CAR_WASH((char) 0xf124),
        MDII_CAR((char) 0xf125),
        MDII_CARD_GIFTCARD((char) 0xf126),
        MDII_CARD_MEMBERSHIP((char) 0xf127),
        MDII_CARD_TRAVEL((char) 0xf128),
        MDII_CARD((char) 0xf129),
        MDII_CASE_CHECK((char) 0xf12a),
        MDII_CASE_DOWNLOAD((char) 0xf12b),
        MDII_CASE_PLAY((char) 0xf12c),
        MDII_CASE((char) 0xf12d),
        MDII_CAST_CONNECTED((char) 0xf12e),
        MDII_CAST((char) 0xf12f),
        MDII_CHART_DONUT((char) 0xf130),
        MDII_CHART((char) 0xf131),
        MDII_CITY_ALT((char) 0xf132),
        MDII_CITY((char) 0xf133),
        MDII_CLOSE_CIRCLE_O((char) 0xf134),
        MDII_CLOSE_CIRCLE((char) 0xf135),
        MDII_CLOSE((char) 0xf136),
        MDII_COCKTAIL((char) 0xf137),
        MDII_CODE_SETTING((char) 0xf138),
        MDII_CODE_SMARTPHONE((char) 0xf139),
        MDII_CODE((char) 0xf13a),
        MDII_COFFEE((char) 0xf13b),
        MDII_COLLECTION_BOOKMARK((char) 0xf13c),
        MDII_COLLECTION_CASE_PLAY((char) 0xf13d),
        MDII_COLLECTION_FOLDER_IMAGE((char) 0xf13e),
        MDII_COLLECTION_IMAGE_O((char) 0xf13f),
        MDII_COLLECTION_IMAGE((char) 0xf140),
        MDII_COLLECTION_ITEM_1((char) 0xf141),
        MDII_COLLECTION_ITEM_2((char) 0xf142),
        MDII_COLLECTION_ITEM_3((char) 0xf143),
        MDII_COLLECTION_ITEM_4((char) 0xf144),
        MDII_COLLECTION_ITEM_5((char) 0xf145),
        MDII_COLLECTION_ITEM_6((char) 0xf146),
        MDII_COLLECTION_ITEM_7((char) 0xf147),
        MDII_COLLECTION_ITEM_8((char) 0xf148),
        MDII_COLLECTION_ITEM_9_PLUS((char) 0xf149),
        MDII_COLLECTION_ITEM_9((char) 0xf14a),
        MDII_COLLECTION_ITEM((char) 0xf14b),
        MDII_COLLECTION_MUSIC((char) 0xf14c),
        MDII_COLLECTION_PDF((char) 0xf14d),
        MDII_COLLECTION_PLUS((char) 0xf14e),
        MDII_COLLECTION_SPEAKER((char) 0xf14f),
        MDII_COLLECTION_TEXT((char) 0xf150),
        MDII_COLLECTION_VIDEO((char) 0xf151),
        MDII_COMPASS((char) 0xf152),
        MDII_CUTLERY((char) 0xf153),
        MDII_DELETE((char) 0xf154),
        MDII_DIALPAD((char) 0xf155),
        MDII_DNS((char) 0xf156),
        MDII_DRINK((char) 0xf157),
        MDII_EDIT((char) 0xf158),
        MDII_EMAIL_OPEN((char) 0xf159),
        MDII_EMAIL((char) 0xf15a),
        MDII_EYE_OFF((char) 0xf15b),
        MDII_EYE((char) 0xf15c),
        MDII_EYEDROPPER((char) 0xf15d),
        MDII_FAVORITE_OUTLINE((char) 0xf15e),
        MDII_FAVORITE((char) 0xf15f),
        MDII_FILTER_LIST((char) 0xf160),
        MDII_FIRE((char) 0xf161),
        MDII_FLAG((char) 0xf162),
        MDII_FLARE((char) 0xf163),
        MDII_FLASH_AUTO((char) 0xf164),
        MDII_FLASH_OFF((char) 0xf165),
        MDII_FLASH((char) 0xf166),
        MDII_FLIP((char) 0xf167),
        MDII_FLOWER_ALT((char) 0xf168),
        MDII_FLOWER((char) 0xf169),
        MDII_FONT((char) 0xf16a),
        MDII_FULLSCREEN_ALT((char) 0xf16b),
        MDII_FULLSCREEN_EXIT((char) 0xf16c),
        MDII_FULLSCREEN((char) 0xf16d),
        MDII_FUNCTIONS((char) 0xf16e),
        MDII_GAS_STATION((char) 0xf16f),
        MDII_GESTURE((char) 0xf170),
        MDII_GLOBE_ALT((char) 0xf171),
        MDII_GLOBE_LOCK((char) 0xf172),
        MDII_GLOBE((char) 0xf173),
        MDII_GRADUATION_CAP((char) 0xf174),
        MDII_HOME((char) 0xf175),
        MDII_HOSPITAL_ALT((char) 0xf176),
        MDII_HOSPITAL((char) 0xf177),
        MDII_HOTEL((char) 0xf178),
        MDII_HOURGLASS_ALT((char) 0xf179),
        MDII_HOURGLASS_OUTLINE((char) 0xf17a),
        MDII_HOURGLASS((char) 0xf17b),
        MDII_HTTP((char) 0xf17c),
        MDII_IMAGE_ALT((char) 0xf17d),
        MDII_IMAGE_O((char) 0xf17e),
        MDII_IMAGE((char) 0xf17f),
        MDII_INBOX((char) 0xf180),
        MDII_INVERT_COLORS_OFF((char) 0xf181),
        MDII_INVERT_COLORS((char) 0xf182),
        MDII_KEY((char) 0xf183),
        MDII_LABEL_ALT_OUTLINE((char) 0xf184),
        MDII_LABEL_ALT((char) 0xf185),
        MDII_LABEL_HEART((char) 0xf186),
        MDII_LABEL((char) 0xf187),
        MDII_LABELS((char) 0xf188),
        MDII_LAMP((char) 0xf189),
        MDII_LANDSCAPE((char) 0xf18a),
        MDII_LAYERS_OFF((char) 0xf18b),
        MDII_LAYERS((char) 0xf18c),
        MDII_LIBRARY((char) 0xf18d),
        MDII_LINK((char) 0xf18e),
        MDII_LOCK_OPEN((char) 0xf18f),
        MDII_LOCK_OUTLINE((char) 0xf190),
        MDII_LOCK((char) 0xf191),
        MDII_MAIL_REPLY_ALL((char) 0xf192),
        MDII_MAIL_REPLY((char) 0xf193),
        MDII_MAIL_SEND((char) 0xf194),
        MDII_MALL((char) 0xf195),
        MDII_MAP((char) 0xf196),
        MDII_MENU((char) 0xf197),
        MDII_MONEY_BOX((char) 0xf198),
        MDII_MONEY_OFF((char) 0xf199),
        MDII_MONEY((char) 0xf19a),
        MDII_MORE_VERT((char) 0xf19b),
        MDII_MORE((char) 0xf19c),
        MDII_MOVIE_ALT((char) 0xf19d),
        MDII_MOVIE((char) 0xf19e),
        MDII_NATURE_PEOPLE((char) 0xf19f),
        MDII_NATURE((char) 0xf1a0),
        MDII_NAVIGATION((char) 0xf1a1),
        MDII_OPEN_IN_BROWSER((char) 0xf1a2),
        MDII_OPEN_IN_NEW((char) 0xf1a3),
        MDII_PALETTE((char) 0xf1a4),
        MDII_PARKING((char) 0xf1a5),
        MDII_PIN_ACCOUNT((char) 0xf1a6),
        MDII_PIN_ASSISTANT((char) 0xf1a7),
        MDII_PIN_DROP((char) 0xf1a8),
        MDII_PIN_HELP((char) 0xf1a9),
        MDII_PIN_OFF((char) 0xf1aa),
        MDII_PIN((char) 0xf1ab),
        MDII_PIZZA((char) 0xf1ac),
        MDII_PLASTER((char) 0xf1ad),
        MDII_POWER_SETTING((char) 0xf1ae),
        MDII_POWER((char) 0xf1af),
        MDII_PRINT((char) 0xf1b0),
        MDII_PUZZLE_PIECE((char) 0xf1b1),
        MDII_QUOTE((char) 0xf1b2),
        MDII_RAILWAY((char) 0xf1b3),
        MDII_RECEIPT((char) 0xf1b4),
        MDII_REFRESH_ALT((char) 0xf1b5),
        MDII_REFRESH_SYNC_ALERT((char) 0xf1b6),
        MDII_REFRESH_SYNC_OFF((char) 0xf1b7),
        MDII_REFRESH_SYNC((char) 0xf1b8),
        MDII_REFRESH((char) 0xf1b9),
        MDII_ROLLER((char) 0xf1ba),
        MDII_RULER((char) 0xf1bb),
        MDII_SCISSORS((char) 0xf1bc),
        MDII_SCREEN_ROTATION_LOCK((char) 0xf1bd),
        MDII_SCREEN_ROTATION((char) 0xf1be),
        MDII_SEARCH_FOR((char) 0xf1bf),
        MDII_SEARCH_IN_FILE((char) 0xf1c0),
        MDII_SEARCH_IN_PAGE((char) 0xf1c1),
        MDII_SEARCH_REPLACE((char) 0xf1c2),
        MDII_SEARCH((char) 0xf1c3),
        MDII_SEAT((char) 0xf1c4),
        MDII_SETTINGS_SQUARE((char) 0xf1c5),
        MDII_SETTINGS((char) 0xf1c6),
        MDII_SHIELD_CHECK((char) 0xf1c7),
        MDII_SHIELD_SECURITY((char) 0xf1c8),
        MDII_SHOPPING_BASKET((char) 0xf1c9),
        MDII_SHOPPING_CART_PLUS((char) 0xf1ca),
        MDII_SHOPPING_CART((char) 0xf1cb),
        MDII_SIGN_IN((char) 0xf1cc),
        MDII_SORT_AMOUNT_ASC((char) 0xf1cd),
        MDII_SORT_AMOUNT_DESC((char) 0xf1ce),
        MDII_SORT_ASC((char) 0xf1cf),
        MDII_SORT_DESC((char) 0xf1d0),
        MDII_SPELLCHECK((char) 0xf1d1),
        MDII_STORAGE((char) 0xf1d2),
        MDII_STORE_24((char) 0xf1d3),
        MDII_STORE((char) 0xf1d4),
        MDII_SUBWAY((char) 0xf1d5),
        MDII_SUN((char) 0xf1d6),
        MDII_TAB_UNSELECTED((char) 0xf1d7),
        MDII_TAB((char) 0xf1d8),
        MDII_TAG_CLOSE((char) 0xf1d9),
        MDII_TAG_MORE((char) 0xf1da),
        MDII_TAG((char) 0xf1db),
        MDII_THUMB_DOWN((char) 0xf1dc),
        MDII_THUMB_UP_DOWN((char) 0xf1dd),
        MDII_THUMB_UP((char) 0xf1de),
        MDII_TICKET_STAR((char) 0xf1df),
        MDII_TOLL((char) 0xf1e0),
        MDII_TOYS((char) 0xf1e1),
        MDII_TRAFFIC((char) 0xf1e2),
        MDII_TRANSLATE((char) 0xf1e3),
        MDII_TRIANGLE_DOWN((char) 0xf1e4),
        MDII_TRIANGLE_UP((char) 0xf1e5),
        MDII_TRUCK((char) 0xf1e6),
        MDII_TURNING_SIGN((char) 0xf1e7),
        MDII_WALLPAPER((char) 0xf1e8),
        MDII_WASHING_MACHINE((char) 0xf1e9),
        MDII_WINDOW_MAXIMIZE((char) 0xf1ea),
        MDII_WINDOW_MINIMIZE((char) 0xf1eb),
        MDII_WINDOW_RESTORE((char) 0xf1ec),
        MDII_WRENCH((char) 0xf1ed),
        MDII_ZOOM_IN((char) 0xf1ee),
        MDII_ZOOM_OUT((char) 0xf1ef),
        MDII_ALERT_CIRCLE_O((char) 0xf1f0),
        MDII_ALERT_CIRCLE((char) 0xf1f1),
        MDII_ALERT_OCTAGON((char) 0xf1f2),
        MDII_ALERT_POLYGON((char) 0xf1f3),
        MDII_ALERT_TRIANGLE((char) 0xf1f4),
        MDII_HELP_OUTLINE((char) 0xf1f5),
        MDII_HELP((char) 0xf1f6),
        MDII_INFO_OUTLINE((char) 0xf1f7),
        MDII_INFO((char) 0xf1f8),
        MDII_NOTIFICATIONS_ACTIVE((char) 0xf1f9),
        MDII_NOTIFICATIONS_ADD((char) 0xf1fa),
        MDII_NOTIFICATIONS_NONE((char) 0xf1fb),
        MDII_NOTIFICATIONS_OFF((char) 0xf1fc),
        MDII_NOTIFICATIONS_PAUSED((char) 0xf1fd),
        MDII_NOTIFICATIONS((char) 0xf1fe),
        MDII_ACCOUNT_ADD((char) 0xf1ff),
        MDII_ACCOUNT_BOX_MAIL((char) 0xf200),
        MDII_ACCOUNT_BOX_O((char) 0xf201),
        MDII_ACCOUNT_BOX_PHONE((char) 0xf202),
        MDII_ACCOUNT_BOX((char) 0xf203),
        MDII_ACCOUNT_CALENDAR((char) 0xf204),
        MDII_ACCOUNT_CIRCLE((char) 0xf205),
        MDII_ACCOUNT_O((char) 0xf206),
        MDII_ACCOUNT((char) 0xf207),
        MDII_ACCOUNTS_ADD((char) 0xf208),
        MDII_ACCOUNTS_ALT((char) 0xf209),
        MDII_ACCOUNTS_LIST_ALT((char) 0xf20a),
        MDII_ACCOUNTS_LIST((char) 0xf20b),
        MDII_ACCOUNTS_OUTLINE((char) 0xf20c),
        MDII_ACCOUNTS((char) 0xf20d),
        MDII_FACE((char) 0xf20e),
        MDII_FEMALE((char) 0xf20f),
        MDII_MALE_ALT((char) 0xf210),
        MDII_MALE_FEMALE((char) 0xf211),
        MDII_MALE((char) 0xf212),
        MDII_MOOD_BAD((char) 0xf213),
        MDII_MOOD((char) 0xf214),
        MDII_RUN((char) 0xf215),
        MDII_WALK((char) 0xf216),
        MDII_CLOUD_BOX((char) 0xf217),
        MDII_CLOUD_CIRCLE((char) 0xf218),
        MDII_CLOUD_DONE((char) 0xf219),
        MDII_CLOUD_DOWNLOAD((char) 0xf21a),
        MDII_CLOUD_OFF((char) 0xf21b),
        MDII_CLOUD_OUTLINE_ALT((char) 0xf21c),
        MDII_CLOUD_OUTLINE((char) 0xf21d),
        MDII_CLOUD_UPLOAD((char) 0xf21e),
        MDII_CLOUD((char) 0xf21f),
        MDII_DOWNLOAD((char) 0xf220),
        MDII_FILE_PLUS((char) 0xf221),
        MDII_FILE_TEXT((char) 0xf222),
        MDII_FILE((char) 0xf223),
        MDII_FOLDER_OUTLINE((char) 0xf224),
        MDII_FOLDER_PERSON((char) 0xf225),
        MDII_FOLDER_STAR_ALT((char) 0xf226),
        MDII_FOLDER_STAR((char) 0xf227),
        MDII_FOLDER((char) 0xf228),
        MDII_GIF((char) 0xf229),
        MDII_UPLOAD((char) 0xf22a),
        MDII_BORDER_ALL((char) 0xf22b),
        MDII_BORDER_BOTTOM((char) 0xf22c),
        MDII_BORDER_CLEAR((char) 0xf22d),
        MDII_BORDER_COLOR((char) 0xf22e),
        MDII_BORDER_HORIZONTAL((char) 0xf22f),
        MDII_BORDER_INNER((char) 0xf230),
        MDII_BORDER_LEFT((char) 0xf231),
        MDII_BORDER_OUTER((char) 0xf232),
        MDII_BORDER_RIGHT((char) 0xf233),
        MDII_BORDER_STYLE((char) 0xf234),
        MDII_BORDER_TOP((char) 0xf235),
        MDII_BORDER_VERTICAL((char) 0xf236),
        MDII_COPY((char) 0xf237),
        MDII_CROP((char) 0xf238),
        MDII_FORMAT_ALIGN_CENTER((char) 0xf239),
        MDII_FORMAT_ALIGN_JUSTIFY((char) 0xf23a),
        MDII_FORMAT_ALIGN_LEFT((char) 0xf23b),
        MDII_FORMAT_ALIGN_RIGHT((char) 0xf23c),
        MDII_FORMAT_BOLD((char) 0xf23d),
        MDII_FORMAT_CLEAR_ALL((char) 0xf23e),
        MDII_FORMAT_CLEAR((char) 0xf23f),
        MDII_FORMAT_COLOR_FILL((char) 0xf240),
        MDII_FORMAT_COLOR_RESET((char) 0xf241),
        MDII_FORMAT_COLOR_TEXT((char) 0xf242),
        MDII_FORMAT_INDENTI_DECREASE((char) 0xf243),
        MDII_FORMAT_INDENTI_INCREASE((char) 0xf244),
        MDII_FORMAT_ITALIC((char) 0xf245),
        MDII_FORMAT_LINE_SPACING((char) 0xf246),
        MDII_FORMAT_LIST_BULLETED((char) 0xf247),
        MDII_FORMAT_LIST_NUMBERED((char) 0xf248),
        MDII_FORMAT_LTR((char) 0xf249),
        MDII_FORMAT_RTL((char) 0xf24a),
        MDII_FORMAT_SIZE((char) 0xf24b),
        MDII_FORMAT_STRIKETHROUGH_S((char) 0xf24c),
        MDII_FORMAT_STRIKETHROUGH((char) 0xf24d),
        MDII_FORMAT_SUBJECT((char) 0xf24e),
        MDII_FORMAT_UNDERLINED((char) 0xf24f),
        MDII_FORMAT_VALIGN_BOTTOM((char) 0xf250),
        MDII_FORMAT_VALIGN_CENTER((char) 0xf251),
        MDII_FORMAT_VALIGN_TOP((char) 0xf252),
        MDII_REDO((char) 0xf253),
        MDII_SELECT_ALL((char) 0xf254),
        MDII_SPACE_BAR((char) 0xf255),
        MDII_TEXT_FORMAT((char) 0xf256),
        MDII_TRANSFORM((char) 0xf257),
        MDII_UNDO((char) 0xf258),
        MDII_WRAP_TEXT((char) 0xf259),
        MDII_COMMENTI_ALERT((char) 0xf25a),
        MDII_COMMENTI_ALT_TEXT((char) 0xf25b),
        MDII_COMMENTI_ALT((char) 0xf25c),
        MDII_COMMENTI_EDIT((char) 0xf25d),
        MDII_COMMENTI_IMAGE((char) 0xf25e),
        MDII_COMMENTI_LIST((char) 0xf25f),
        MDII_COMMENTI_MORE((char) 0xf260),
        MDII_COMMENTI_OUTLINE((char) 0xf261),
        MDII_COMMENTI_TEXT_ALT((char) 0xf262),
        MDII_COMMENTI_TEXT((char) 0xf263),
        MDII_COMMENTI_VIDEO((char) 0xf264),
        MDII_COMMENT((char) 0xf265),
        MDII_COMMENTS((char) 0xf266),
        MDII_CHECK_ALL((char) 0xf267),
        MDII_CHECK_CIRCLE_U((char) 0xf268),
        MDII_CHECK_CIRCLE((char) 0xf269),
        MDII_CHECK_SQUARE((char) 0xf26a),
        MDII_CHECK((char) 0xf26b),
        MDII_CIRCLE_O((char) 0xf26c),
        MDII_CIRCLE((char) 0xf26d),
        MDII_DOT_CIRCLE_ALT((char) 0xf26e),
        MDII_DOT_CIRCLE((char) 0xf26f),
        MDII_MINUS_CIRCLE_OUTLINE((char) 0xf270),
        MDII_MINUS_CIRCLE((char) 0xf271),
        MDII_MINUS_SQUARE((char) 0xf272),
        MDII_MINUS((char) 0xf273),
        MDII_PLUS_CIRCLE_O_DUPLICATE((char) 0xf274),
        MDII_PLUS_CIRCLE_O((char) 0xf275),
        MDII_PLUS_CIRCLE((char) 0xf276),
        MDII_PLUS_SQUARE((char) 0xf277),
        MDII_PLUS((char) 0xf278),
        MDII_SQUARE_O((char) 0xf279),
        MDII_STAR_CIRCLE((char) 0xf27a),
        MDII_STAR_HALF((char) 0xf27b),
        MDII_STAR_OUTLINE((char) 0xf27c),
        MDII_STAR((char) 0xf27d),
        MDII_BLUETOOTH_CONNECTED((char) 0xf27e),
        MDII_BLUETOOTH_OFF((char) 0xf27f),
        MDII_BLUETOOTH_SEARCH((char) 0xf280),
        MDII_BLUETOOTH_SETTING((char) 0xf281),
        MDII_BLUETOOTH((char) 0xf282),
        MDII_CAMERA_ADD((char) 0xf283),
        MDII_CAMERA_ALT((char) 0xf284),
        MDII_CAMERA_BW((char) 0xf285),
        MDII_CAMERA_FRONT((char) 0xf286),
        MDII_CAMERA_MIC((char) 0xf287),
        MDII_CAMERA_PARTY_MODE((char) 0xf288),
        MDII_CAMERA_REAR((char) 0xf289),
        MDII_CAMERA_ROLL((char) 0xf28a),
        MDII_CAMERA_SWITCH((char) 0xf28b),
        MDII_CAMERA((char) 0xf28c),
        MDII_CARD_ALERT((char) 0xf28d),
        MDII_CARD_OFF((char) 0xf28e),
        MDII_CARD_SD((char) 0xf28f),
        MDII_CARD_SIM((char) 0xf290),
        MDII_DESKTOP_MAC((char) 0xf291),
        MDII_DESKTOP_WINDOWS((char) 0xf292),
        MDII_DEVICE_HUB((char) 0xf293),
        MDII_DEVICES_OFF((char) 0xf294),
        MDII_DEVICES((char) 0xf295),
        MDII_DOCK((char) 0xf296),
        MDII_FLOPPY((char) 0xf297),
        MDII_GAMEPAD((char) 0xf298),
        MDII_GPS_DOT((char) 0xf299),
        MDII_GPS_OFF((char) 0xf29a),
        MDII_GPS((char) 0xf29b),
        MDII_HEADSET_MIC((char) 0xf29c),
        MDII_HEADSET((char) 0xf29d),
        MDII_INPUT_ANTENNA((char) 0xf29e),
        MDII_INPUT_COMPOSITE((char) 0xf29f),
        MDII_INPUT_HDMI((char) 0xf2a0),
        MDII_INPUT_POWER((char) 0xf2a1),
        MDII_INPUT_SVIDEO((char) 0xf2a2),
        MDII_KEYBOARD_HIDE((char) 0xf2a3),
        MDII_KEYBOARD((char) 0xf2a4),
        MDII_LAPTOP_CHROMEBOOK((char) 0xf2a5),
        MDII_LAPTOP_MAC((char) 0xf2a6),
        MDII_LAPTOP((char) 0xf2a7),
        MDII_MIC_OFF((char) 0xf2a8),
        MDII_MIC_OUTLINE((char) 0xf2a9),
        MDII_MIC_SETTING((char) 0xf2aa),
        MDII_MIC((char) 0xf2ab),
        MDII_MOUSE((char) 0xf2ac),
        MDII_NETWORK_ALERT((char) 0xf2ad),
        MDII_NETWORK_LOCKED((char) 0xf2ae),
        MDII_NETWORK_OFF((char) 0xf2af),
        MDII_NETWORK_OUTLINE((char) 0xf2b0),
        MDII_NETWORK_SETTING((char) 0xf2b1),
        MDII_NETWORK((char) 0xf2b2),
        MDII_PHONE_BLUETOOTH((char) 0xf2b3),
        MDII_PHONE_END((char) 0xf2b4),
        MDII_PHONE_FORWARDED((char) 0xf2b5),
        MDII_PHONE_IN_TALK((char) 0xf2b6),
        MDII_PHONE_LOCKED((char) 0xf2b7),
        MDII_PHONE_MISSED((char) 0xf2b8),
        MDII_PHONE_MSG((char) 0xf2b9),
        MDII_PHONE_PAUSED((char) 0xf2ba),
        MDII_PHONE_RING((char) 0xf2bb),
        MDII_PHONE_SETTING((char) 0xf2bc),
        MDII_PHONE_SIP((char) 0xf2bd),
        MDII_PHONE((char) 0xf2be),
        MDII_PORTABLE_WIFI_CHANGES((char) 0xf2bf),
        MDII_PORTABLE_WIFI_OFF((char) 0xf2c0),
        MDII_PORTABLE_WIFI((char) 0xf2c1),
        MDII_RADIO((char) 0xf2c2),
        MDII_READER((char) 0xf2c3),
        MDII_REMOTE_CONTROL_ALT((char) 0xf2c4),
        MDII_REMOTE_CONTROL((char) 0xf2c5),
        MDII_ROUTER((char) 0xf2c6),
        MDII_SCANNER((char) 0xf2c7),
        MDII_SMARTPHONE_DOWNLOAD((char) 0xf2c9),
        MDII_SMARTPHONE_ERASE((char) 0xf2ca),
        MDII_SMARTPHONE_INFO((char) 0xf2cb),
        MDII_SMARTPHONE_IPHONE((char) 0xf2cc),
        MDII_SMARTPHONE_LANDSCAPE_LOCK((char) 0xf2cd),
        MDII_SMARTPHONE_LANDSCAPE((char) 0xf2ce),
        MDII_SMARTPHONE_LOCK((char) 0xf2cf),
        MDII_SMARTPHONE_PORTRAIT_LOCK((char) 0xf2d0),
        MDII_SMARTPHONE_RING((char) 0xf2d1),
        MDII_SMARTPHONE_SETTING((char) 0xf2d2),
        MDII_SMARTPHONE_SETUP((char) 0xf2d3),
        MDII_SMARTPHONE((char) 0xf2d4),
        MDII_SPEAKER((char) 0xf2d5),
        MDII_TABLET_MAC((char) 0xf2d7),
        MDII_TABLET((char) 0xf2d8),
        MDII_TV_ALT_PLAY((char) 0xf2d9),
        MDII_TV_LIST((char) 0xf2da),
        MDII_TV_PLAY((char) 0xf2db),
        MDII_TV((char) 0xf2dc),
        MDII_USB((char) 0xf2dd),
        MDII_VIDEOCAM_OFF((char) 0xf2de),
        MDII_VIDEOCAM_SWITCH((char) 0xf2df),
        MDII_VIDEOCAM((char) 0xf2e0),
        MDII_WATCH((char) 0xf2e1),
        MDII_WIFI_ALT_2((char) 0xf2e2),
        MDII_WIFI_ALT((char) 0xf2e3),
        MDII_WIFI_INFO((char) 0xf2e4),
        MDII_WIFI_LOCK((char) 0xf2e5),
        MDII_WIFI_OFF((char) 0xf2e6),
        MDII_WIFI_OUTLINE((char) 0xf2e7),
        MDII_WIFI((char) 0xf2e8),
        MDII_ARROW_LEFT_BOTTOM((char) 0xf2e9),
        MDII_ARROW_LEFT((char) 0xf2ea),
        MDII_ARROW_MERGE((char) 0xf2eb),
        MDII_ARROW_MISSED((char) 0xf2ec),
        MDII_ARROW_RIGHT_TOP((char) 0xf2ed),
        MDII_ARROW_RIGHT((char) 0xf2ee),
        MDII_ARROW_SPLIT((char) 0xf2ef),
        MDII_ARROWS((char) 0xf2f0),
        MDII_CARET_DOWN_CIRCLE((char) 0xf2f1),
        MDII_CARET_DOWN((char) 0xf2f2),
        MDII_CARET_LEFT_CIRCLE((char) 0xf2f3),
        MDII_CARET_LEFT((char) 0xf2f4),
        MDII_CARET_RIGHT_CIRCLE((char) 0xf2f5),
        MDII_CARET_RIGHT((char) 0xf2f6),
        MDII_CARET_UP_CIRCLE((char) 0xf2f7),
        MDII_CARET_UP((char) 0xf2f8),
        MDII_CHEVRON_DOWN((char) 0xf2f9),
        MDII_CHEVRON_LEFT((char) 0xf2fa),
        MDII_CHEVRON_RIGHT((char) 0xf2fb),
        MDII_CHEVRON_UP((char) 0xf2fc),
        MDII_FORWARD((char) 0xf2fd),
        MDII_LONG_ARROW_DOWN((char) 0xf2fe),
        MDII_LONG_ARROW_LEFT((char) 0xf2ff),
        MDII_LONG_ARROW_RETURN((char) 0xf300),
        MDII_LONG_ARROW_RIGHT((char) 0xf301),
        MDII_LONG_ARROW_TAB((char) 0xf302),
        MDII_LONG_ARROW_UP((char) 0xf303),
        MDII_ROTATE_CCW((char) 0xf304),
        MDII_ROTATE_CW((char) 0xf305),
        MDII_ROTATE_LEFT((char) 0xf306),
        MDII_ROTATE_RIGHT((char) 0xf307),
        MDII_SQUARE_DOWN((char) 0xf308),
        MDII_SQUARE_RIGHT((char) 0xf309),
        MDII_SWAP_ALT((char) 0xf30a),
        MDII_SWAP_VERTICAL_CIRCLE((char) 0xf30b),
        MDII_SWAP_VERTICAL((char) 0xf30c),
        MDII_SWAP((char) 0xf30d),
        MDII_TRENDING_DOWN((char) 0xf30e),
        MDII_TRENDING_FLAT((char) 0xf30f),
        MDII_TRENDING_UP((char) 0xf310),
        MDII_UNFOLD_LESS((char) 0xf311),
        MDII_UNFOLD_MORE((char) 0xf312),
        MDII_APPS((char) 0xf313),
        MDII_GRID_OFF((char) 0xf314),
        MDII_GRID((char) 0xf315),
        MDII_VIEW_AGENDA((char) 0xf316),
        MDII_VIEW_ARRAY((char) 0xf317),
        MDII_VIEW_CAROUSEL((char) 0xf318),
        MDII_VIEW_COLUMN((char) 0xf319),
        MDII_VIEW_COMFY((char) 0xf31a),
        MDII_VIEW_COMPACT((char) 0xf31b),
        MDII_VIEW_DASHBOARD((char) 0xf31c),
        MDII_VIEW_DAY((char) 0xf31d),
        MDII_VIEW_HEADLINE((char) 0xf31e),
        MDII_VIEW_LIST_ALT((char) 0xf31f),
        MDII_VIEW_LIST((char) 0xf320),
        MDII_VIEW_MODULE((char) 0xf321),
        MDII_VIEW_QUILT((char) 0xf322),
        MDII_VIEW_STREAM((char) 0xf323),
        MDII_VIEW_SUBTITLES((char) 0xf324),
        MDII_VIEW_TOC((char) 0xf325),
        MDII_VIEW_WEB((char) 0xf326),
        MDII_VIEW_WEEK((char) 0xf327),
        MDII_WIDGETS((char) 0xf328),
        MDII_ALARM_CHECK((char) 0xf329),
        MDII_ALARM_OFF((char) 0xf32a),
        MDII_ALARM_PLUS((char) 0xf32b),
        MDII_ALARM_SNOOZE((char) 0xf32c),
        MDII_ALARM((char) 0xf32d),
        MDII_CALENDAR_ALT((char) 0xf32e),
        MDII_CALENDAR_CHECK((char) 0xf32f),
        MDII_CALENDAR_CLOSE((char) 0xf330),
        MDII_CALENDAR_NOTE((char) 0xf331),
        MDII_CALENDAR((char) 0xf332),
        MDII_TIME_COUNTDOWN((char) 0xf333),
        MDII_TIME_INTERVAL((char) 0xf334),
        MDII_TIME_RESTORE_SETTING((char) 0xf335),
        MDII_TIME_RESTORE((char) 0xf336),
        MDII_TIME((char) 0xf337),
        MDII_TIMER_OFF((char) 0xf338),
        MDII_TIMER((char) 0xf339),
        MDII_APPLE((char) 0xf33c),
        MDII_BEHANCE((char) 0xf33d),
        MDII_CODEPEN((char) 0xf33e),
        MDII_DRIBBBLE((char) 0xf33f),
        MDII_DROPBOX((char) 0xf340),
        MDII_EVERNOTE((char) 0xf341),
        MDII_FACEBOOK_BOX((char) 0xf342),
        MDII_FACEBOOK((char) 0xf343),
        MDII_GITHUB_BOX((char) 0xf344),
        MDII_GITHUB((char) 0xf345),
        MDII_GOOGLE_DRIVE((char) 0xf346),
        MDII_GOOGLE_EARTH((char) 0xf347),
        MDII_GOOGLE_GLASS((char) 0xf348),
        MDII_GOOGLE_MAPS((char) 0xf349),
        MDII_GOOGLE_PAGES((char) 0xf34a),
        MDII_GOOGLE_PLAY((char) 0xf34b),
        MDII_GOOGLE_PLUS_BOX((char) 0xf34c),
        MDII_GOOGLE_PLUS((char) 0xf34d),
        MDII_GOOGLE((char) 0xf34e),
        MDII_INSTAGRAM((char) 0xf34f),
        MDII_LANGUAGE_CSS3((char) 0xf350),
        MDII_LANGUAGE_HTML5((char) 0xf351),
        MDII_LANGUAGE_JAVASCRIPT((char) 0xf352),
        MDII_LANGUAGE_PYTHON_ALT((char) 0xf353),
        MDII_LANGUAGE_PYTHON((char) 0xf354),
        MDII_LASTFM((char) 0xf355),
        MDII_LINKEDIN_BOX((char) 0xf356),
        MDII_PAYPAL((char) 0xf357),
        MDII_PINTEREST_BOX((char) 0xf358),
        MDII_POCKET((char) 0xf359),
        MDII_POLYMER((char) 0xf35a),
        MDII_SHARE((char) 0xf35b),
        MDII_STACKOVERFLOW((char) 0xf35c),
        MDII_STEAM_SQUARE((char) 0xf35d),
        MDII_STEAM((char) 0xf35e),
        MDII_TWITTER_BOX((char) 0xf35f),
        MDII_TWITTER((char) 0xf360),
        MDII_VK((char) 0xf361),
        MDII_WIKIPEDIA((char) 0xf362),
        MDII_WINDOWS((char) 0xf363),
        MDII_ASPECT_RATIO_ALT((char) 0xf364),
        MDII_ASPECT_RATIO((char) 0xf365),
        MDII_BLUR_CIRCULAR((char) 0xf366),
        MDII_BLUR_LINEAR((char) 0xf367),
        MDII_BLUR_OFF((char) 0xf368),
        MDII_BLUR((char) 0xf369),
        MDII_BRIGHTNESS_2((char) 0xf36a),
        MDII_BRIGHTNESS_3((char) 0xf36b),
        MDII_BRIGHTNESS_4((char) 0xf36c),
        MDII_BRIGHTNESS_5((char) 0xf36d),
        MDII_BRIGHTNESS_6((char) 0xf36e),
        MDII_BRIGHTNESS_7((char) 0xf36f),
        MDII_BRIGHTNESS_AUTO((char) 0xf370),
        MDII_BRIGHTNESS_SETTING((char) 0xf371),
        MDII_BROKEN_IMAGE((char) 0xf372),
        MDII_CENTER_FOCUS_STRONG((char) 0xf373),
        MDII_CENTER_FOCUS_WEAK((char) 0xf374),
        MDII_COMPARE((char) 0xf375),
        MDII_CROP_16_9((char) 0xf376),
        MDII_CROP_3_2((char) 0xf377),
        MDII_CROP_5_4((char) 0xf378),
        MDII_CROP_7_5((char) 0xf379),
        MDII_CROP_DIN((char) 0xf37a),
        MDII_CROP_FREE((char) 0xf37b),
        MDII_CROP_LANDSCAPE((char) 0xf37c),
        MDII_CROP_PORTRAIT((char) 0xf37d),
        MDII_CROP_SQUARE((char) 0xf37e),
        MDII_EXPOSURE_ALT((char) 0xf37f),
        MDII_EXPOSURE((char) 0xf380),
        MDII_FILTER_B_AND_W((char) 0xf381),
        MDII_FILTER_CENTER_FOCUS((char) 0xf382),
        MDII_FILTER_FRAMES((char) 0xf383),
        MDII_FILTER_TILT_SHIFT((char) 0xf384),
        MDII_GRADIENT((char) 0xf385),
        MDII_GRAIN((char) 0xf386),
        MDII_GRAPHIC_EQ((char) 0xf387),
        MDII_HDR_OFF((char) 0xf388),
        MDII_HDR_STRONG((char) 0xf389),
        MDII_HDR_WEAK((char) 0xf38a),
        MDII_HDR((char) 0xf38b),
        MDII_IRIDESCENT((char) 0xf38c),
        MDII_LEAK_OFF((char) 0xf38d),
        MDII_LEAK((char) 0xf38e),
        MDII_LOOKS((char) 0xf38f),
        MDII_LOUPE((char) 0xf390),
        MDII_PANORAMA_HORIZONTAL((char) 0xf391),
        MDII_PANORAMA_VERTICAL((char) 0xf392),
        MDII_PANORAMA_WIDE_ANGLE((char) 0xf393),
        MDII_PHOTO_SIZE_SELECT_LARGE((char) 0xf394),
        MDII_PHOTO_SIZE_SELECT_SMALL((char) 0xf395),
        MDII_PICTURE_IN_PICTURE((char) 0xf396),
        MDII_SLIDESHOW((char) 0xf397),
        MDII_TEXTURE((char) 0xf398),
        MDII_TONALITY((char) 0xf399),
        MDII_VIGNETTE((char) 0xf39a),
        MDII_WB_AUTO((char) 0xf39b),
        MDII_EJECT_ALT((char) 0xf39c),
        MDII_EJECT((char) 0xf39d),
        MDII_EQUALIZER((char) 0xf39e),
        MDII_FAST_FORWARD((char) 0xf39f),
        MDII_FAST_REWIND((char) 0xf3a0),
        MDII_FORWARD_10((char) 0xf3a1),
        MDII_FORWARD_30((char) 0xf3a2),
        MDII_FORWARD_5((char) 0xf3a3),
        MDII_HEARING((char) 0xf3a4),
        MDII_PAUSE_CIRCLE_OUTLINE((char) 0xf3a5),
        MDII_PAUSE_CIRCLE((char) 0xf3a6),
        MDII_PAUSE((char) 0xf3a7),
        MDII_PLAY_CIRCLE_OUTLINE((char) 0xf3a8),
        MDII_PLAY_CIRCLE((char) 0xf3a9),
        MDII_PLAY((char) 0xf3aa),
        MDII_PLAYLIST_AUDIO((char) 0xf3ab),
        MDII_PLAYLIST_PLUS((char) 0xf3ac),
        MDII_REPEAT_ONE((char) 0xf3ad),
        MDII_REPEAT((char) 0xf3ae),
        MDII_REPLAY_10((char) 0xf3af),
        MDII_REPLAY_30((char) 0xf3b0),
        MDII_REPLAY_5((char) 0xf3b1),
        MDII_REPLAY((char) 0xf3b2),
        MDII_SHUFFLE((char) 0xf3b3),
        MDII_SKIP_NEXT((char) 0xf3b4),
        MDII_SKIP_PREVIOUS((char) 0xf3b5),
        MDII_STOP((char) 0xf3b6),
        MDII_SURROUND_SOUND((char) 0xf3b7),
        MDII_TUNE((char) 0xf3b8),
        MDII_VOLUME_DOWN((char) 0xf3b9),
        MDII_VOLUME_MUTE((char) 0xf3ba),
        MDII_VOLUME_OFF((char) 0xf3bb),
        MDII_VOLUME_UP((char) 0xf3bc),
        MDII_N_1_SQUARE((char) 0xf3bd),
        MDII_N_2_SQUARE((char) 0xf3be),
        MDII_N_3_SQUARE((char) 0xf3bf),
        MDII_N_4_SQUARE((char) 0xf3c0),
        MDII_N_5_SQUARE((char) 0xf3c1),
        MDII_N_6_SQUARE((char) 0xf3c2),
        MDII_NEG_1((char) 0xf3c3),
        MDII_NEG_2((char) 0xf3c4),
        MDII_PLUS_1((char) 0xf3c5),
        MDII_PLUS_2((char) 0xf3c6),
        MDII_SEC_10((char) 0xf3c7),
        MDII_SEC_3((char) 0xf3c8),
        MDII_ZERO((char) 0xf3c9),
        MDII_AIRLINE_SEAT_FLAT_ANGLED((char) 0xf3ca),
        MDII_AIRLINE_SEAT_FLAT((char) 0xf3cb),
        MDII_AIRLINE_SEAT_INDIVIDUAL_SUITE((char) 0xf3cc),
        MDII_AIRLINE_SEAT_LEGROOM_EXTRA((char) 0xf3cd),
        MDII_AIRLINE_SEAT_LEGROOM_NORMAL((char) 0xf3ce),
        MDII_AIRLINE_SEAT_LEGROOM_REDUCED((char) 0xf3cf),
        MDII_AIRLINE_SEAT_RECLINE_EXTRA((char) 0xf3d0),
        MDII_AIRLINE_SEAT_RECLINE_NORMAL((char) 0xf3d1),
        MDII_AIRPLAY((char) 0xf3d2),
        MDII_CLOSED_CAPTION((char) 0xf3d3),
        MDII_CONFIRMATION_NUMBER((char) 0xf3d4),
        MDII_DEVELOPER_BOARD((char) 0xf3d5),
        MDII_DISC_FULL((char) 0xf3d6),
        MDII_EXPLICIT((char) 0xf3d7),
        MDII_FLIGHT_LAND((char) 0xf3d8),
        MDII_FLIGHT_TAKEOFF((char) 0xf3d9),
        MDII_FLIP_TO_BACK((char) 0xf3da),
        MDII_FLIP_TO_FRONT((char) 0xf3db),
        MDII_GROUP_WORK((char) 0xf3dc),
        MDII_HD((char) 0xf3dd),
        MDII_HQ((char) 0xf3de),
        MDII_MARKUNREAD_MAILBOX((char) 0xf3df),
        MDII_MEMORY((char) 0xf3e0),
        MDII_NFC((char) 0xf3e1),
        MDII_PLAY_FOR_WORK((char) 0xf3e2),
        MDII_POWER_INPUT((char) 0xf3e3),
        MDII_PRESENTI_TO_ALL((char) 0xf3e4),
        MDII_SATELLITE((char) 0xf3e5),
        MDII_TAP_AND_PLAY((char) 0xf3e6),
        MDII_VIBRATION((char) 0xf3e7),
        MDII_VOICEMAIL((char) 0xf3e8),
        MDII_GROUP((char) 0xf3e9),
        MDII_RSS((char) 0xf3ea),
        MDII_SHAPE((char) 0xf3eb),
        MDII_SPINNER((char) 0xf3ec),
        MDII_UNGROUP((char) 0xf3ed),
        MDII_500PX((char) 0xf3ee),
        MDII_8TRACKS((char) 0xf3ef),
        MDII_AMAZON((char) 0xf3f0),
        MDII_BLOGGER((char) 0xf3f1),
        MDII_DELICIOUS((char) 0xf3f2),
        MDII_DISQUS((char) 0xf3f3),
        MDII_FLATTR((char) 0xf3f4),
        MDII_FLICKR((char) 0xf3f5),
        MDII_GITHUB_ALT((char) 0xf3f6),
        MDII_GOOGLE_OLD((char) 0xf3f7),
        MDII_LINKEDIN((char) 0xf3f8),
        MDII_ODNOKLASSNIKI((char) 0xf3f9),
        MDII_OUTLOOK((char) 0xf3fa),
        MDII_PAYPAL_ALT((char) 0xf3fb),
        MDII_PINTEREST((char) 0xf3fc),
        MDII_PLAYSTATION((char) 0xf3fd),
        MDII_REDDIT((char) 0xf3fe),
        MDII_SKYPE((char) 0xf3ff),
        MDII_SLIDESHARE((char) 0xf400),
        MDII_SOUNDCLOUD((char) 0xf401),
        MDII_TUMBLR((char) 0xf402),
        MDII_TWITCH((char) 0xf403),
        MDII_VIMEO((char) 0xf404),
        MDII_WHATSAPP((char) 0xf405),
        MDII_XBOX((char) 0xf406),
        MDII_YAHOO((char) 0xf407),
        MDII_YOUTUBE_PLAY((char) 0xf408),
        MDII_YOUTUBE((char) 0xf409),
        MDII_IMPORT_EXPORT((char) 0xf30c),
        MDII_AIRPLANEMODE_INACTIVE((char) 0xf102),
        MDII_AIRPLANEMODE_ACTIVE((char) 0xf103),
        MDII_RATE_REVIEW((char) 0xf103),
        MDII_COMMENTI_SIGN((char) 0xf25a),
        MDII_NETWORK_WARNING((char) 0xf2ad),
        MDII_SHOPPING_CART_ADD((char) 0xf1ca),
        MDII_FILE_ADD((char) 0xf221),
        MDII_NETWORK_WIFI_SCAN((char) 0xf2e4),
        MDII_COLLECTION_ADD((char) 0xf14e),
        MDII_FORMAT_PLAYLIST_ADD((char) 0xf3ac),
        MDII_FORMAT_QUEUE_MUSIC((char) 0xf3ab),
        MDII_PLUS_BOX((char) 0xf277),
        MDII_TAG_BACKSPACE((char) 0xf1d9),
        MDII_ALARM_ADD((char) 0xf32b),
        MDII_BATTERY_CHARGING((char) 0xf114),
        MDII_DAYDREAM_SETTING((char) 0xf217),
        MDII_MORE_HORIZ((char) 0xf19c),
        MDII_BOOK_PHOTO((char) 0xf11b),
        MDII_INCANDESCENT((char) 0xf189),
        MDII_WB_IRIDESCENT((char) 0xf38c),
        MDII_CALENDAR_REMOVE((char) 0xf330),
        MDII_REFRESH_SYNC_DISABLED((char) 0xf1b7),
        MDII_REFRESH_SYNC_PROBLEM((char) 0xf1b6),
        MDII_CROP_ORIGINAL((char) 0xf17e),
        MDII_POWER_OFF((char) 0xf1af),
        MDII_POWER_OFF_SETTING((char) 0xf1ae),
        MDII_LEAK_REMOVE((char) 0xf38d),
        MDII_STAR_BORDER((char) 0xf27c),
        MDII_BRIGHTNESS_LOW((char) 0xf36d),
        MDII_BRIGHTNESS_MEDIUM((char) 0xf36e),
        MDII_BRIGHTNESS_HIGH((char) 0xf36f),
        MDII_SMARTPHONE_PORTRAIT((char) 0xf2d4),
        MDII_LIVE_TV((char) 0xf2d9),
        MDII_FORMAT_TEXTDIRECTION_L_TO_R((char) 0xf249),
        MDII_FORMAT_TEXTDIRECTION_R_TO_L((char) 0xf24a),
        MDII_ARROW_BACK((char) 0xf2ea),
        MDII_ARROW_FORWARD((char) 0xf2ee),
        MDII_ARROW_IN((char) 0xf2e9),
        MDII_ARROW_OUT((char) 0xf2ed),
        MDII_ROTATE_90_DEGREES_CCW((char) 0xf304),
        MDII_ADB((char) 0xf33a),
        MDII_NETWORK_WIFI((char) 0xf2e8),
        MDII_NETWORK_WIFI_ALT((char) 0xf2e3),
        MDII_NETWORK_WIFI_LOCK((char) 0xf2e5),
        MDII_NETWORK_WIFI_OFF((char) 0xf2e6),
        MDII_NETWORK_WIFI_OUTLINE((char) 0xf2e7),
        MDII_NETWORK_WIFI_INFO((char) 0xf2e4),
        MDII_LAYERS_CLEAR((char) 0xf18b),
        MDII_COLORIZE((char) 0xf15d),
        MDII_FORMAT_PAINT((char) 0xf1ba),
        MDII_FORMAT_QUOTE((char) 0xf1b2),
        MDII_CAMERA_MONOCHROME_PHOTOS((char) 0xf285),
        MDII_SORT_BY_ALPHA((char) 0xf1cf),
        MDII_FOLDER_SHARED((char) 0xf225),
        MDII_FOLDER_SPECIAL((char) 0xf226),
        MDII_COMMENTI_DOTS((char) 0xf260),
        MDII_REORDER((char) 0xf31e),
        MDII_DEHAZE((char) 0xf197),
        MDII_SORT((char) 0xf1ce),
        MDII_PAGES((char) 0xf34a),
        MDII_STACK_OVERFLOW((char) 0xf35c),
        MDII_CALENDAR_ACCOUNT((char) 0xf204),
        MDII_PASTE((char) 0xf109),
        MDII_CUT((char) 0xf1bc),
        MDII_SAVE((char) 0xf297),
        MDII_SMARTPHONE_CODE((char) 0xf139),
        MDII_DIRECTIONS_BIKE((char) 0xf117),
        MDII_DIRECTIONS_BOAT((char) 0xf11a),
        MDII_DIRECTIONS_BUS((char) 0xf121),
        MDII_DIRECTIONS_CAR((char) 0xf125),
        MDII_DIRECTIONS_RAILWAY((char) 0xf1b3),
        MDII_DIRECTIONS_RUN((char) 0xf215),
        MDII_DIRECTIONS_SUBWAY((char) 0xf1d5),
        MDII_DIRECTIONS_WALK((char) 0xf216),
        MDII_LOCAL_HOTEL((char) 0xf178),
        MDII_LOCAL_ACTIVITY((char) 0xf1df),
        MDII_LOCAL_PLAY((char) 0xf1df),
        MDII_LOCAL_AIRPORT((char) 0xf103),
        MDII_LOCAL_ATM((char) 0xf198),
        MDII_LOCAL_BAR((char) 0xf137),
        MDII_LOCAL_CAFE((char) 0xf13b),
        MDII_LOCAL_CAR_WASH((char) 0xf124),
        MDII_LOCAL_CONVENIENCE_STORE((char) 0xf1d3),
        MDII_LOCAL_DINING((char) 0xf153),
        MDII_LOCAL_DRINK((char) 0xf157),
        MDII_LOCAL_FLORIST((char) 0xf168),
        MDII_LOCAL_GAS_STATION((char) 0xf16f),
        MDII_LOCAL_GROCERY_STORE((char) 0xf1cb),
        MDII_LOCAL_HOSPITAL((char) 0xf177),
        MDII_LOCAL_LAUNDRY_SERVICE((char) 0xf1e9),
        MDII_LOCAL_LIBRARY((char) 0xf18d),
        MDII_LOCAL_MALL((char) 0xf195),
        MDII_LOCAL_MOVIES((char) 0xf19d),
        MDII_LOCAL_OFFER((char) 0xf187),
        MDII_LOCAL_PARKING((char) 0xf1a5),
        MDII_LOCAL_PHARMACY((char) 0xf176),
        MDII_LOCAL_PHONE((char) 0xf2be),
        MDII_LOCAL_PIZZA((char) 0xf1ac),
        MDII_LOCAL_POST_OFFICE((char) 0xf15a),
        MDII_LOCAL_PRINTSHOP((char) 0xf1b0),
        MDII_LOCAL_SEE((char) 0xf28c),
        MDII_LOCAL_SHIPPING((char) 0xf1e6),
        MDII_LOCAL_STORE((char) 0xf1d4),
        MDII_LOCAL_TAXI((char) 0xf123),
        MDII_LOCAL_WC((char) 0xf211),
        MDII_MY_LOCATION((char) 0xf299),
        MDII_DIRECTIONS((char) 0xf1e7);

        char materialDesignIconicCharacter;

        Icon(char character) {
            this.materialDesignIconicCharacter = character;
        }

        public String getFormattedName() {
            return "{" + name() + "}";
        }

        public char getCharacter() {
            return materialDesignIconicCharacter;
        }

        public String getName() {
            return name();
        }

        // remember the typeface so we can use it later
        private static MfbTypeface materialDesignIconicTypeface;

        @Override
        public MfbTypeface getTypeface() {
            if (materialDesignIconicTypeface == null) {
                setTypeface(new MaterialDesignIconic());
            }
            return materialDesignIconicTypeface;
        }

        private static void setTypeface(MaterialDesignIconic materialDesignIconicTypeface) {
            Icon.materialDesignIconicTypeface = materialDesignIconicTypeface;
        }
    }
}
