package com.rilixtech.googlematerialtypeface;

import ohos.agp.text.Font;
import ohos.app.AbilityContext;
import com.rilixtech.materialfancybutton.typeface.MfbIcon;
import com.rilixtech.materialfancybutton.typeface.MfbTypeface;
import com.rilixtech.materialfancybutton.utils.FontUtil;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;

/**
 * MfbTypeface implementation using the GoogleMaterial font. It hosts a variety of icons that can be used by
 * the MaterialFancyButton Components.
 */
public class GoogleMaterial implements MfbTypeface {
    private static final String TTF_FILE = "googlematerial.ttf";
    private static final String GOOGLE_MATERIAL_PREFIX = "GMDI";
    public static final String GOOGLE_MATERIAL_NAME = "Google Material";
    public static final String GOOGLE_MATERIAL_VERSION = "3" + ".0.1.0.original";
    public static final String GOOGLE_MATERIAL_AUTHOR = "Google";
    public static final String GOOGLE_MATERIAL_URL = "https://github.com/google/material-design-icons";
    public static final String GOOGLE_MATERIAL_DESC = "Material design icons are the official icon set from Google that"
            + " are designed under the material design guidelines.";
    public static final String GOOGLE_MATERIAL_LICENSE = "CC-BY 4.0";
    public static final String GOOGLE_MATERIAL_LICENSE_URL = "http://creativecommons.org/licenses/by/4.0/";

    private static Font googleMaterialTypeface = null;
    private static HashMap<String, Character> googleMaterialCharMap;


    /**
     * GoogleMaterial MfbIcon object corresponding to this typeface for the given key.
     *
     * @param key Key for which GoogleMaterial MfbIcon is to be retrieved.
     */
    @Override public MfbIcon getIcon(String key) {
        return Icon.valueOf(key);
    }

    /**
     * Get all the GoogleMaterial icon characters in a HashMap.
     *
     * @return HashMap of all GoogleMaterial icon character names mapped to their character values.
     */
    @Override public HashMap<String, Character> getCharacters() {
        if (googleMaterialCharMap == null) {
            HashMap<String, Character> characterHashMap = new HashMap<>();
            for (Icon v : Icon.values()) {
                characterHashMap.put(v.name(), v.googleMaterialCharacter);
            }
            setChars(characterHashMap);
        }
        return googleMaterialCharMap;
    }

    /**
     * Set the GoogleMaterial Characters into a HashMap.
     */
    private static void setChars(HashMap<String, Character> characterHashMap) {
        googleMaterialCharMap = characterHashMap;
    }

    /**
     * Return the GoogleMaterial Mapping Prefix.
     *
     * @return GoogleMaterial Mapping Prefix, used by all GoogleMaterial icons.
     */
    @Override public String getMappingPrefix() {
        return GOOGLE_MATERIAL_PREFIX;
    }

    @Override public String getFontName() {
        return GOOGLE_MATERIAL_NAME;
    }

    @Override public String getVersion() {
        return GOOGLE_MATERIAL_VERSION;
    }

    @Override public int getIconCount() {
        return googleMaterialCharMap.size();
    }

    @Override public Collection<String> getIcons() {
        Collection<String> googleMaterialKeyList = new LinkedList<>();
        for (Icon value : Icon.values()) {
            googleMaterialKeyList.add(value.name());
        }
        return googleMaterialKeyList;
    }

    @Override public String getAuthor() {
        return GOOGLE_MATERIAL_AUTHOR;
    }

    @Override public String getUrl() {
        return GOOGLE_MATERIAL_URL;
    }

    @Override public String getDescription() {
        return GOOGLE_MATERIAL_DESC;
    }

    @Override public String getLicense() {
        return GOOGLE_MATERIAL_LICENSE;
    }

    @Override public String getLicenseUrl() {
        return GOOGLE_MATERIAL_LICENSE_URL;
    }

    @Override
    public Font getTypeface(AbilityContext context) {
        if (googleMaterialTypeface == null) {
            try {
                cacheTypeface(FontUtil.getFontFromRawFile(context, TTF_FILE));
            } catch (IllegalStateException e) {
                throw new IllegalStateException(e);
            }
        }
        return googleMaterialTypeface;
    }

    private static void cacheTypeface(Font font) {
        googleMaterialTypeface = font;
    }

    /**
     * Enumerates all the supported Custom Icon Unicode characters by GoogleMaterial MfbTypeface.
     */
    public enum Icon implements MfbIcon {
        GMDI_3D_ROTATION((char) 0xe84d),
        GMDI_AC_UNIT((char) 0xeb3b),
        GMDI_ACCESS_ALARM((char) 0xe190),
        GMDI_ACCESS_ALARMS((char) 0xe191),
        GMDI_ACCESS_TIME((char) 0xe192),
        GMDI_ACCESSIBILITY((char) 0xe84e),
        GMDI_ACCESSIBLE((char) 0xe914),
        GMDI_ACCOUNT_BALANCE((char) 0xe84f),
        GMDI_ACCOUNT_BALANCE_WALLET((char) 0xe850),
        GMDI_ACCOUNT_BOX((char) 0xe851),
        GMDI_ACCOUNT_CIRCLE((char) 0xe853),
        GMDI_ADB((char) 0xe60e),
        GMDI_ADD((char) 0xe145),
        GMDI_ADD_A_PHOTO((char) 0xe439),
        GMDI_ADD_ALARM((char) 0xe193),
        GMDI_ADD_ALERT((char) 0xe003),
        GMDI_ADD_BOX((char) 0xe146),
        GMDI_ADD_CIRCLE((char) 0xe147),
        GMDI_ADD_CIRCLE_OUTLINE((char) 0xe148),
        GMDI_ADD_LOCATION((char) 0xe567),
        GMDI_ADD_SHOPPING_CART((char) 0xe854),
        GMDI_ADD_TO_PHOTOS((char) 0xe39d),
        GMDI_ADD_TO_QUEUE((char) 0xe05c),
        GMDI_ADJUST((char) 0xe39e),
        GMDI_AIRLINE_SEAT_FLAT((char) 0xe630),
        GMDI_AIRLINE_SEAT_FLAT_ANGLED((char) 0xe631),
        GMDI_AIRLINE_SEAT_INDIVIDUAL_SUITE((char) 0xe632),
        GMDI_AIRLINE_SEAT_LEGROOM_EXTRA((char) 0xe633),
        GMDI_AIRLINE_SEAT_LEGROOM_NORMAL((char) 0xe634),
        GMDI_AIRLINE_SEAT_LEGROOM_REDUCED((char) 0xe635),
        GMDI_AIRLINE_SEAT_RECLINE_EXTRA((char) 0xe636),
        GMDI_AIRLINE_SEAT_RECLINE_NORMAL((char) 0xe637),
        GMDI_AIRPLANEMODE_ACTIVE((char) 0xe195),
        GMDI_AIRPLANEMODE_INACTIVE((char) 0xe194),
        GMDI_AIRPLAY((char) 0xe055),
        GMDI_AIRPORT_SHUTTLE((char) 0xeb3c),
        GMDI_ALARM((char) 0xe855),
        GMDI_ALARM_ADD((char) 0xe856),
        GMDI_ALARM_OFF((char) 0xe857),
        GMDI_ALARM_ON((char) 0xe858),
        GMDI_ALBUM((char) 0xe019),
        GMDI_ALL_INCLUSIVE((char) 0xeb3d),
        GMDI_ALL_OUT((char) 0xe90b),
        GMDI_ANNOUNCEMENT((char) 0xe85a),
        GMDI_APPS((char) 0xe5c3),
        GMDI_ARCHIVE((char) 0xe149),
        GMDI_ARROW_BACK((char) 0xe5c4),
        GMDI_ARROW_DOWNWARD((char) 0xe5db),
        GMDI_ARROW_DROP_DOWN((char) 0xe5c5),
        GMDI_ARROW_DROP_DOWN_CIRCLE((char) 0xe5c6),
        GMDI_ARROW_DROP_UP((char) 0xe5c7),
        GMDI_ARROW_FORWARD((char) 0xe5c8),
        GMDI_ARROW_UPWARD((char) 0xe5d8),
        GMDI_ART_TRACK((char) 0xe060),
        GMDI_ASPECT_RATIO((char) 0xe85b),
        GMDI_ASSESSMENT((char) 0xe85c),
        GMDI_ASSIGNMENT((char) 0xe85d),
        GMDI_ASSIGNMENTI_IND((char) 0xe85e),
        GMDI_ASSIGNMENTI_LATE((char) 0xe85f),
        GMDI_ASSIGNMENTI_RETURN((char) 0xe860),
        GMDI_ASSIGNMENTI_RETURNED((char) 0xe861),
        GMDI_ASSIGNMENTI_TURNED_IN((char) 0xe862),
        GMDI_ASSISTANT((char) 0xe39f),
        GMDI_ASSISTANT_PHOTO((char) 0xe3a0),
        GMDI_ATTACH_FILE((char) 0xe226),
        GMDI_ATTACH_MONEY((char) 0xe227),
        GMDI_ATTACHMENT((char) 0xe2bc),
        GMDI_AUDIOTRACK((char) 0xe3a1),
        GMDI_AUTORENEW((char) 0xe863),
        GMDI_AV_TIMER((char) 0xe01b),
        GMDI_BACKSPACE((char) 0xe14a),
        GMDI_BACKUP((char) 0xe864),
        GMDI_BATTERY_ALERT((char) 0xe19c),
        GMDI_BATTERY_CHARGING_FULL((char) 0xe1a3),
        GMDI_BATTERY_FULL((char) 0xe1a4),
        GMDI_BATTERY_STD((char) 0xe1a5),
        GMDI_BATTERY_UNKNOWN((char) 0xe1a6),
        GMDI_BEACH_ACCESS((char) 0xeb3e),
        GMDI_BEENHERE((char) 0xe52d),
        GMDI_BLOCK((char) 0xe14b),
        GMDI_BLUETOOTH((char) 0xe1a7),
        GMDI_BLUETOOTH_AUDIO((char) 0xe60f),
        GMDI_BLUETOOTH_CONNECTED((char) 0xe1a8),
        GMDI_BLUETOOTH_DISABLED((char) 0xe1a9),
        GMDI_BLUETOOTH_SEARCHING((char) 0xe1aa),
        GMDI_BLUR_CIRCULAR((char) 0xe3a2),
        GMDI_BLUR_LINEAR((char) 0xe3a3),
        GMDI_BLUR_OFF((char) 0xe3a4),
        GMDI_BLUR_ON((char) 0xe3a5),
        GMDI_BOOK((char) 0xe865),
        GMDI_BOOKMARK((char) 0xe866),
        GMDI_BOOKMARK_BORDER((char) 0xe867),
        GMDI_BORDER_ALL((char) 0xe228),
        GMDI_BORDER_BOTTOM((char) 0xe229),
        GMDI_BORDER_CLEAR((char) 0xe22a),
        GMDI_BORDER_COLOR((char) 0xe22b),
        GMDI_BORDER_HORIZONTAL((char) 0xe22c),
        GMDI_BORDER_INNER((char) 0xe22d),
        GMDI_BORDER_LEFT((char) 0xe22e),
        GMDI_BORDER_OUTER((char) 0xe22f),
        GMDI_BORDER_RIGHT((char) 0xe230),
        GMDI_BORDER_STYLE((char) 0xe231),
        GMDI_BORDER_TOP((char) 0xe232),
        GMDI_BORDER_VERTICAL((char) 0xe233),
        GMDI_BRANDING_WATERMARK((char) 0xe06b),
        GMDI_BRIGHTNESS_1((char) 0xe3a6),
        GMDI_BRIGHTNESS_2((char) 0xe3a7),
        GMDI_BRIGHTNESS_3((char) 0xe3a8),
        GMDI_BRIGHTNESS_4((char) 0xe3a9),
        GMDI_BRIGHTNESS_5((char) 0xe3aa),
        GMDI_BRIGHTNESS_6((char) 0xe3ab),
        GMDI_BRIGHTNESS_7((char) 0xe3ac),
        GMDI_BRIGHTNESS_AUTO((char) 0xe1ab),
        GMDI_BRIGHTNESS_HIGH((char) 0xe1ac),
        GMDI_BRIGHTNESS_LOW((char) 0xe1ad),
        GMDI_BRIGHTNESS_MEDIUM((char) 0xe1ae),
        GMDI_BROKEN_IMAGE((char) 0xe3ad),
        GMDI_BRUSH((char) 0xe3ae),
        GMDI_BUBBLE_CHART((char) 0xe6dd),
        GMDI_BUG_REPORT((char) 0xe868),
        GMDI_BUILD((char) 0xe869),
        GMDI_BURST_MODE((char) 0xe43c),
        GMDI_BUSINESS((char) 0xe0af),
        GMDI_BUSINESS_CENTER((char) 0xeb3f),
        GMDI_CACHED((char) 0xe86a),
        GMDI_CAKE((char) 0xe7e9),
        GMDI_CALL((char) 0xe0b0),
        GMDI_CALL_END((char) 0xe0b1),
        GMDI_CALL_MADE((char) 0xe0b2),
        GMDI_CALL_MERGE((char) 0xe0b3),
        GMDI_CALL_MISSED((char) 0xe0b4),
        GMDI_CALL_MISSED_OUTGOING((char) 0xe0e4),
        GMDI_CALL_RECEIVED((char) 0xe0b5),
        GMDI_CALL_SPLIT((char) 0xe0b6),
        GMDI_CALL_TO_ACTION((char) 0xe06c),
        GMDI_CAMERA((char) 0xe3af),
        GMDI_CAMERA_ALT((char) 0xe3b0),
        GMDI_CAMERA_ENHANCE((char) 0xe8fc),
        GMDI_CAMERA_FRONT((char) 0xe3b1),
        GMDI_CAMERA_REAR((char) 0xe3b2),
        GMDI_CAMERA_ROLL((char) 0xe3b3),
        GMDI_CANCEL((char) 0xe5c9),
        GMDI_CARD_GIFTCARD((char) 0xe8f6),
        GMDI_CARD_MEMBERSHIP((char) 0xe8f7),
        GMDI_CARD_TRAVEL((char) 0xe8f8),
        GMDI_CASINO((char) 0xeb40),
        GMDI_CAST((char) 0xe307),
        GMDI_CAST_CONNECTED((char) 0xe308),
        GMDI_CENTER_FOCUS_STRONG((char) 0xe3b4),
        GMDI_CENTER_FOCUS_WEAK((char) 0xe3b5),
        GMDI_CHANGE_HISTORY((char) 0xe86b),
        GMDI_CHAT((char) 0xe0b7),
        GMDI_CHAT_BUBBLE((char) 0xe0ca),
        GMDI_CHAT_BUBBLE_OUTLINE((char) 0xe0cb),
        GMDI_CHECK((char) 0xe5ca),
        GMDI_CHECK_BOX((char) 0xe834),
        GMDI_CHECK_BOX_OUTLINE_BLANK((char) 0xe835),
        GMDI_CHECK_CIRCLE((char) 0xe86c),
        GMDI_CHEVRON_LEFT((char) 0xe5cb),
        GMDI_CHEVRON_RIGHT((char) 0xe5cc),
        GMDI_CHILD_CARE((char) 0xeb41),
        GMDI_CHILD_FRIENDLY((char) 0xeb42),
        GMDI_CHROME_READER_MODE((char) 0xe86d),
        GMDI_CLASS((char) 0xe86e),
        GMDI_CLEAR((char) 0xe14c),
        GMDI_CLEAR_ALL((char) 0xe0b8),
        GMDI_CLOSE((char) 0xe5cd),
        GMDI_CLOSED_CAPTION((char) 0xe01c),
        GMDI_CLOUD((char) 0xe2bd),
        GMDI_CLOUD_CIRCLE((char) 0xe2be),
        GMDI_CLOUD_DONE((char) 0xe2bf),
        GMDI_CLOUD_DOWNLOAD((char) 0xe2c0),
        GMDI_CLOUD_OFF((char) 0xe2c1),
        GMDI_CLOUD_QUEUE((char) 0xe2c2),
        GMDI_CLOUD_UPLOAD((char) 0xe2c3),
        GMDI_CODE((char) 0xe86f),
        GMDI_COLLECTIONS((char) 0xe3b6),
        GMDI_COLLECTIONS_BOOKMARK((char) 0xe431),
        GMDI_COLOR_LENS((char) 0xe3b7),
        GMDI_COLORIZE((char) 0xe3b8),
        GMDI_COMMENT((char) 0xe0b9),
        GMDI_COMPARE((char) 0xe3b9),
        GMDI_COMPARE_ARROWS((char) 0xe915),
        GMDI_COMPUTER((char) 0xe30a),
        GMDI_CONFIRMATION_NUMBER((char) 0xe638),
        GMDI_CONTACT_MAIL((char) 0xe0d0),
        GMDI_CONTACT_PHONE((char) 0xe0cf),
        GMDI_CONTACTS((char) 0xe0ba),
        GMDI_CONTENTI_COPY((char) 0xe14d),
        GMDI_CONTENTI_CUT((char) 0xe14e),
        GMDI_CONTENTI_PASTE((char) 0xe14f),
        GMDI_CONTROL_POINT((char) 0xe3ba),
        GMDI_CONTROL_POINT_DUPLICATE((char) 0xe3bb),
        GMDI_COPYRIGHT((char) 0xe90c),
        GMDI_CREATE((char) 0xe150),
        GMDI_CREATE_NEW_FOLDER((char) 0xe2cc),
        GMDI_CREDIT_CARD((char) 0xe870),
        GMDI_CROP((char) 0xe3be),
        GMDI_CROP_16_9((char) 0xe3bc),
        GMDI_CROP_3_2((char) 0xe3bd),
        GMDI_CROP_5_4((char) 0xe3bf),
        GMDI_CROP_7_5((char) 0xe3c0),
        GMDI_CROP_DIN((char) 0xe3c1),
        GMDI_CROP_FREE((char) 0xe3c2),
        GMDI_CROP_LANDSCAPE((char) 0xe3c3),
        GMDI_CROP_ORIGINAL((char) 0xe3c4),
        GMDI_CROP_PORTRAIT((char) 0xe3c5),
        GMDI_CROP_ROTATE((char) 0xe437),
        GMDI_CROP_SQUARE((char) 0xe3c6),
        GMDI_DASHBOARD((char) 0xe871),
        GMDI_DATA_USAGE((char) 0xe1af),
        GMDI_DATE_RANGE((char) 0xe916),
        GMDI_DEHAZE((char) 0xe3c7),
        GMDI_DELETE((char) 0xe872),
        GMDI_DELETE_FOREVER((char) 0xe92b),
        GMDI_DELETE_SWEEP((char) 0xe16c),
        GMDI_DESCRIPTION((char) 0xe873),
        GMDI_DESKTOP_MAC((char) 0xe30b),
        GMDI_DESKTOP_WINDOWS((char) 0xe30c),
        GMDI_DETAILS((char) 0xe3c8),
        GMDI_DEVELOPER_BOARD((char) 0xe30d),
        GMDI_DEVELOPER_MODE((char) 0xe1b0),
        GMDI_DEVICE_HUB((char) 0xe335),
        GMDI_DEVICES((char) 0xe1b1),
        GMDI_DEVICES_OTHER((char) 0xe337),
        GMDI_DIALER_SIP((char) 0xe0bb),
        GMDI_DIALPAD((char) 0xe0bc),
        GMDI_DIRECTIONS((char) 0xe52e),
        GMDI_DIRECTIONS_BIKE((char) 0xe52f),
        GMDI_DIRECTIONS_BOAT((char) 0xe532),
        GMDI_DIRECTIONS_BUS((char) 0xe530),
        GMDI_DIRECTIONS_CAR((char) 0xe531),
        GMDI_DIRECTIONS_RAILWAY((char) 0xe534),
        GMDI_DIRECTIONS_RUN((char) 0xe566),
        GMDI_DIRECTIONS_SUBWAY((char) 0xe533),
        GMDI_DIRECTIONS_TRANSIT((char) 0xe535),
        GMDI_DIRECTIONS_WALK((char) 0xe536),
        GMDI_DISC_FULL((char) 0xe610),
        GMDI_DNS((char) 0xe875),
        GMDI_DO_NOT_DISTURB((char) 0xe612),
        GMDI_DO_NOT_DISTURB_ALT((char) 0xe611),
        GMDI_DO_NOT_DISTURB_OFF((char) 0xe643),
        GMDI_DO_NOT_DISTURB_ON((char) 0xe644),
        GMDI_DOCK((char) 0xe30e),
        GMDI_DOMAIN((char) 0xe7ee),
        GMDI_DONE((char) 0xe876),
        GMDI_DONE_ALL((char) 0xe877),
        GMDI_DONUT_LARGE((char) 0xe917),
        GMDI_DONUT_SMALL((char) 0xe918),
        GMDI_DRAFTS((char) 0xe151),
        GMDI_DRAG_HANDLE((char) 0xe25d),
        GMDI_DRIVE_ETA((char) 0xe613),
        GMDI_DVR((char) 0xe1b2),
        GMDI_EDIT((char) 0xe3c9),
        GMDI_EDIT_LOCATION((char) 0xe568),
        GMDI_EJECT((char) 0xe8fb),
        GMDI_EMAIL((char) 0xe0be),
        GMDI_ENHANCED_ENCRYPTION((char) 0xe63f),
        GMDI_EQUALIZER((char) 0xe01d),
        GMDI_ERROR((char) 0xe000),
        GMDI_ERROR_OUTLINE((char) 0xe001),
        GMDI_EURO_SYMBOL((char) 0xe926),
        GMDI_EV_STATION((char) 0xe56d),
        GMDI_EVENT((char) 0xe878),
        GMDI_EVENTI_AVAILABLE((char) 0xe614),
        GMDI_EVENTI_BUSY((char) 0xe615),
        GMDI_EVENTI_NOTE((char) 0xe616),
        GMDI_EVENTI_SEAT((char) 0xe903),
        GMDI_EXIT_TO_APP((char) 0xe879),
        GMDI_EXPAND_LESS((char) 0xe5ce),
        GMDI_EXPAND_MORE((char) 0xe5cf),
        GMDI_EXPLICIT((char) 0xe01e),
        GMDI_EXPLORE((char) 0xe87a),
        GMDI_EXPOSURE((char) 0xe3ca),
        GMDI_EXPOSURE_NEG_1((char) 0xe3cb),
        GMDI_EXPOSURE_NEG_2((char) 0xe3cc),
        GMDI_EXPOSURE_PLUS_1((char) 0xe3cd),
        GMDI_EXPOSURE_PLUS_2((char) 0xe3ce),
        GMDI_EXPOSURE_ZERO((char) 0xe3cf),
        GMDI_EXTENSION((char) 0xe87b),
        GMDI_FACE((char) 0xe87c),
        GMDI_FAST_FORWARD((char) 0xe01f),
        GMDI_FAST_REWIND((char) 0xe020),
        GMDI_FAVORITE((char) 0xe87d),
        GMDI_FAVORITE_BORDER((char) 0xe87e),
        GMDI_FEATURED_PLAY_LIST((char) 0xe06d),
        GMDI_FEATURED_VIDEO((char) 0xe06e),
        GMDI_FEEDBACK((char) 0xe87f),
        GMDI_FIBER_DVR((char) 0xe05d),
        GMDI_FIBER_MANUAL_RECORD((char) 0xe061),
        GMDI_FIBER_NEW((char) 0xe05e),
        GMDI_FIBER_PIN((char) 0xe06a),
        GMDI_FIBER_SMART_RECORD((char) 0xe062),
        GMDI_FILE_DOWNLOAD((char) 0xe2c4),
        GMDI_FILE_UPLOAD((char) 0xe2c6),
        GMDI_FILTER((char) 0xe3d3),
        GMDI_FILTER_1((char) 0xe3d0),
        GMDI_FILTER_2((char) 0xe3d1),
        GMDI_FILTER_3((char) 0xe3d2),
        GMDI_FILTER_4((char) 0xe3d4),
        GMDI_FILTER_5((char) 0xe3d5),
        GMDI_FILTER_6((char) 0xe3d6),
        GMDI_FILTER_7((char) 0xe3d7),
        GMDI_FILTER_8((char) 0xe3d8),
        GMDI_FILTER_9((char) 0xe3d9),
        GMDI_FILTER_9_PLUS((char) 0xe3da),
        GMDI_FILTER_B_AND_W((char) 0xe3db),
        GMDI_FILTER_CENTER_FOCUS((char) 0xe3dc),
        GMDI_FILTER_DRAMA((char) 0xe3dd),
        GMDI_FILTER_FRAMES((char) 0xe3de),
        GMDI_FILTER_HDR((char) 0xe3df),
        GMDI_FILTER_LIST((char) 0xe152),
        GMDI_FILTER_NONE((char) 0xe3e0),
        GMDI_FILTER_TILT_SHIFT((char) 0xe3e2),
        GMDI_FILTER_VINTAGE((char) 0xe3e3),
        GMDI_FIND_IN_PAGE((char) 0xe880),
        GMDI_FIND_REPLACE((char) 0xe881),
        GMDI_FINGERPRINT((char) 0xe90d),
        GMDI_FIRST_PAGE((char) 0xe5dc),
        GMDI_FITNESS_CENTER((char) 0xeb43),
        GMDI_FLAG((char) 0xe153),
        GMDI_FLARE((char) 0xe3e4),
        GMDI_FLASH_AUTO((char) 0xe3e5),
        GMDI_FLASH_OFF((char) 0xe3e6),
        GMDI_FLASH_ON((char) 0xe3e7),
        GMDI_FLIGHT((char) 0xe539),
        GMDI_FLIGHT_LAND((char) 0xe904),
        GMDI_FLIGHT_TAKEOFF((char) 0xe905),
        GMDI_FLIP((char) 0xe3e8),
        GMDI_FLIP_TO_BACK((char) 0xe882),
        GMDI_FLIP_TO_FRONT((char) 0xe883),
        GMDI_FOLDER((char) 0xe2c7),
        GMDI_FOLDER_OPEN((char) 0xe2c8),
        GMDI_FOLDER_SHARED((char) 0xe2c9),
        GMDI_FOLDER_SPECIAL((char) 0xe617),
        GMDI_FONT_DOWNLOAD((char) 0xe167),
        GMDI_FORMAT_ALIGN_CENTER((char) 0xe234),
        GMDI_FORMAT_ALIGN_JUSTIFY((char) 0xe235),
        GMDI_FORMAT_ALIGN_LEFT((char) 0xe236),
        GMDI_FORMAT_ALIGN_RIGHT((char) 0xe237),
        GMDI_FORMAT_BOLD((char) 0xe238),
        GMDI_FORMAT_CLEAR((char) 0xe239),
        GMDI_FORMAT_COLOR_FILL((char) 0xe23a),
        GMDI_FORMAT_COLOR_RESET((char) 0xe23b),
        GMDI_FORMAT_COLOR_TEXT((char) 0xe23c),
        GMDI_FORMAT_INDENTI_DECREASE((char) 0xe23d),
        GMDI_FORMAT_INDENTI_INCREASE((char) 0xe23e),
        GMDI_FORMAT_ITALIC((char) 0xe23f),
        GMDI_FORMAT_LINE_SPACING((char) 0xe240),
        GMDI_FORMAT_LIST_BULLETED((char) 0xe241),
        GMDI_FORMAT_LIST_NUMBERED((char) 0xe242),
        GMDI_FORMAT_PAINT((char) 0xe243),
        GMDI_FORMAT_QUOTE((char) 0xe244),
        GMDI_FORMAT_SHAPES((char) 0xe25e),
        GMDI_FORMAT_SIZE((char) 0xe245),
        GMDI_FORMAT_STRIKETHROUGH((char) 0xe246),
        GMDI_FORMAT_TEXTDIRECTION_L_TO_R((char) 0xe247),
        GMDI_FORMAT_TEXTDIRECTION_R_TO_L((char) 0xe248),
        GMDI_FORMAT_UNDERLINED((char) 0xe249),
        GMDI_FORUM((char) 0xe0bf),
        GMDI_FORWARD((char) 0xe154),
        GMDI_FORWARD_10((char) 0xe056),
        GMDI_FORWARD_30((char) 0xe057),
        GMDI_FORWARD_5((char) 0xe058),
        GMDI_FREE_BREAKFAST((char) 0xeb44),
        GMDI_FULLSCREEN((char) 0xe5d0),
        GMDI_FULLSCREEN_EXIT((char) 0xe5d1),
        GMDI_FUNCTIONS((char) 0xe24a),
        GMDI_G_TRANSLATE((char) 0xe927),
        GMDI_GAMEPAD((char) 0xe30f),
        GMDI_GAMES((char) 0xe021),
        GMDI_GAVEL((char) 0xe90e),
        GMDI_GESTURE((char) 0xe155),
        GMDI_GET_APP((char) 0xe884),
        GMDI_GIF((char) 0xe908),
        GMDI_GOLF_COURSE((char) 0xeb45),
        GMDI_GPS_FIXED((char) 0xe1b3),
        GMDI_GPS_NOT_FIXED((char) 0xe1b4),
        GMDI_GPS_OFF((char) 0xe1b5),
        GMDI_GRADE((char) 0xe885),
        GMDI_GRADIENT((char) 0xe3e9),
        GMDI_GRAIN((char) 0xe3ea),
        GMDI_GRAPHIC_EQ((char) 0xe1b8),
        GMDI_GRID_OFF((char) 0xe3eb),
        GMDI_GRID_ON((char) 0xe3ec),
        GMDI_GROUP((char) 0xe7ef),
        GMDI_GROUP_ADD((char) 0xe7f0),
        GMDI_GROUP_WORK((char) 0xe886),
        GMDI_HD((char) 0xe052),
        GMDI_HDR_OFF((char) 0xe3ed),
        GMDI_HDR_ON((char) 0xe3ee),
        GMDI_HDR_STRONG((char) 0xe3f1),
        GMDI_HDR_WEAK((char) 0xe3f2),
        GMDI_HEADSET((char) 0xe310),
        GMDI_HEADSET_MIC((char) 0xe311),
        GMDI_HEALING((char) 0xe3f3),
        GMDI_HEARING((char) 0xe023),
        GMDI_HELP((char) 0xe887),
        GMDI_HELP_OUTLINE((char) 0xe8fd),
        GMDI_HIGH_QUALITY((char) 0xe024),
        GMDI_HIGHLIGHT((char) 0xe25f),
        GMDI_HIGHLIGHT_OFF((char) 0xe888),
        GMDI_HISTORY((char) 0xe889),
        GMDI_HOME((char) 0xe88a),
        GMDI_HOT_TUB((char) 0xeb46),
        GMDI_HOTEL((char) 0xe53a),
        GMDI_HOURGLASS_EMPTY((char) 0xe88b),
        GMDI_HOURGLASS_FULL((char) 0xe88c),
        GMDI_HTTP((char) 0xe902),
        GMDI_HTTPS((char) 0xe88d),
        GMDI_IMAGE((char) 0xe3f4),
        GMDI_IMAGE_ASPECT_RATIO((char) 0xe3f5),
        GMDI_IMPORT_CONTACTS((char) 0xe0e0),
        GMDI_IMPORT_EXPORT((char) 0xe0c3),
        GMDI_IMPORTANT_DEVICES((char) 0xe912),
        GMDI_INBOX((char) 0xe156),
        GMDI_INDETERMINATE_CHECK_BOX((char) 0xe909),
        GMDI_INFO((char) 0xe88e),
        GMDI_INFO_OUTLINE((char) 0xe88f),
        GMDI_INPUT((char) 0xe890),
        GMDI_INSERT_CHART((char) 0xe24b),
        GMDI_INSERT_COMMENT((char) 0xe24c),
        GMDI_INSERT_DRIVE_FILE((char) 0xe24d),
        GMDI_INSERT_EMOTICON((char) 0xe24e),
        GMDI_INSERT_INVITATION((char) 0xe24f),
        GMDI_INSERT_LINK((char) 0xe250),
        GMDI_INSERT_PHOTO((char) 0xe251),
        GMDI_INVERT_COLORS((char) 0xe891),
        GMDI_INVERT_COLORS_OFF((char) 0xe0c4),
        GMDI_ISO((char) 0xe3f6),
        GMDI_KEYBOARD((char) 0xe312),
        GMDI_KEYBOARD_ARROW_DOWN((char) 0xe313),
        GMDI_KEYBOARD_ARROW_LEFT((char) 0xe314),
        GMDI_KEYBOARD_ARROW_RIGHT((char) 0xe315),
        GMDI_KEYBOARD_ARROW_UP((char) 0xe316),
        GMDI_KEYBOARD_BACKSPACE((char) 0xe317),
        GMDI_KEYBOARD_CAPSLOCK((char) 0xe318),
        GMDI_KEYBOARD_HIDE((char) 0xe31a),
        GMDI_KEYBOARD_RETURN((char) 0xe31b),
        GMDI_KEYBOARD_TAB((char) 0xe31c),
        GMDI_KEYBOARD_VOICE((char) 0xe31d),
        GMDI_KITCHEN((char) 0xeb47),
        GMDI_LABEL((char) 0xe892),
        GMDI_LABEL_OUTLINE((char) 0xe893),
        GMDI_LANDSCAPE((char) 0xe3f7),
        GMDI_LANGUAGE((char) 0xe894),
        GMDI_LAPTOP((char) 0xe31e),
        GMDI_LAPTOP_CHROMEBOOK((char) 0xe31f),
        GMDI_LAPTOP_MAC((char) 0xe320),
        GMDI_LAPTOP_WINDOWS((char) 0xe321),
        GMDI_LAST_PAGE((char) 0xe5dd),
        GMDI_LAUNCH((char) 0xe895),
        GMDI_LAYERS((char) 0xe53b),
        GMDI_LAYERS_CLEAR((char) 0xe53c),
        GMDI_LEAK_ADD((char) 0xe3f8),
        GMDI_LEAK_REMOVE((char) 0xe3f9),
        GMDI_LENS((char) 0xe3fa),
        GMDI_LIBRARY_ADD((char) 0xe02e),
        GMDI_LIBRARY_BOOKS((char) 0xe02f),
        GMDI_LIBRARY_MUSIC((char) 0xe030),
        GMDI_LIGHTBULB_OUTLINE((char) 0xe90f),
        GMDI_LINE_STYLE((char) 0xe919),
        GMDI_LINE_WEIGHT((char) 0xe91a),
        GMDI_LINEAR_SCALE((char) 0xe260),
        GMDI_LINK((char) 0xe157),
        GMDI_LINKED_CAMERA((char) 0xe438),
        GMDI_LIST((char) 0xe896),
        GMDI_LIVE_HELP((char) 0xe0c6),
        GMDI_LIVE_TV((char) 0xe639),
        GMDI_LOCAL_ACTIVITY((char) 0xe53f),
        GMDI_LOCAL_AIRPORT((char) 0xe53d),
        GMDI_LOCAL_ATM((char) 0xe53e),
        GMDI_LOCAL_BAR((char) 0xe540),
        GMDI_LOCAL_CAFE((char) 0xe541),
        GMDI_LOCAL_CAR_WASH((char) 0xe542),
        GMDI_LOCAL_CONVENIENCE_STORE((char) 0xe543),
        GMDI_LOCAL_DINING((char) 0xe556),
        GMDI_LOCAL_DRINK((char) 0xe544),
        GMDI_LOCAL_FLORIST((char) 0xe545),
        GMDI_LOCAL_GAS_STATION((char) 0xe546),
        GMDI_LOCAL_GROCERY_STORE((char) 0xe547),
        GMDI_LOCAL_HOSPITAL((char) 0xe548),
        GMDI_LOCAL_HOTEL((char) 0xe549),
        GMDI_LOCAL_LAUNDRY_SERVICE((char) 0xe54a),
        GMDI_LOCAL_LIBRARY((char) 0xe54b),
        GMDI_LOCAL_MALL((char) 0xe54c),
        GMDI_LOCAL_MOVIES((char) 0xe54d),
        GMDI_LOCAL_OFFER((char) 0xe54e),
        GMDI_LOCAL_PARKING((char) 0xe54f),
        GMDI_LOCAL_PHARMACY((char) 0xe550),
        GMDI_LOCAL_PHONE((char) 0xe551),
        GMDI_LOCAL_PIZZA((char) 0xe552),
        GMDI_LOCAL_PLAY((char) 0xe553),
        GMDI_LOCAL_POST_OFFICE((char) 0xe554),
        GMDI_LOCAL_PRINTSHOP((char) 0xe555),
        GMDI_LOCAL_SEE((char) 0xe557),
        GMDI_LOCAL_SHIPPING((char) 0xe558),
        GMDI_LOCAL_TAXI((char) 0xe559),
        GMDI_LOCATION_CITY((char) 0xe7f1),
        GMDI_LOCATION_DISABLED((char) 0xe1b6),
        GMDI_LOCATION_OFF((char) 0xe0c7),
        GMDI_LOCATION_ON((char) 0xe0c8),
        GMDI_LOCATION_SEARCHING((char) 0xe1b7),
        GMDI_LOCK((char) 0xe897),
        GMDI_LOCK_OPEN((char) 0xe898),
        GMDI_LOCK_OUTLINE((char) 0xe899),
        GMDI_LOOKS((char) 0xe3fc),
        GMDI_LOOKS_3((char) 0xe3fb),
        GMDI_LOOKS_4((char) 0xe3fd),
        GMDI_LOOKS_5((char) 0xe3fe),
        GMDI_LOOKS_6((char) 0xe3ff),
        GMDI_LOOKS_ONE((char) 0xe400),
        GMDI_LOOKS_TWO((char) 0xe401),
        GMDI_LOOP((char) 0xe028),
        GMDI_LOUPE((char) 0xe402),
        GMDI_LOW_PRIORITY((char) 0xe16d),
        GMDI_LOYALTY((char) 0xe89a),
        GMDI_MAIL((char) 0xe158),
        GMDI_MAIL_OUTLINE((char) 0xe0e1),
        GMDI_MAP((char) 0xe55b),
        GMDI_MARKUNREAD((char) 0xe159),
        GMDI_MARKUNREAD_MAILBOX((char) 0xe89b),
        GMDI_MEMORY((char) 0xe322),
        GMDI_MENU((char) 0xe5d2),
        GMDI_MERGE_TYPE((char) 0xe252),
        GMDI_MESSAGE((char) 0xe0c9),
        GMDI_MIC((char) 0xe029),
        GMDI_MIC_NONE((char) 0xe02a),
        GMDI_MIC_OFF((char) 0xe02b),
        GMDI_MMS((char) 0xe618),
        GMDI_MODE_COMMENT((char) 0xe253),
        GMDI_MODE_EDIT((char) 0xe254),
        GMDI_MONETIZATION_ON((char) 0xe263),
        GMDI_MONEY_OFF((char) 0xe25c),
        GMDI_MONOCHROME_PHOTOS((char) 0xe403),
        GMDI_MOOD((char) 0xe7f2),
        GMDI_MOOD_BAD((char) 0xe7f3),
        GMDI_MORE((char) 0xe619),
        GMDI_MORE_HORIZ((char) 0xe5d3),
        GMDI_MORE_VERT((char) 0xe5d4),
        GMDI_MOTORCYCLE((char) 0xe91b),
        GMDI_MOUSE((char) 0xe323),
        GMDI_MOVE_TO_INBOX((char) 0xe168),
        GMDI_MOVIE((char) 0xe02c),
        GMDI_MOVIE_CREATION((char) 0xe404),
        GMDI_MOVIE_FILTER((char) 0xe43a),
        GMDI_MULTILINE_CHART((char) 0xe6df),
        GMDI_MUSIC_NOTE((char) 0xe405),
        GMDI_MUSIC_VIDEO((char) 0xe063),
        GMDI_MY_LOCATION((char) 0xe55c),
        GMDI_NATURE((char) 0xe406),
        GMDI_NATURE_PEOPLE((char) 0xe407),
        GMDI_NAVIGATE_BEFORE((char) 0xe408),
        GMDI_NAVIGATE_NEXT((char) 0xe409),
        GMDI_NAVIGATION((char) 0xe55d),
        GMDI_NEAR_ME((char) 0xe569),
        GMDI_NETWORK_CELL((char) 0xe1b9),
        GMDI_NETWORK_CHECK((char) 0xe640),
        GMDI_NETWORK_LOCKED((char) 0xe61a),
        GMDI_NETWORK_WIFI((char) 0xe1ba),
        GMDI_NEW_RELEASES((char) 0xe031),
        GMDI_NEXT_WEEK((char) 0xe16a),
        GMDI_NFC((char) 0xe1bb),
        GMDI_NO_ENCRYPTION((char) 0xe641),
        GMDI_NO_SIM((char) 0xe0cc),
        GMDI_NOT_INTERESTED((char) 0xe033),
        GMDI_NOTE((char) 0xe06f),
        GMDI_NOTE_ADD((char) 0xe89c),
        GMDI_NOTIFICATIONS((char) 0xe7f4),
        GMDI_NOTIFICATIONS_ACTIVE((char) 0xe7f7),
        GMDI_NOTIFICATIONS_NONE((char) 0xe7f5),
        GMDI_NOTIFICATIONS_OFF((char) 0xe7f6),
        GMDI_NOTIFICATIONS_PAUSED((char) 0xe7f8),
        GMDI_OFFLINE_PIN((char) 0xe90a),
        GMDI_ONDEMAND_VIDEO((char) 0xe63a),
        GMDI_OPACITY((char) 0xe91c),
        GMDI_OPEN_IN_BROWSER((char) 0xe89d),
        GMDI_OPEN_IN_NEW((char) 0xe89e),
        GMDI_OPEN_WITH((char) 0xe89f),
        GMDI_PAGES((char) 0xe7f9),
        GMDI_PAGEVIEW((char) 0xe8a0),
        GMDI_PALETTE((char) 0xe40a),
        GMDI_PAN_TOOL((char) 0xe925),
        GMDI_PANORAMA((char) 0xe40b),
        GMDI_PANORAMA_FISH_EYE((char) 0xe40c),
        GMDI_PANORAMA_HORIZONTAL((char) 0xe40d),
        GMDI_PANORAMA_VERTICAL((char) 0xe40e),
        GMDI_PANORAMA_WIDE_ANGLE((char) 0xe40f),
        GMDI_PARTY_MODE((char) 0xe7fa),
        GMDI_PAUSE((char) 0xe034),
        GMDI_PAUSE_CIRCLE_FILLED((char) 0xe035),
        GMDI_PAUSE_CIRCLE_OUTLINE((char) 0xe036),
        GMDI_PAYMENT((char) 0xe8a1),
        GMDI_PEOPLE((char) 0xe7fb),
        GMDI_PEOPLE_OUTLINE((char) 0xe7fc),
        GMDI_PERM_CAMERA_MIC((char) 0xe8a2),
        GMDI_PERM_CONTACT_CALENDAR((char) 0xe8a3),
        GMDI_PERM_DATA_SETTING((char) 0xe8a4),
        GMDI_PERM_DEVICE_INFORMATION((char) 0xe8a5),
        GMDI_PERM_IDENTITY((char) 0xe8a6),
        GMDI_PERM_MEDIA((char) 0xe8a7),
        GMDI_PERM_PHONE_MSG((char) 0xe8a8),
        GMDI_PERM_SCAN_WIFI((char) 0xe8a9),
        GMDI_PERSON((char) 0xe7fd),
        GMDI_PERSON_ADD((char) 0xe7fe),
        GMDI_PERSON_OUTLINE((char) 0xe7ff),
        GMDI_PERSON_PIN((char) 0xe55a),
        GMDI_PERSON_PIN_CIRCLE((char) 0xe56a),
        GMDI_PERSONAL_VIDEO((char) 0xe63b),
        GMDI_PETS((char) 0xe91d),
        GMDI_PHONE((char) 0xe0cd),
        GMDI_PHONE_BLUETOOTH_SPEAKER((char) 0xe61b),
        GMDI_PHONE_FORWARDED((char) 0xe61c),
        GMDI_PHONE_IN_TALK((char) 0xe61d),
        GMDI_PHONE_IPHONE((char) 0xe325),
        GMDI_PHONE_LOCKED((char) 0xe61e),
        GMDI_PHONE_MISSED((char) 0xe61f),
        GMDI_PHONE_PAUSED((char) 0xe620),
        GMDI_PHONELINK((char) 0xe326),
        GMDI_PHONELINK_ERASE((char) 0xe0db),
        GMDI_PHONELINK_LOCK((char) 0xe0dc),
        GMDI_PHONELINK_OFF((char) 0xe327),
        GMDI_PHONELINK_RING((char) 0xe0dd),
        GMDI_PHONELINK_SETUP((char) 0xe0de),
        GMDI_PHOTO((char) 0xe410),
        GMDI_PHOTO_ALBUM((char) 0xe411),
        GMDI_PHOTO_CAMERA((char) 0xe412),
        GMDI_PHOTO_FILTER((char) 0xe43b),
        GMDI_PHOTO_LIBRARY((char) 0xe413),
        GMDI_PHOTO_SIZE_SELECT_ACTUAL((char) 0xe432),
        GMDI_PHOTO_SIZE_SELECT_LARGE((char) 0xe433),
        GMDI_PHOTO_SIZE_SELECT_SMALL((char) 0xe434),
        GMDI_PICTURE_AS_PDF((char) 0xe415),
        GMDI_PICTURE_IN_PICTURE((char) 0xe8aa),
        GMDI_PICTURE_IN_PICTURE_ALT((char) 0xe911),
        GMDI_PIE_CHART((char) 0xe6c4),
        GMDI_PIE_CHART_OUTLINED((char) 0xe6c5),
        GMDI_PIN_DROP((char) 0xe55e),
        GMDI_PLACE((char) 0xe55f),
        GMDI_PLAY_ARROW((char) 0xe037),
        GMDI_PLAY_CIRCLE_FILLED((char) 0xe038),
        GMDI_PLAY_CIRCLE_OUTLINE((char) 0xe039),
        GMDI_PLAY_FOR_WORK((char) 0xe906),
        GMDI_PLAYLIST_ADD((char) 0xe03b),
        GMDI_PLAYLIST_ADD_CHECK((char) 0xe065),
        GMDI_PLAYLIST_PLAY((char) 0xe05f),
        GMDI_PLUS_ONE((char) 0xe800),
        GMDI_POLL((char) 0xe801),
        GMDI_POLYMER((char) 0xe8ab),
        GMDI_POOL((char) 0xeb48),
        GMDI_PORTABLE_WIFI_OFF((char) 0xe0ce),
        GMDI_PORTRAIT((char) 0xe416),
        GMDI_POWER((char) 0xe63c),
        GMDI_POWER_INPUT((char) 0xe336),
        GMDI_POWER_SETTINGS_NEW((char) 0xe8ac),
        GMDI_PREGNANT_WOMAN((char) 0xe91e),
        GMDI_PRESENTI_TO_ALL((char) 0xe0df),
        GMDI_PRINT((char) 0xe8ad),
        GMDI_PRIORITY_HIGH((char) 0xe645),
        GMDI_PUBLIC((char) 0xe80b),
        GMDI_PUBLISH((char) 0xe255),
        GMDI_QUERY_BUILDER((char) 0xe8ae),
        GMDI_QUESTION_ANSWER((char) 0xe8af),
        GMDI_QUEUE((char) 0xe03c),
        GMDI_QUEUE_MUSIC((char) 0xe03d),
        GMDI_QUEUE_PLAY_NEXT((char) 0xe066),
        GMDI_RADIO((char) 0xe03e),
        GMDI_RADIO_BUTTON_CHECKED((char) 0xe837),
        GMDI_RADIO_BUTTON_UNCHECKED((char) 0xe836),
        GMDI_RATE_REVIEW((char) 0xe560),
        GMDI_RECEIPT((char) 0xe8b0),
        GMDI_RECENTI_ACTORS((char) 0xe03f),
        GMDI_RECORD_VOICE_OVER((char) 0xe91f),
        GMDI_REDEEM((char) 0xe8b1),
        GMDI_REDO((char) 0xe15a),
        GMDI_REFRESH((char) 0xe5d5),
        GMDI_REMOVE((char) 0xe15b),
        GMDI_REMOVE_CIRCLE((char) 0xe15c),
        GMDI_REMOVE_CIRCLE_OUTLINE((char) 0xe15d),
        GMDI_REMOVE_FROM_QUEUE((char) 0xe067),
        GMDI_REMOVE_RED_EYE((char) 0xe417),
        GMDI_REMOVE_SHOPPING_CART((char) 0xe928),
        GMDI_REORDER((char) 0xe8fe),
        GMDI_REPEAT((char) 0xe040),
        GMDI_REPEAT_ONE((char) 0xe041),
        GMDI_REPLAY((char) 0xe042),
        GMDI_REPLAY_10((char) 0xe059),
        GMDI_REPLAY_30((char) 0xe05a),
        GMDI_REPLAY_5((char) 0xe05b),
        GMDI_REPLY((char) 0xe15e),
        GMDI_REPLY_ALL((char) 0xe15f),
        GMDI_REPORT((char) 0xe160),
        GMDI_REPORT_PROBLEM((char) 0xe8b2),
        GMDI_RESTAURANT((char) 0xe56c),
        GMDI_RESTAURANT_MENU((char) 0xe561),
        GMDI_RESTORE((char) 0xe8b3),
        GMDI_RESTORE_PAGE((char) 0xe929),
        GMDI_RING_VOLUME((char) 0xe0d1),
        GMDI_ROOM((char) 0xe8b4),
        GMDI_ROOM_SERVICE((char) 0xeb49),
        GMDI_ROTATE_90_DEGREES_CCW((char) 0xe418),
        GMDI_ROTATE_LEFT((char) 0xe419),
        GMDI_ROTATE_RIGHT((char) 0xe41a),
        GMDI_ROUNDED_CORNER((char) 0xe920),
        GMDI_ROUTER((char) 0xe328),
        GMDI_ROWING((char) 0xe921),
        GMDI_RSS_FEED((char) 0xe0e5),
        GMDI_RV_HOOKUP((char) 0xe642),
        GMDI_SATELLITE((char) 0xe562),
        GMDI_SAVE((char) 0xe161),
        GMDI_SCANNER((char) 0xe329),
        GMDI_SCHEDULE((char) 0xe8b5),
        GMDI_SCHOOL((char) 0xe80c),
        GMDI_SCREEN_LOCK_LANDSCAPE((char) 0xe1be),
        GMDI_SCREEN_LOCK_PORTRAIT((char) 0xe1bf),
        GMDI_SCREEN_LOCK_ROTATION((char) 0xe1c0),
        GMDI_SCREEN_ROTATION((char) 0xe1c1),
        GMDI_SCREEN_SHARE((char) 0xe0e2),
        GMDI_SD_CARD((char) 0xe623),
        GMDI_SD_STORAGE((char) 0xe1c2),
        GMDI_SEARCH((char) 0xe8b6),
        GMDI_SECURITY((char) 0xe32a),
        GMDI_SELECT_ALL((char) 0xe162),
        GMDI_SEND((char) 0xe163),
        GMDI_SENTIMENTI_DISSATISFIED((char) 0xe811),
        GMDI_SENTIMENTI_NEUTRAL((char) 0xe812),
        GMDI_SENTIMENTI_SATISFIED((char) 0xe813),
        GMDI_SENTIMENTI_VERY_DISSATISFIED((char) 0xe814),
        GMDI_SENTIMENTI_VERY_SATISFIED((char) 0xe815),
        GMDI_SETTINGS((char) 0xe8b8),
        GMDI_SETTINGS_APPLICATIONS((char) 0xe8b9),
        GMDI_SETTINGS_BACKUP_RESTORE((char) 0xe8ba),
        GMDI_SETTINGS_BLUETOOTH((char) 0xe8bb),
        GMDI_SETTINGS_BRIGHTNESS((char) 0xe8bd),
        GMDI_SETTINGS_CELL((char) 0xe8bc),
        GMDI_SETTINGS_ETHERNET((char) 0xe8be),
        GMDI_SETTINGS_INPUT_ANTENNA((char) 0xe8bf),
        GMDI_SETTINGS_INPUT_COMPONENT((char) 0xe8c0),
        GMDI_SETTINGS_INPUT_COMPOSITE((char) 0xe8c1),
        GMDI_SETTINGS_INPUT_HDMI((char) 0xe8c2),
        GMDI_SETTINGS_INPUT_SVIDEO((char) 0xe8c3),
        GMDI_SETTINGS_OVERSCAN((char) 0xe8c4),
        GMDI_SETTINGS_PHONE((char) 0xe8c5),
        GMDI_SETTINGS_POWER((char) 0xe8c6),
        GMDI_SETTINGS_REMOTE((char) 0xe8c7),
        GMDI_SETTINGS_SYSTEM_DAYDREAM((char) 0xe1c3),
        GMDI_SETTINGS_VOICE((char) 0xe8c8),
        GMDI_SHARE((char) 0xe80d),
        GMDI_SHOP((char) 0xe8c9),
        GMDI_SHOP_TWO((char) 0xe8ca),
        GMDI_SHOPPING_BASKET((char) 0xe8cb),
        GMDI_SHOPPING_CART((char) 0xe8cc),
        GMDI_SHORT_TEXT((char) 0xe261),
        GMDI_SHOW_CHART((char) 0xe6e1),
        GMDI_SHUFFLE((char) 0xe043),
        GMDI_SIGNAL_CELLULAR_4_BAR((char) 0xe1c8),
        GMDI_SIGNAL_CELLULAR_CONNECTED_NO_INTERNET_4_BAR((char) 0xe1cd),
        GMDI_SIGNAL_CELLULAR_NO_SIM((char) 0xe1ce),
        GMDI_SIGNAL_CELLULAR_NULL((char) 0xe1cf),
        GMDI_SIGNAL_CELLULAR_OFF((char) 0xe1d0),
        GMDI_SIGNAL_WIFI_4_BAR((char) 0xe1d8),
        GMDI_SIGNAL_WIFI_4_BAR_LOCK((char) 0xe1d9),
        GMDI_SIGNAL_WIFI_OFF((char) 0xe1da),
        GMDI_SIM_CARD((char) 0xe32b),
        GMDI_SIM_CARD_ALERT((char) 0xe624),
        GMDI_SKIP_NEXT((char) 0xe044),
        GMDI_SKIP_PREVIOUS((char) 0xe045),
        GMDI_SLIDESHOW((char) 0xe41b),
        GMDI_SLOW_MOTION_VIDEO((char) 0xe068),
        GMDI_SMARTPHONE((char) 0xe32c),
        GMDI_SMOKE_FREE((char) 0xeb4a),
        GMDI_SMOKING_ROOMS((char) 0xeb4b),
        GMDI_SMS((char) 0xe625),
        GMDI_SMS_FAILED((char) 0xe626),
        GMDI_SNOOZE((char) 0xe046),
        GMDI_SORT((char) 0xe164),
        GMDI_SORT_BY_ALPHA((char) 0xe053),
        GMDI_SPA((char) 0xeb4c),
        GMDI_SPACE_BAR((char) 0xe256),
        GMDI_SPEAKER((char) 0xe32d),
        GMDI_SPEAKER_GROUP((char) 0xe32e),
        GMDI_SPEAKER_NOTES((char) 0xe8cd),
        GMDI_SPEAKER_NOTES_OFF((char) 0xe92a),
        GMDI_SPEAKER_PHONE((char) 0xe0d2),
        GMDI_SPELLCHECK((char) 0xe8ce),
        GMDI_STAR((char) 0xe838),
        GMDI_STAR_BORDER((char) 0xe83a),
        GMDI_STAR_HALF((char) 0xe839),
        GMDI_STARS((char) 0xe8d0),
        GMDI_STAY_CURRENTI_LANDSCAPE((char) 0xe0d3),
        GMDI_STAY_CURRENTI_PORTRAIT((char) 0xe0d4),
        GMDI_STAY_PRIMARY_LANDSCAPE((char) 0xe0d5),
        GMDI_STAY_PRIMARY_PORTRAIT((char) 0xe0d6),
        GMDI_STOP((char) 0xe047),
        GMDI_STOP_SCREEN_SHARE((char) 0xe0e3),
        GMDI_STORAGE((char) 0xe1db),
        GMDI_STORE((char) 0xe8d1),
        GMDI_STORE_MALL_DIRECTORY((char) 0xe563),
        GMDI_STRAIGHTEN((char) 0xe41c),
        GMDI_STREETVIEW((char) 0xe56e),
        GMDI_STRIKETHROUGH_S((char) 0xe257),
        GMDI_STYLE((char) 0xe41d),
        GMDI_SUBDIRECTORY_ARROW_LEFT((char) 0xe5d9),
        GMDI_SUBDIRECTORY_ARROW_RIGHT((char) 0xe5da),
        GMDI_SUBJECT((char) 0xe8d2),
        GMDI_SUBSCRIPTIONS((char) 0xe064),
        GMDI_SUBTITLES((char) 0xe048),
        GMDI_SUBWAY((char) 0xe56f),
        GMDI_SUPERVISOR_ACCOUNT((char) 0xe8d3),
        GMDI_SURROUND_SOUND((char) 0xe049),
        GMDI_SWAP_CALLS((char) 0xe0d7),
        GMDI_SWAP_HORIZ((char) 0xe8d4),
        GMDI_SWAP_VERT((char) 0xe8d5),
        GMDI_SWAP_VERTICAL_CIRCLE((char) 0xe8d6),
        GMDI_SWITCH_CAMERA((char) 0xe41e),
        GMDI_SWITCH_VIDEO((char) 0xe41f),
        GMDI_SYNC((char) 0xe627),
        GMDI_SYNC_DISABLED((char) 0xe628),
        GMDI_SYNC_PROBLEM((char) 0xe629),
        GMDI_SYSTEM_UPDATE((char) 0xe62a),
        GMDI_SYSTEM_UPDATE_ALT((char) 0xe8d7),
        GMDI_TAB((char) 0xe8d8),
        GMDI_TAB_UNSELECTED((char) 0xe8d9),
        GMDI_TABLET((char) 0xe32f),
        GMDI_TABLET_MAC((char) 0xe331),
        GMDI_TAG_FACES((char) 0xe420),
        GMDI_TAP_AND_PLAY((char) 0xe62b),
        GMDI_TERRAIN((char) 0xe564),
        GMDI_TEXT_FIELDS((char) 0xe262),
        GMDI_TEXT_FORMAT((char) 0xe165),
        GMDI_TEXTSMS((char) 0xe0d8),
        GMDI_TEXTURE((char) 0xe421),
        GMDI_THEATERS((char) 0xe8da),
        GMDI_THUMB_DOWN((char) 0xe8db),
        GMDI_THUMB_UP((char) 0xe8dc),
        GMDI_THUMBS_UP_DOWN((char) 0xe8dd),
        GMDI_TIME_TO_LEAVE((char) 0xe62c),
        GMDI_TIMELAPSE((char) 0xe422),
        GMDI_TIMELINE((char) 0xe922),
        GMDI_TIMER((char) 0xe425),
        GMDI_TIMER_10((char) 0xe423),
        GMDI_TIMER_3((char) 0xe424),
        GMDI_TIMER_OFF((char) 0xe426),
        GMDI_TITLE((char) 0xe264),
        GMDI_TOC((char) 0xe8de),
        GMDI_TODAY((char) 0xe8df),
        GMDI_TOLL((char) 0xe8e0),
        GMDI_TONALITY((char) 0xe427),
        GMDI_TOUCH_APP((char) 0xe913),
        GMDI_TOYS((char) 0xe332),
        GMDI_TRACK_CHANGES((char) 0xe8e1),
        GMDI_TRAFFIC((char) 0xe565),
        GMDI_TRAIN((char) 0xe570),
        GMDI_TRAM((char) 0xe571),
        GMDI_TRANSFER_WITHIN_A_STATION((char) 0xe572),
        GMDI_TRANSFORM((char) 0xe428),
        GMDI_TRANSLATE((char) 0xe8e2),
        GMDI_TRENDING_DOWN((char) 0xe8e3),
        GMDI_TRENDING_FLAT((char) 0xe8e4),
        GMDI_TRENDING_UP((char) 0xe8e5),
        GMDI_TUNE((char) 0xe429),
        GMDI_TURNED_IN((char) 0xe8e6),
        GMDI_TURNED_IN_NOT((char) 0xe8e7),
        GMDI_TV((char) 0xe333),
        GMDI_UNARCHIVE((char) 0xe169),
        GMDI_UNDO((char) 0xe166),
        GMDI_UNFOLD_LESS((char) 0xe5d6),
        GMDI_UNFOLD_MORE((char) 0xe5d7),
        GMDI_UPDATE((char) 0xe923),
        GMDI_USB((char) 0xe1e0),
        GMDI_VERIFIED_USER((char) 0xe8e8),
        GMDI_VERTICAL_ALIGN_BOTTOM((char) 0xe258),
        GMDI_VERTICAL_ALIGN_CENTER((char) 0xe259),
        GMDI_VERTICAL_ALIGN_TOP((char) 0xe25a),
        GMDI_VIBRATION((char) 0xe62d),
        GMDI_VIDEO_CALL((char) 0xe070),
        GMDI_VIDEO_LABEL((char) 0xe071),
        GMDI_VIDEO_LIBRARY((char) 0xe04a),
        GMDI_VIDEOCAM((char) 0xe04b),
        GMDI_VIDEOCAM_OFF((char) 0xe04c),
        GMDI_VIDEOGAME_ASSET((char) 0xe338),
        GMDI_VIEW_AGENDA((char) 0xe8e9),
        GMDI_VIEW_ARRAY((char) 0xe8ea),
        GMDI_VIEW_CAROUSEL((char) 0xe8eb),
        GMDI_VIEW_COLUMN((char) 0xe8ec),
        GMDI_VIEW_COMFY((char) 0xe42a),
        GMDI_VIEW_COMPACT((char) 0xe42b),
        GMDI_VIEW_DAY((char) 0xe8ed),
        GMDI_VIEW_HEADLINE((char) 0xe8ee),
        GMDI_VIEW_LIST((char) 0xe8ef),
        GMDI_VIEW_MODULE((char) 0xe8f0),
        GMDI_VIEW_QUILT((char) 0xe8f1),
        GMDI_VIEW_STREAM((char) 0xe8f2),
        GMDI_VIEW_WEEK((char) 0xe8f3),
        GMDI_VIGNETTE((char) 0xe435),
        GMDI_VISIBILITY((char) 0xe8f4),
        GMDI_VISIBILITY_OFF((char) 0xe8f5),
        GMDI_VOICE_CHAT((char) 0xe62e),
        GMDI_VOICEMAIL((char) 0xe0d9),
        GMDI_VOLUME_DOWN((char) 0xe04d),
        GMDI_VOLUME_MUTE((char) 0xe04e),
        GMDI_VOLUME_OFF((char) 0xe04f),
        GMDI_VOLUME_UP((char) 0xe050),
        GMDI_VPN_KEY((char) 0xe0da),
        GMDI_VPN_LOCK((char) 0xe62f),
        GMDI_WALLPAPER((char) 0xe1bc),
        GMDI_WARNING((char) 0xe002),
        GMDI_WATCH((char) 0xe334),
        GMDI_WATCH_LATER((char) 0xe924),
        GMDI_WB_AUTO((char) 0xe42c),
        GMDI_WB_CLOUDY((char) 0xe42d),
        GMDI_WB_INCANDESCENT((char) 0xe42e),
        GMDI_WB_IRIDESCENT((char) 0xe436),
        GMDI_WB_SUNNY((char) 0xe430),
        GMDI_WC((char) 0xe63d),
        GMDI_WEB((char) 0xe051),
        GMDI_WEB_ASSET((char) 0xe069),
        GMDI_WEEKEND((char) 0xe16b),
        GMDI_WHATSHOT((char) 0xe80e),
        GMDI_WIDGETS((char) 0xe1bd),
        GMDI_WIFI((char) 0xe63e),
        GMDI_WIFI_LOCK((char) 0xe1e1),
        GMDI_WIFI_TETHERING((char) 0xe1e2),
        GMDI_WORK((char) 0xe8f9),
        GMDI_WRAP_TEXT((char) 0xe25b),
        GMDI_YOUTUBE_SEARCHED_FOR((char) 0xe8fa),
        GMDI_ZOOM_IN((char) 0xe8ff),
        GMDI_ZOOM_OUT((char) 0xe900),
        GMDI_ZOOM_OUT_MAP((char) 0xe56b);

        char googleMaterialCharacter;

        Icon(char character) {
            this.googleMaterialCharacter = character;
        }

        public String getFormattedName() {
            return "{" + name() + "}";
        }

        public char getCharacter() {
            return googleMaterialCharacter;
        }

        public String getName() {
            return name();
        }

        // remember the typeface so we can use it later
        private static MfbTypeface googleMaterialTypeface;

        @Override
        public MfbTypeface getTypeface() {
            if (googleMaterialTypeface == null) {
                setTypeface(new GoogleMaterial());
            }
            return googleMaterialTypeface;
        }

        private static void setTypeface(GoogleMaterial googleMaterialTypeface) {
            Icon.googleMaterialTypeface = googleMaterialTypeface;
        }
    }
}
